### ISSUE TITLE
Consider adding a "first run" info

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#10006]
Maybe we should add a short introduction how HTTPS-Everywhere works or what differs from the legacy version.

**Comment by J0WI** [comment]
At least a short FAQ about "What happened to my SSL Observatory?" would be great.

**Comment by Hainish** [comment]
I often find the first-time run dialogues annoying - what is it adding to the user experience?  Just one more click?  We should evaluate the trade-offs here.

The way the `SSL Observatory` first-time run popup currently works is that there is a config boolean value for whether it has been seen or not before: `extensions.https_everywhere._observatory.popup_shown`.  If not, it is shown and the flag is set to `true`.  Within Tor Browser, this flag is manually set to `true` so that the dialogue does not appear for all new Tor Browser users.

We can certainly do this within [`chrome.storage`](https://developer.chrome.com/extensions/storage), but one tricky thing is that I'm not sure if there is a manual way to set values in `chrome.storage` for an extension without it having been run before.  I'll have to look into this.

**Comment by J0WI** [comment]
We also had this bar on the top "HTTPS Everywhere is now active ..." with the FAQ button.

**Comment by Hainish** [comment]
Sorry, I'm misunderstanding.  Where did we have this?

**Comment by J0WI** [comment]
I think it's here:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/toolbar_button.js#L115-L157

**Comment by jeremyn** [comment]
I agree with @Hainish here, we don't need a first run notice for this change. I have no statistical data but I guess HTTPS Everywhere isn't something most people interact with or think about when they're using it. A first run notice for an obscure change would probably be confusing instead of helpful.

Also remember that HTTPS Everywhere is on the short list of add-ons that are recommended for and installed by technical people on behalf on less-technical people, so the people who see this notice may not even know they are using HTTPS Everywhere or even what an add-on is.

Instead of a first run notice, another option is to include a temporary clickable menu item to the UI like "Why did the UI change?" that we keep for a few Firefox release cycles and then remove. It could go between "About HTTPS Everywhere" and "Donate to EFF", for example.

**Comment by Hainish** [comment]
I'm closing this due to the concerns mentioned.  If a link in the menu is desired, please open another issue and we can discuss it there.
