### ISSUE TITLE
Update FAQ entry regarding Safari support

### ISSUE THREAD

**Issue by apple-web-evangelist** [EFForg/https-everywhere#10020]
The current FAQ entry regarding Safari states that the Safari Extension API does not offer a way to perform secure rewriting of HTTP requests to HTTPS.

The Content Blocker Extension action `make-https` will change a URL from HTTP to HTTPS before making a server request. For more information see: https://developer.apple.com/library/content/documentation/Extensions/Conceptual/ContentBlockingRules/CreatingRules/CreatingRules.html#//apple_ref/doc/uid/TP40016265-CH2-SW7

The FAQ entry is located here:
https://www.eff.org/https-everywhere/faq#will-there-be-a-version-of-https-everywhere-for-ie-safari-or-some-other-browser

The FAQ entry should be updated with EFF's new plans regarding Safari support in light of this new capability.

**Comment by jeremyn** [comment]
@Hainish Thoughts?

**Comment by Hainish** [comment]
We still have to have our lawyers look at the developer license agreement in order to determine if there's any way we can publish HTTPS Everywhere on the Safari extension distribution channel.  It's on their queue currently.

**Comment by jeremyn** [comment]
I found related issue https://github.com/EFForg/https-everywhere/issues/5121 while browsing through older issues, so I'm noting it here.

**Comment by Hainish** [comment]
Due to overly burdensome developer license agreement restrictions, we will not be developing a Safari extension for HTTPS Everywhere or Privacy Badger.  Others have taken our code and developed derivative works for HTTPS Everywhere, though.  If you're interested, you can follow the discussion here: https://github.com/EFForg/https-everywhere/issues/5121
