### ISSUE TITLE
HTTPS-Everywhere retains the last ruleset after clicking on 'View image'

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10039]
Take for example [this stackexchange question](https://photo.stackexchange.com/questions/2627/good-examples-of-raws-advantages-over-jpeg).

When you right-click on any picture in this thread and select `View image`, you are linked to https://i.stack.imgur.com/.

If you then look at the active rulesets on that page:
- The legacy XPCOM HTTPS-Everywhere lists `Imgur.com`
- The new WebExtensions HTTPS-Everywhere lists `Stack Exchange (partial)` even though that ruleset is not active on that page. (I don't know if that fact it fails to mention `Imgur.com` is due to #9965 or not)

Related: #9958

**Comment by Hainish** [comment]
For some reason, when we set the filter argument for https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onBeforeRequest to listen to all https urls and all http urls, onBeforeRequest isn't fired often in Firefox.  Notably, it's not fired on page reloads or when you view an image.

Changing this to the special string "<all_urls>" fixes this.

**Comment by Hainish** [comment]
This has been fixed in https://github.com/EFForg/https-everywhere/tree/master because I want to make sure that this doesn't interfere with any chrome functionality.  It really shouldn't, but just in case, it's better to get bug reports on the next release (before we deploy webextensions) than have to deal with all the problems at once when we merge the `webextensions` branch.  The next test release will rebase from master, so you should be able to verify this when I deploy that.

**Comment by Hainish** [comment]
Ref: https://github.com/EFForg/https-everywhere/commit/79ca764f32cffec9dbda3b494d58c0cd2f7c2ab9
