### ISSUE TITLE
Help reviewers identify ruleset fixes

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10231]
I think pull requests fixing rulesets that were previously preventing HTTPS-Everywhere users from accessing or properly using a website should be prioritized. Ideally, they should be included in the first release following the PR.

However, simply due to the daily number of pull requests, it is not easy for reviewers to catch such PR.

How can we help reviewers prioritize those PR?

- Simply ping them in the PR but that may generate a lot of mailbox spam
- Use a bot to auto-tag those PR (with `ruleset-bug` label and `Before the Next Release` milestone) based on a certain keyword (for example `ruleset-fix` in the PR title)
- List those PR in the release issue

**Comment by jeremyn** [comment]
This isn't really how reviewing works for me. I review stuff that I feel like reviewing. There is no ping/tag/milestone/bot that is going to particularly motivate me. In fact the only time I'm okay with being pinged is if another reviewer needs something or if there is a process/policy discussion that someone wants my opinion on.

If someone thinks something is truly urgent then they can contact the EFF directly and the EFF can get it fixed. If it's not important enough to convince the EFF to fix it, then it's not important enough to ping me about, because the EFF are the ones getting paid to do this, not me.

One of the reasons I keep trying to [encourage diversity](https://github.com/EFForg/https-everywhere/issues/8900#issuecomment-284281410) in the project is in the hope of attracting enough reviewers to cover enough areas that someone will want to work on and review a wide range of issues and PRs.

**Comment by Bisaloo** [comment]
Okay, I see.

From my point of view, rulesets fixes should be prioritized compared to new rules because bugs reduce usability and may turn people away from HTTPS-Everywhere. But I totally get your point.

I guess the aim of this issue was to find a way to *inform* reviewers that a ruleset fix is ready, not tell them what they should do during their free time.

What do you think?

**Comment by jeremyn** [comment]
The `ruleset-bug` label is enough for me. I don't think there is any way to autolabel effectively without having an overengineered bot or trying to force contributors to use rigid templates. People are not going to use something like `ruleset-fix` reliably.
