### ISSUE TITLE
Reuters.com doesn't switch to HTTPS even though it's available

### ISSUE THREAD

**Issue by notasan** [EFForg/https-everywhere#10686]
HTTPS Everywhere is enabled in Firefox, but if I go to reuters.com, it remains unencrypted. If I go to https://www.reuters.com it works.

This most likely has something to do with the www. prefix.

Could it be an idea to implement a list in the plug-in that contains special instructions to switch to https for some websites?

tl;dr HTTPS Everywhere does not enable HTTPS on reuters.com because merely changing http:// to https:// is not enough; it needs to change http:// to https://www..

**Comment by Bisaloo** [comment]
Hi, thanks for reaching out!

> Could it be an idea to implement a list in the plug-in that contains special instructions to switch to https for some websites?

This is actually what this extension is doing. It relies on user contributed rules to rewrite websites to https because it is indeed sometimes more complicated than simply rewriting `http` to `https`. [Here](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Nature.com.xml) is an example of a such ruleset.

The reuters ruleset is [https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Reuters.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Reuters.com.xml). [This guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md) should be enough to get you started if you want to try and fix it yourself.
