### ISSUE TITLE
Update https://www.eff.org/https-everywhere/rulesets

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1074]
Right now https://www.eff.org/https-everywhere/rulesets doesn't reference the new test coverage requirements or style guide. We need to update it to take those into account.

As part of that process, we should submit the current version of that page to the repository and edit it here, so it is easier for contributors to make changes. The maintainer (currently me) will still have to manually copy those changes into the live site.

**Comment by guiweber** [comment]
@jsha Why not put all the rule writing documentation into the github wiki and link to it from the EFF website? I feel it would be easier to find the info you need if all information was at the same place. Currently you have to check the website, rule-style.md and ruleset-testing.md. This is not clear for people just getting started, especially since these resources do not all have links to each other nor do they all mention each other.

**Comment by guiweber** [comment]
@jsha Re-reading you note I realize I might have read to fast... you were actually saying that the content of rule-style.md and ruleset-testing.md should be on the website, which would address the issue I was referring to.

But wouldn't a wiki be easier to maintain and offer a better structure for documentation anyway?

**Comment by jsha** [comment]
This is now fixed by revising the rulesets page, now maintained under the doc/ directory and copied to the EFF website.

@guiweber: I think the GitHub wiki would only allow edits from contributors, while we can take pull requests to the .md files. Additionally, it's nice to have the documentation included in the repo. That way we are more free to choose a different repo host in future.
