### ISSUE TITLE
zh-CN should be zh_CN in translations, for Chrome

### ISSUE THREAD

**Issue by yfdyh000** [EFForg/https-everywhere#10814]
In addition, why releases no locales except `en`?

**Comment by Bisaloo** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/9631

**Comment by Bisaloo** [comment]
Somewhat related: https://github.com/EFForg/https-everywhere/issues/9631

**Comment by gloomy-ghost** [comment]
Ping @Hainish

**Comment by Hainish** [comment]
The `en` locale is used as a template for translations that are performed in transifex.

To quote https://github.com/EFForg/https-everywhere/blob/83f6bb5233dd5cc49175cbd44b0fccf973242a42/src/chrome/locale/README.txt#L13-L15
> If you'd like to add a new string for translation, add it to the `en` locale.
> Once your change has been merged to master, it will show up in Transifex as
> available for translation.

All other locales are located in the `translations` subrepo.

**Comment by gloomy-ghost** [comment]
The thing is `zh-CN` is not recognised by Chrome, as it should be `zh_CN`. Also the current WebExtension beta for Firefox only includes the `en` locale.

**Comment by Hainish** [comment]
Translations have already been made under the `zh-CN` label, rather than `zh_CN`, see https://gitweb.torproject.org/translation.git/tree/?h=https_everywhere

This means that changing this locale may remove this translation from being sourced from transifex.  If this is the case, we'll have to re-add the translations from what we have in `zh-CN`.

I'll look into the mozilla translations problem.

**Comment by yfdyh000** [comment]
Maybe mv zh-CN to zh_CN in makecrx.sh is acceptable.

**Comment by Hainish** [comment]
No, we don't want to be making all these exceptions in build scripts because of irregularities.

**Comment by Hainish** [comment]
The translations repo has been updated, this should be fixed, please:

```bash
cd translations
git pull origin https_everywhere
cd ..
test/chromium.sh --justrun
```

to confirm.

**Comment by Hainish** [comment]
I just tested using the `zh_cn` locale, seems to be working, closing.

**Comment by Hainish** [comment]
@gloomy-ghost wow, I just looked into the translations issue, and it looks like translations weren't being pulled into the Chrome extension at all in general!  This was fixed in https://github.com/EFForg/https-everywhere/commit/a7fcdf3b20e1e9554dd76dbd6d66458b7ab5af0a and is incorporated into the newest test release, `2017.7.21.1338`: https://www.eff.org/files/https-everywhere-test/index.html

**Comment by Hainish** [comment]
Ref: https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-317146470
