### ISSUE TITLE
Fetcher should send headers of an actual browser

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#10873]
This can help us to avoid issues like #9877 where the fetching test failed because the site used header sniffing to determine bots. In addition, We should send excally the same headers, as some sites are sniffing headers other than User-Agent. e.g. [sniffing of `upgrade-insecure-requests`](https://github.com/EFForg/https-everywhere/pull/8940#issuecomment-287646604)

**Comment by J0WI** [comment]
See also #10833

**Comment by Hainish** [comment]
@gloomy-ghost this is always the goal, but I don't think we need to open an issue for this.  Especially because there are strange idiosyncrasies with pyCurl, we're never going to get 100% alignment with the browsers, see https://github.com/EFForg/https-everywhere/pull/10944.  Plus the browsers are a moving target.

I suggest a more specific issue, like "Update user-agent string to Firefox 52" or something like that.
