### ISSUE TITLE
Do not restart Firefox after installing this plugin

### ISSUE THREAD

**Issue by chhantyal** [EFForg/https-everywhere#1123]
As far as I know, Firefox already supports plugin install without restarting browser.

It would be great if this plugin also works that way, if there is no particular reason to restart.

Thanks.

**Comment by reedy** [comment]
https://adblockplus.org/blog/how-many-hacks-does-it-take-to-make-your-extension-install-without-a-restart

https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions


The question is whether it's worth the time/effort to do so

**Comment by diracdeltas** [comment]
I have a branch somewhere that started converting HTTPS Everywhere to a restartless extension. At the time the process wasn't well-documented, but perhaps it's changed. I think it's this branch: https://github.com/diracdeltas/https-everywhere/tree/fennec

Things weren't working IIRC but see src/bootstrap.js for a starting point if you're implementing this.

**Comment by diracdeltas** [comment]
I can't unassign myself in Github anymore, so I'll just note that this task is free for anyone to take on.

**Comment by isonmad** [comment]
I mean, for the record, the exact same guy also wrote that all those showstoppers are gone now and haven't applied since Firefox 8. https://adblockplus.org/blog/why-you-should-make-your-next-add-on-restartless

But this is gonna be fixed anyway with the planned switch to WebExtensions for firefox right? https://github.com/EFForg/https-everywhere/issues/7389#issuecomment-255483554

**Comment by gloomy-ghost** [comment]
We will move to WebExtension which is restartless as described in #9958, and I don't think there will be further developments for the XPCOM version as it's already deprecated.
