### ISSUE TITLE
Add openstreetmap.org

### ISSUE THREAD

**Issue by piratenpanda** [EFForg/https-everywhere#1133]
openstreetmap.org also offers https

**Comment by reedy** [comment]
There is a ruleset for openstreetmap.org in master - https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/OpenStreetMap.xml

It is there in 3.5/4.0/stable too, but doesn't cater for www.openstreetmap.org

Having said that, it's explicitly disabled by default due to https://trac.torproject.org/projects/tor/ticket/8841
