### ISSUE TITLE
Suggestion: move translations into this repo

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#11677]
It would make it less error-prone than using an external submodule and would make it easier to work on the translations. Also it will make HTTPS Everywhere less dependent on Tor Project.

**Comment by koops76** [comment]
ping @Hainish

**Comment by koops76** [comment]
@j0WI @cschanaj Can you explain a reason for thumbs down?

**Comment by cschanaj** [comment]
@koops76 I don't agree this is a good idea because we have a fairly small number of reviewers here. Our reviewers might have difficulties to approve translations of languages they do not comprehend of themselves, translation PRs are blocked as a result. 

Besides, what do you mean by being _less error-prone_? If you are talking about the translation accuracy/ quality, I see little difference caused due to the location where the source code are hosted.

See also @Hainish 's comment in https://github.com/EFForg/https-everywhere/pull/9670#issuecomment-309614152

**Comment by koops76** [comment]
@cschanaj Submodule sometimes causes errors when it is updated when it's not supposed to.

**Comment by Hainish** [comment]
HTTPS Everywhere was started as a joint project between the Tor Project and EFF.  Transifex provided by Tor is a huge utility, it gets us an enormous amount of translator labor for absolutely free.
