### ISSUE TITLE
meta.statuspage.io gives untrusted certificate

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#1224]
StatusPage.io's status page is on Heroku, not their infrastructure. So connecting via TLS gives a certificate name mismatch.

This looks like just an overzealous wildcard. Easy to fix.

**Comment by strugee** [comment]
@jsha does HTTPS Everywhere not have support for excluding certain subdomains? I'm not familiar enough with the ruleset grammar to know... :/

**Comment by jsha** [comment]
@strugee: Yes, you can use the exclusion tag for that, and I'd encourage you to do that to fix the rule. I tend to disable broken rules rather than trying to fix them. It can take up huge amounts of my time trying to fix rules, and I'm the only official maintainer on HTTPS Everywhere. Our awesome community members sometimes fix up and re-enable the rules.

**Comment by strugee** [comment]
@jsha you might consider having a GitHub label for that. Then interested community members could more easily find problems like this :)
