### ISSUE TITLE
[Ruleset] Add one for "digitick.com"

### ISSUE THREAD

**Issue by pihug12** [EFForg/https-everywhere#12409]
I'm not familiar with the ruleset system.

Can you, please, add one for http://www.digitick.com/ (a French website e-Ticket store)?

Thanks!

**Comment by christianheinrichs** [comment]
@pihug12 Thank you for opening this issue.

As soon as the corresponding pull request is merged, Digitick should be added. Note however that the hotline.digitick.com subdomain (which you can reach by clicking on the _**Support**_  link on the top right) cannot be secured since it has an invalid certificate, therefore it was commented out.
