### ISSUE TITLE
pgp.mit.edu isn't redirected anymore

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#12640]
Until recently pgp.mit.edu got redirected by https-everywhere.
This is no longer the case.

https://pgp.mit.edu works well so this redirect should be enabled again.

**Comment by bardiharborow** [comment]
[The MIT ruleset](https://github.com/EFForg/https-everywhere/blob/7e4193f45aeb4633e79cdfa56abe1178bf746b39/src/chrome/content/rules/MIT.xml) is currently disabled due to errors.

**Comment by J0WI** [comment]
closed by #12652

**Comment by KommX** [comment]
But unfortunately pgp.mit.edu still doesn't get redirected.

**Comment by bardiharborow** [comment]
@J0WI

**Comment by J0WI** [comment]
This should be _really_ fixed now.

To transparently summarize what happened (cc @jeremyn):
* #12652 fixed the ruleset, but did not re-enable it.
* #12002 reenabled the rule together with some minor enhancements, but had a failing test.
* Sadly this repo has been deleted, so I merged this into a new branch to fix the outstanding issue.
* Since the remaining issue was only a [one character change](https://github.com/EFForg/https-everywhere/pull/14169/commits/6ab78e994a94b928b883328612217a9d542c5f82) I merged #14169 myself

So any further contributions as already discussed in #12002 are welcome (again).
