### ISSUE TITLE
Add Swedish translation

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#12902]
Type: other

I have translated HTTPSE on https://www.transifex.com/otf/torproject/
It is the Swedish translation. Please merge my translation, thank you.

**Comment by J0WI** [comment]
Thanks!
This should be added automatically during release (see #12827).

**Comment by jony0008** [comment]
@J0WI Why was only the chrome addon and not the FF addon updated with the translation?

**Comment by J0WI** [comment]
Uhm, no idea what went wrong. Let's ask @Hainish

**Comment by Hainish** [comment]
Closing as a subset of https://github.com/EFForg/https-everywhere/issues/12009

**Comment by Hainish** [comment]
More specifically, there is an underlying problem.  The Swedish translation, although it's been made, hasn't been picked up because there is a mismatch between the transifex locale and the locale that most Swedish speakers have set.  The `sv` locale has been blanked out.  This is all beign tracked in #12009

**Comment by jony0008** [comment]
@Hainish Any solution yet?
