### ISSUE TITLE
Consider forcing first-party-only cookies

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#1301]
Chrome is testing out *first* party cookies. When this feature becomes API-available, we should consider applying it to our cookie rules:

https://code.google.com/p/chromium/issues/detail?id=459154

**Comment by jsha** [comment]
I think the first party cookie feature is more oriented towards sites that want to mitigate CSRF by asking the browser not to send cookies in certain situations.

I could see how setting the first party bit on all cookies could improve privacy, but I think that winds up being equivalent to turning on 'block third party cookies.' Also, Privacy Badger is probably a better place for such anti-tracking measures.

**Comment by semenko** [comment]
Hm, I think this is less privacy focused, and more security focused -- to me it feels on-par with the current "Set HTTPS-only" flag feature of secure cookies that we're using.

There's a bit more I need to think about here -- mostly @mikewest's comments in: https://plus.google.com/+FrancoisBeaufort/posts/PjiVdXeWqU4

**Comment by mikewest** [comment]
Right. Setting 'first-party-only' on all cookies is equivalent to turning on third-party cookie blocking (except insofar as Chrome's third-party cookie blocking blocks "cookies and site data" (e.g. Local storage, etc)). I believe you can do that, if you like, via the content settings API.

**Comment by jsha** [comment]
Interesting. @mikewest, I had definitely assumed this was mainly a CSRF thing until I read your comment. The data leakage aspect is interesting because HTTPS Everywhere's threat model involves operating in a hostile network, and if you load any HTTP page, that page could potentially use a data leakage attack against pages that HTTPS Everywhere has secured.

On the other hand, the interactions that break when first-party is enforced will be very hard to find:
  - Typically they will involve some subdomain posting data to a different domain.
  - They will almost certainly require a logged-in user account, which we don't have for most sites in HTTPS Everywhere.
   - They will almost certainly require user interaction, versus just loading a page.

I think rather than adding a new potential source of breakage, we should perhaps just encourage HTTPS Everywhere users to disable third-party cookies. We could make it an easy checkbox in the dropdown.

**Comment by jsha** [comment]
Interesting. @mikewest, I had definitely assumed this was mainly a CSRF thing until I read your comment. The data leakage aspect is interesting because HTTPS Everywhere's threat model involves operating in a hostile network, and if you load any HTTP page, that page could potentially use a data leakage attack against pages that HTTPS Everywhere has secured.

On the other hand, the interactions that break when first-party is enforced will be very hard to find:
  - Typically they will involve some subdomain posting data to a different domain.
  - They will almost certainly require a logged-in user account, which we don't have for most sites in HTTPS Everywhere.
   - They will almost certainly require user interaction, versus just loading a page.

I think rather than adding a new potential source of breakage, we should perhaps just encourage HTTPS Everywhere users to disable third-party cookies. We could make it an easy checkbox in the dropdown.
