### ISSUE TITLE
Ruleset creates bugs with Humanitarian OpenStreetMap issue tracker (and its cousins)

### ISSUE THREAD

**Issue by gappleto97** [EFForg/https-everywhere#13211]
Type: ruleset issue

Domain: tasks.hotosm.org, tasks.openstreetmap.us, and all other websites [listed here](http://wiki.openstreetmap.org/wiki/OSM_Tasking_Manager#Operational_installations_of_the_Tasking_Manager)

When using these websites, it will open part of OpenStreetMap in the ID editor. This will show a bounding box fed by these domains. Unfortunately, pretty much none of them support HTTPS. Without a rule change, that means the bounding box never shows, and the task manager is much much more difficult to use.

hotosm/osm-tasking-manager2#988

**Comment by Bisaloo** [comment]
I don't understand. I don't seem to have any issue when visiting those domains and clicking on a task.

Could you provide a specific URL where you have issues? 

Also, we don't have a rule for domains like `hotosm.org` and they load normally over `http` for me.

I am interested in fixing this issue but I will need additional information.

**Comment by Bisaloo** [comment]
Okay, I get it:

1. Visit http://tasks.hotosm.org/
2. Log in
3. Click on an ongoing task
4. Go to `contribute` tab
5. Click on `Start mapping`
6. Click on `Edit with iD editor`
7. You will be taken to https://www.openstreetmap.org/edit?editor=id#$COORDINATES. On this URL, you have MCB.

**Comment by gappleto97** [comment]
Yup. And with HTTPS Everywhere turned off you see a pink square. With it on you do not see this, and it reports that it blocked mixed content.

**Comment by Bisaloo** [comment]
I don't think there is much we can do. Disabling the whole openstreetmap ruleset is likely not option.

I will take some time to think about it.

Note for my future self or anyone wanting to chime in: securecookies on `openstreetmap.org` are an issue as well because you need to be logged in to edit.

**Comment by gappleto97** [comment]
Is it not possible to make a rule to ignore https on *.hotosm.org, for instance?

**Comment by Bisaloo** [comment]
> Is it not possible to make a rule to ignore https on *.hotosm.org, for instance?

Yes, it would be possible but this is not the issue here. 

HTTPS-Everywhere doesn't force secure connections to `hotosm.org`. It forces `https` connections to `openstreetmap.org` which loads resources from `http://tasks.hotosm.org`, hence the mixed content blocking.

Generally speaking, there is two possible fixes to this kind of issues:
- stop loading `openstreetmap.org` over `https`. But if we remove that rule, we will leave **all** openstreetmap users at risk, even those that don't care about this specific issue. This would be really bad.
- load `tasks.hotosm.org` over `https`. There is usually no downsides to this option (but I know openstreetmap is a complex project and I understand such changes may come with possible issues here) but it has to be done on openstreetmap side, not ours.

**Comment by gappleto97** [comment]
Gah. I've gotten no movement trying to get them to act. I was hoping you'd be able to do a workaround. Oh well

**Comment by Bisaloo** [comment]
You can always disable the `OpenStreetMap.org` ruleset in your browser. Go to https://openstreetmap.org, open HTTPS-Everywhere dropdown menu and click on the ruleset. It will be unchecked after that.

You will lose the benefits of the https connection on openstreetmap but it may be a tradeoff you are willing to make yourself.

**Comment by gappleto97** [comment]
My solution for the moment is to disable when I'm using the task manager.

**Comment by Bisaloo** [comment]
This issue should now be fixed for `tasks.hotosm.org` (which now redirects to `https`) but it's still an issue for [other websites using the tasking manager](http://wiki.openstreetmap.org/wiki/OSM_Tasking_Manager#Operational_installations_of_the_Tasking_Manager) as far as I can tell.

**Comment by wonderchook** [comment]
So the issue would be with every single configuration with the tool? Other than updating their documentation to inform people, is there anything that can be done to fix this? 

(I designed the very first version of this tool, so I might have more luck inquiring)

**Comment by Bisaloo** [comment]
If I understand correct, this has been fixed upstream in https://github.com/hotosm/tasking-manager/pull/907/.

Downstream projects such as teachOSM, OSMCanada, etc. now need to update their version of the tasking manager.
