### ISSUE TITLE
Disable numbers from toolbar icon

### ISSUE THREAD

**Issue by xchannels** [EFForg/https-everywhere#13298]
As I have OCD, I see it annoying. I want to disable numbers from toolbar icon of HTTPS everywhere and i want to keep everything clear from those annoying things.
Thank you.

![image](https://user-images.githubusercontent.com/20967118/31887314-1a792f8a-b7f8-11e7-89e5-0d148d814943.png)

**Comment by jeremyn** [comment]
In Firefox:

about:addons > Extensions > HTTPS Everywhere > uncheck "Show Counter"

It's similar in Chrome:

chrome://extensions/ > HTTPS Everywhere > Options > uncheck "Show Counter".

Note that due to a bug in the Firefox extension, private browsing mode/clearing your Firefox data will reset your HTTPS Everywhere settings, including the "Show Counter" setting (see issue https://github.com/EFForg/https-everywhere/issues/12730).

**Comment by kbpsmp3** [comment]
I unchecked "Show Counter" and it helped.
Thanks fro your help
