### ISSUE TITLE
Update URI.js

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#1335]
We haven't updated this in a while -- and a bunch of performance bugs are fixed.

@jsha could you update this? (As it's a big, not-so-easily diffable blob.)

Via: https://github.com/medialize/URI.js

We want: https://github.com/medialize/URI.js/blob/gh-pages/src/URI.min.js

**Comment by semenko** [comment]
Hm, alternatively we could drop URI.js and switch to IDL attributes:
https://jsperf.com/idl-attributes-vs-uri-js

Let me ponder.

**Comment by jsha** [comment]
IDL attributes sound good too. I will wait for your conclusions.

If we stick with URI.js I'd like to commit the unminified version so that future diffs are meaningfully auditable. We could either minify it ourselves during the release process or decide that the infrequent downloading of the extension means we can simply not minify.

**Comment by semenko** [comment]
I'm thinking IDL, since that's standard blazing-fast code we can forget about updating / auditing, etc. PR inbound in a bit here.
