### ISSUE TITLE
Include "Add rule for this site" option on http webpages.

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13592]
Type: feature request

Right now to i have to manually type `https://` in browser to load http website to https and then add a rule, which is extra step that differentiates it from another extension "Smart Https" where you can do it in one click. Even if it's going to be two clicks in https-everywhere, i can back switch back to it.

**Comment by ihave100openPRs** [comment]
This is already implemented in the "Block all unencrypted requests" option where it forces HTTPS with HTTP connections.

**Comment by ficofabrid** [comment]
@ihave100openPRs It's breaks websites.

**Comment by cschanaj** [comment]
I agree that we should include "Add a rule for this site" feature for HTTP sites as well, as this will provide more consistent behavior. It is also more convenient for advanced users. 

@Hainish @cowlicks any reason behind the current behavior? See #13633

**Comment by Bisaloo** [comment]
I'm not sure I support this. It greatly increases the risk of users adding rules for websites that don't actually support HTTPS.

**Comment by cschanaj** [comment]
> I'm not sure I support this. It greatly increases the risk of users adding rules for websites that don't actually support HTTPS.

If the users add a trivial rule, they should be able to remove it after finding the site does not support HTTPS. 

However, I agree it could be problematic if a user add a complex rule (rewriting domains, etc.); since when the rule turns out problematics, it is not possible remove the rule from the extension UI.

For example, when adding the following custom rule, it will turn out problematic and difficult to remove the custom rule from the extension UI.
```xml
<rule from="^http://example\.com/" to="https://example.co.uk/" />
```

Maybe we should fix this before resolving this issue :smile:

**Comment by Bisaloo** [comment]
https://github.com/EFForg/https-everywhere/issues/1779

**Comment by Hainish** [comment]
I'm going to close this due to inactivity for now, if this is a truly desired feature we can reconsider in another issue.
