### ISSUE TITLE
Google Chrome HTTPS Everywhere 2015.3.31 http://folding.stanford.edu/nacl/ No Longer Works

### ISSUE THREAD

**Issue by hc970** [EFForg/https-everywhere#1366]
Hello,

HTTPS Everywhere version 2015.3.31 for Google Chrome on Windows 8.1 breaks the Stanford NaCl Folding@Home client from working.

Accessing the following URL http://folding.stanford.edu/nacl/ with the default settings for HTTPS Everywhere stops the folding client from working. Turning off (un-ticking/un-checking) the rule Stanford.edu (partial) (after left clicking on the HTTPS Everywhere icon) resolves the issue.

Thank you.

![image](https://cloud.githubusercontent.com/assets/11799180/6996519/58975042-db84-11e4-8ee1-195013f2c641.png)

**Comment by reedy** [comment]
I guess the simplest fix here is to just add the nacl url as an exclusion

**Comment by hc970** [comment]
Hi Sam,

Sounds good, it's great that it should be such a simple fix. Thanks.

**Comment by KommX** [comment]
I tried to just add
<exclusion pattern="^http://folding\.stanford\.edu/nacl/" />
to the rule, but that doesn't do the trick.

At least when I try to ./run-chromium.sh I still get errors when I try to use the folding client.

Did I make an obvious mistake or is the solution just a different one?

**Comment by terrorist96** [comment]
I can confirm that the stanford rule is still breaking the NaCl client.

**Comment by terrorist96** [comment]
Still broken in 2016.6.9.

**Comment by jeremyn** [comment]
This should not be a problem now because the folding NaCl URL is http://fahwebx.stanford.edu/nacl/ instead of https://folding.stanford.edu/nacl/ . The `folding` HTTPS URL redirects successfully to the `fahwebx` URL. `fahwebx` is not in the current [`Stanford-University-xml`](https://github.com/EFForg/https-everywhere/blob/9bf49cbeb4696cdea76df23f685da1d11031f693/src/chrome/content/rules/Stanford-University.xml) file, and https://fahwebx.stanford.edu/ gets a `Connection refused` response so it's unlikely to be added in the future.

Also the entire `Stanford-University-xml` ruleset is disabled now anyway.
