### ISSUE TITLE
Add release notes to EFF hosted version

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#13716]
Type: feature request

similar issue in privacy badger's repo: https://github.com/EFForg/privacybadger/issues/1749

**Comment by jeremyn** [comment]
I don't see the "Show/Hide Release Notes" button with the AMO version of Privacy Badger as described in https://github.com/EFForg/privacybadger/issues/1749#issuecomment-343322954. Anyway I think a better way would be just to add a link in the UI, below "About HTTPS Everywhere" maybe, for "View Release Notes" which links to https://www.eff.org/files/Changelog.txt.

But I'm not even really happy with that, because the current release notes are really minimal. If we promote the release notes then people might get annoyed to see (or miss) significant changes that aren't  listed there.

**Comment by Bisaloo** [comment]
> I don't see the "Show/Hide Release Notes" button with the AMO version of Privacy Badger as described in EFForg/privacybadger#1749 (comment).

I do. Click on the cog in `about:addons` and select `View recent updates`. (I will only work if you updated HTTPS Everywhere in the last couple of days though.)

**Comment by jeremyn** [comment]
Do you mean "if you updated Privacy Badger in the last couple of days"? Anyway nothing shows up for either Privacy Badger or HTTPS Everywhere when I click "View Recent Updates", I guess because I haven't updated recently and there are no pending updates.

**Comment by zoracon** [comment]
Release notes available since this discussion. 

Closing due to new changes since this conversation took place
