### ISSUE TITLE
Breaks http://campus.codeschool.com/

### ISSUE THREAD

**Issue by EvsWorld** [EFForg/https-everywhere#13885]
Type: other

Domain:http://campus.codeschool.com/

**Comment by jeremyn** [comment]
@dromomaniac I don't see anything broken after some casual browsing of this site. What is broken for you, exactly?

**Comment by dromomaniac** [comment]
I got it working normally after disabling some option on the https anywhere
chrome extension. It only was only a problem when you’re doing a course.
Also have a paid account fyi.

-- 
Evan


Enviado desde mi iPhone


----------
On Thu, Dec 7, 2017 at 6:20 PM, Jeremy Nation <notifications@github.com>
wrote:

@dromomaniac <https://github.com/dromomaniac> I don't see anything broken
after some casual browsing of this site. What is broken for you, exactly?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EFForg/https-everywhere/issues/13885#issuecomment-350035606>,
or mute the thread

**Comment by pipboy96** [comment]
Website in question no longer exists and is merged with Pluralsight.
