### ISSUE TITLE
Declare when HTTPS Everywhere broke a site

### ISSUE THREAD

**Issue by paulakreuzer** [EFForg/https-everywhere#13913]
Type: feature request

Backgroud:
I'm using a long list of privacy enhancing browser addons (almost congruent with [Prism Break's list](https://prism-break.org/en/all/#web-browser-addons)), set up Firefox's security settings pretty strict and additionally blocked some sites via hosts file - so there are many reasons why a particular site might not work on my browser. Unfortunately the various error messages and broken connection pages are not very helpful to determine which addon or setting broke a site.

Feature Request:
I think it would be really helpful if HTTPS Everywhere indicated when it is responsible for a broken connection. Like with a little 🚫 sign on the addon symbol.

What this means for reporting ruleset issues:
There are some sites that don't work with my current setup. To find out which site is broken because of HTTPS Everywhere I downloaded the FF Dev Edition, set it up exactly the same way as standard FF (settings +addons), except I didn't install HTTPS Everywhere there.
I don't think this is very practical and I think this will keep me and others from reporting issues.

Additional Question:
Is it really HTTPS Everywhere's "fault" if it breaks a site or shouldn't I rather contact the owner of the site and ask them to fix their site security instead of (or in addition to) reporting the issue here?

**Comment by jeremyn** [comment]
Issue https://github.com/EFForg/https-everywhere/issues/8239 discusses some of the difficulties with saying that some particular failure is HTTPS Everywhere's "fault". You might find that discussion interesting.

**Comment by jeremyn** [comment]
To answer your "additional question": it's theoretically possible for HTTPS Everywhere to break a site that is working perfectly with HTTPS, because HTTPS Everywhere can rewrite a URL to a completely different URL. In practice we try not to break important site functionality, so things like broken images or video are valid issues for us.

Of course you are welcome to contact a site's administrator if you want but keep in mind that sometimes breakage happens, especially on complex sites, because of stuff that the tech administrator who answers your email can't control. For example maybe a video player that is breaking was chosen by a business team years ago and the person you're talking to can't change it.

Also, please don't ask administrators to change their site specifically to work with HTTPS Everywhere. It doesn't look good for us. Instead, please submit an issue or pull request here.

**Comment by jeremyn** [comment]
@paulakreuzer I'd like to close this issue because it's unclear what it means to say that "HTTPS Everywhere broke a site", for reasons such as those in issue https://github.com/EFForg/https-everywhere/issues/8239 that I linked before. Is it okay with you if we close this issue?
