### ISSUE TITLE
Wall Street Journal Comments Not Loading

### ISSUE THREAD

**Issue by justlurking** [EFForg/https-everywhere#1417]
Tested on Chrome (stable branch), on Mac OS 10.10.2.  WSJ comments do not load at all and there is no error message.  Scrolling to the bottom of an article (or clicking on the comments link to jump down to the comments at the bottom of the article) reveals blank white space where the comments usually appear.

Disabling the extension or white listing "Livefyre (partial)" results in the comments loading.

**Comment by finaljason** [comment]
The rule causing this seems to be:

<rule from="^http://(?:zor\.fyre\.co|(?:www\.|zor\.)?livefyre\.com)/"
		to="https://d584h2bjreb1u.cloudfront.net/" />

The server which the URL is rewritten to returns a 404 error and i cant figure out if or how the directory structure was changed. Trying to access https://zor.fyre.co (matching the above pattern) directly leads to an error because ssl domain mismatch (its an Akamai cert at a248.e.akamai.net).

Possibly it can be rewritten to access the cdn directly, but i dont know how or if this even is something to aim for.

**Comment by semenko** [comment]
WSJ comments are loading for me with the latest version.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
