### ISSUE TITLE
Rewriting of URLs with fixed port number causes trouble on sqlite.org

### ISSUE THREAD

**Issue by hannob** [EFForg/https-everywhere#1461]
Have a look at this page:
https://www.sqlite.org/src/wiki?name=Bug+Reports

There is a link to:
http://sqlite.org:8080/cgi-bin/mailman/listinfo/sqlite-users

As HTTS everywhere has sqlite.org in its database it will try to rewrite the URL. However this URL has a port number - and of course there can't be an HTTPS and an HTTP server on the same port at the same time. So the rewriting will cause the request to fail.

HTTPS Everywhere probably should not rewrite URLs with a port number (except when it knows that there is both an http and an https server on uncommon ports - but in that case it'd need to know which port the https one is, so this can only be whitelistet).

**Comment by reedy** [comment]
I wonder if we can "easily" fix this by just explicitly excluding the sqlite mailman setup in the sqlite ruleset?

I know this probably needs looking at in a larger sense, but this improves the situation to begin with

**Comment by jsha** [comment]
Yes, let's add a mailman exclusion for now.

This is a problem introduced by my recent encouragement of the http->https simple rules. Previously we would have had:

```
<rule from="^http://sqlite.org/" to="https://sqlite.org/" />
```

Since the slash was explicitly part of the match it wouldn't have matched anything with a port number. I think the right fix is for matching to punt on any URL whose port is not 80 or 443.
