### ISSUE TITLE
New ruleset request: webmail.breathe.com

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#14711]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: new ruleset

Domain: webmail.breathe.com

I have received feedback requesting https://webmail.breathe.com/ be added to our list of rulesets.

**Comment by Bisaloo** [comment]
We don't usually add coverage for subdomains that require a login because it is hard to predict the effect of the ruleset. Maybe there is MCB or a redirect to HTTP behind the login page and we have no way to test this.

But since this is a specific request, I guess we can make an exception (#14712).
