### ISSUE TITLE
Doesn't work on my site http://www.billdietrich.me/

### ISSUE THREAD

**Issue by BillDietrich** [EFForg/https-everywhere#14856]
Type: ruleset issue

Domain: billdietrich.me

It's my personal site, just put it on a new host (Arch Hosting).  Both HTTP and HTTPS work fine, but HTTPS Everywhere on Firefox does not automatically switch from HTTP to HTTPS.  HTTPS Everywhere on this browser works fine on other sites for me.  Hope I haven't done something stupid and wasted your time.  Thanks.

**Comment by Bisaloo** [comment]
Hi @BillDietrich,

HTTPS Everywhere does not try HTTPS for every single but instead rely on a manually curated set of rules. See [this FAQ entry](https://www.eff.org/https-everywhere/faq#why-use-a-whitelist-of-sites-that-support-https-why-cant-you-try-to-use-https-for-every-last-site-and-only-fall-back-to-http-if-it-isnt-available) for the rationale behind this approach.

You are not redirected to HTTPS for your own site simply because no one has written a rule for it yet. You are welcome to add a rule yourself by following the instructions in our [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md).

Another approach would be to add you site to the [HSTS preload list](https://hstspreload.org/). This is even better than adding a rule in HTTPS Everywhere because you will force HTTPS (and thus protect) *all* visitors and not just HTTPS Everywhere users.

I hope that makes sense!

**Comment by BillDietrich** [comment]
Okay, thanks very much.  I'm just going to put a redirect in the .htaccess for the site.
