### ISSUE TITLE
Warn users about insecure (HTTP) downloads

### ISSUE THREAD

**Issue by sydneyli** [EFForg/https-everywhere#14895]
Type: feature request

In recent news, ISPs actually do mess with [HTTP downloads](https://citizenlab.ca/2018/03/bad-traffic-sandvines-packetlogic-devices-deploy-government-spyware-turkey-syria/). Insecure downloads being hosted on HTTPS sites are [particularly misleading](https://citizenlab.ca/wp-content/uploads/2018/03/Bad-Traffic-Image-12.png). Could HTTPS Everywhere warn users when downloads are served over HTTP? Could be by looking for `http` links associated with the `download` attribute and displaying an open red lock, or something to that effect.

**Comment by jeremyn** [comment]
FYI, a related situation, where a user might think they are getting encrypted content but actually isn't, is mixed content, described at https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox .

A problem with warning users here though is, what do we want the user to do about it? If we tell them something is wrong without telling them how to fix it, then we've just worried the user for no reason.

We also don't want users to think that they are safe just because the download happened over HTTPS. Users downloading sensitive files, using HTTPS or not, should make sure their file is correct using some out-of-band means, such as downloading a signature file that has been created with a GPG key they can get from some other source, or using Windows [digital signatures](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/digital-signatures) that rely on certificate authories provided securely by Windows itself.

**Comment by l0b0** [comment]
I've written a simple [Firefox plugin](https://addons.mozilla.org/en-US/firefox/addon/insecure-links-highlighter/) to do this.

**Comment by zoracon** [comment]
Related: https://security.googleblog.com/2020/02/protecting-users-from-insecure_6.html

Not determining this as not useful, but the browsers are taking a good lead on this and actually getting to the point providing enough guidance naturally without our need to create this feature. Will leave this open for now to see what happens early next years with the browsers.
