### ISSUE TITLE
Rule for *.cornell.edu

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#15054]
Type: new ruleset
Domain: *.cornell.edu

**Comment by galenide** [comment]
As of now, it appears that HTTPS Everywhere has a [ruleset for Cornell](https://www.eff.org/https-everywhere/atlas/domains/cornell.edu.html) in the stable and release branches of the extension. The information in the rulesets indicates that they are disabled because some of the domains gave errors when a testing process was performed. (It is possible that some of the listed errors have been resolved since then.)

**Comment by KOLANICH** [comment]
Thank you for the info.
