### ISSUE TITLE
intermittent selenium test failure

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#15073]
Type: other

https://travis-ci.org/EFForg/https-everywhere/jobs/360945791
https://travis-ci.org/EFForg/https-everywhere/jobs/360947600
https://travis-ci.org/EFForg/https-everywhere/jobs/361786914

**Comment by cschanaj** [comment]
I am also seeing this happening in https://travis-ci.org/EFForg/https-everywhere/builds/362107337

**Comment by Hainish** [comment]
I did notice this yesterday.  I think this is due to an increase in extension load-time at startup for Chrome.  I'll investigate.

**Comment by Hainish** [comment]
This seems to be due to the out-of-band rulesets' application of rules halting the extension process in chrome for a second or two, interfering with the ability for selenium to click UX elements.  You can mimic this behavior by throttling your connection to about 125k/s (on my machine I insert an `iptables` rule as such, but this can be achieved via other throttling applications):

    sudo iptables -I INPUT 3 -m conntrack --ctstate RELATED,ESTABLISHED -m limit --limit 80/sec -j ACCEPT

This allows me to open the extension debugging panel to monitor the steps of the extension update.  Then I open the options UX and click on the "Show Counter" button.  Sure enough, there is some interference.

I think we should just disable ruleset updates for the Selenium tests for the time being.

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/pull/15075 passed on first run.  That should resolve this issue.

**Comment by gloomy-ghost** [comment]
https://travis-ci.org/EFForg/https-everywhere/jobs/367856503
https://travis-ci.org/EFForg/https-everywhere/jobs/367858826
https://travis-ci.org/EFForg/https-everywhere/jobs/367858827

It looks like we have a problem again

**Comment by Hainish** [comment]
Looks like all three of these were due to a 404 response in the chromedriver URL.  I've restarted the jobs.

**Comment by Hainish** [comment]
Looks like it's passing again!
