### ISSUE TITLE
Make a ruleset for example.org, example.net and example.com

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#15099]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: new ruleset

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: example.net
Domain: example.com
Domain: example.org

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

(What if someone wants to use them with HTTP? Then they just have to disable their ruleset in HTTPS Everywhere.)

**Comment by httpsverywehreerio** [comment]
https://github.com/EFForg/https-everywhere/pull/15105 https://github.com/EFForg/https-everywhere/pull/15104 https://github.com/EFForg/https-everywhere/pull/15103 Never thought it would be this easy :smile:

**Comment by Hainish** [comment]
@J0WI I think it would be good to provide some well-known HTTP endpoint for people who are trying to connect behind a captive portal.  Often, people use these example domains for that purpose.  We should probably give some alternative that doesn't involve completely disabling HTTPS Everywhere.

**Comment by J0WI** [comment]
Both, Chromium and Firefox have internal captive portal checks.
IMHO captive portals are harmful and we should not "support" their behavior.

**Comment by Hainish** [comment]
In fact, since https://tools.ietf.org/html/rfc2606 specifies that `example.[com|net|org]` is an IANA reserved domain and no sensitive information is transferred, we should probably exclude them for the purposes of captive portals.  There is the danger of drive-by downloads on HTTP sites, but if that's what your threat model is you should probably be using the addon in HTTP nowhere mode anyway.  I've removed these in https://github.com/EFForg/https-everywhere/commit/cef22501ffc5a67b52f4b327717ea8f433a7f5cd

**Comment by Hainish** [comment]
@J0WI I haven't seen this functionality in Firefox or Chromium on Linux.  I have seen it as an Android OS-level feature, which has access to the network management layer.

Regardless of whether we support captive portals existing ideally, they do exist in reality.  We shouldn't force users to disable HTTPS Everywhere (or know about an HTTP-only site that isn't a standard) in order to allow people to connect in situations where captive portals are in place.

**Comment by Hainish** [comment]
Removing these rulesets may not be optimal - I removed them in order to go forward with a release, but at the very least they should be disabled by default. Perhaps we can add a comment mentioning captive portals for the reason that it is disabled. This way, users will have to actively enable it, at which point they will see the 'captive portal' comment. Hopefully, this will be triggered in their memory if they do at some later point have to go through the captive portal workflow.
