### ISSUE TITLE
How to anonymously submit rulesets?

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#15182]
Type: other

I know there's email but the last rulesets that were submitted there were never reviewed. Also I'm not confident that Github is privacy respecting and can't link all of my accounts, and always using a throwaway-then-deleted account takes time and many times Github locks the account and I have to re-login and send an email to the staff asking to activate my account. Also another disadvantage is that I can't get back at the maintainers' reviews to fix them.

**Comment by YegorIevlev** [comment]
@ghost You can use a throwaway account to submit a pull request but you shouldn't delete it before your PR is merged or closed. PRs from deleted accounts are closed.

**Comment by jeremyn** [comment]
PRs from @ghost [are discouraged](https://github.com/EFForg/https-everywhere/blob/3a6359bf32100e4493f5de4f380cb165413a1af6/CONTRIBUTING.md#pull-requests-from-deleted-accounts) in `CONTRIBUTING.md`, along the lines of what @YegorIevlev wrote.

@Hainish Can you please comment here on the original question, "How to anonymously submit rulesets?"

**Comment by Hainish** [comment]
@ghost `github.com` is accessible over the Tor Browser, so you can use the Web UI anonymously.  The command line `git` anonymously can be a little more tricky.  I'd suggest creating a new VM which you work from, and configure it to ensure all traffic in that VM goes over Tor by default.  There are some distributions that are specifically made for this: Whonix and Tails, for instance.  You can install a persistent version of Tails (rather than booting fresh from a Live distribution every time) or install [Whonix in Virtualbox](https://www.whonix.org/wiki/VirtualBox) and work from that.  Other distributions installed on bare metal (like Qubes, for instance) will have Whonix pre-installed.
Also, the Qubes distribution comes with Whonix installed in it.
