### ISSUE TITLE
Reimplement SSL Observatory for Firefox

### ISSUE THREAD

**Issue by ansell** [EFForg/https-everywhere#16025]
Type: feature request

The SSL Observatory can be reimplemented for Firefox-62+ WebExtensions using the API created in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1322748

(I realise this may not happen soon since the Firefox-60 ESR which doesn't have this feature is likely to be supported for a while, but opening this to keep track of it)

**Comment by Hainish** [comment]
It seems that Firefox has decided to go with entirely their own API for TLS introspection instead of adopting the one we are working with Chromium devs on developing, and is slowly being implemented in Chrome.

I'd like to make sure the API we pick will be standardized in all the browsers we support. This divergence is a little troublesome for our own implementation needs, and I'd like to not develop two separate code paths for Firefox and Chrome. I think it's worth waiting until the browsers figure this out.

**Comment by pipboy96** [comment]
@Hainish @zoracon Am I welcome to start implementing this with Firefox's current API?

**Comment by zoracon** [comment]
> @Hainish @zoracon Am I welcome to start implementing this with Firefox's current API?

I'll confirm if the API issues were sorted out and get back to you

**Comment by Giltyhub** [comment]
@zoracon *ping*

**Comment by pipboy96** [comment]
@Giltyhub re. what?

**Comment by Giltyhub** [comment]
@pipboy96 re your request above to him. Did you get an answer? if so sorry for the disturbance

**Comment by pipboy96** [comment]
@Giltyhub No.

**Comment by pipboy96** [comment]
This seems unlikely to happen due to lack of requisite APIs in Chrome and EFF team responsible for SSL Observatory moving to work on Let's Encrypt.

**Comment by JamesTheAwesomeDude** [comment]
I know this is a weird question, but- is the SSL Observatory server still running?

[`webRequest.getSecurityInfo()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/getSecurityInfo) now includes raw DER passthrough support, if called with `{"rawDER": true}`.

**Comment by pipboy96** [comment]
@JamesTheAwesomeDude This API is Firefox-only.
