### ISSUE TITLE
New "HTTPS unavailable" interstitial page misses some cases

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#16418]
Type: code issue

I've got the latest HTTPS Everywhere, and tested http://http.badssl.com/ with "Block All HTTP Requests" enabled; the interstitial works great!

However, when I visit http://brokenballots.com, I get the browser's "Connection timed out" error.
Disabling "Block all HTTP Requests" allows me to visit the site (which is a redirect).

Also, visiting http://timbergroves.com/bb/ gives ERR_SSL_PROTOCOL_ERROR instead of the interstitial.

**Comment by bcyphers** [comment]
Related to #16394?

**Comment by cschanaj** [comment]
AFAIK, this is not related to #16394. These errors happen when the requests are made and should be handled in `onErrorOccurred(details)`.

https://github.com/EFForg/https-everywhere/blob/ca0db7bd0b975b0d7f1933508cbb85ea02fcf408/chromium/background-scripts/background.js#L586-L590

I tried to fix this with `chrome.tab.update` to force redirect a tab to the interstitial page, but it could not distinguish errors which are not caused by HTTPSE, e.g. `Could not resolve host`. So I guess a more sophisticated mechanism is needed to fix this.

**Comment by bcyphers** [comment]
Yeah, this is tricky. It'll be hard to know whether any given error was the result of HTTPS Everywhere's rewrite instead of a regular host problem. Should we try listing out the errors that are probably a result of HTTPSE?

**Comment by cschanaj** [comment]
> string. The error description. This string is an internal error string, may vary from one browser to another, and is not guaranteed to stay the same between releases.

This might require some maintenance effort, since the strings might change from time to time according to [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onErrorOccurred). However, I think this is a good workaround for SSL errors which hopefully the messages will not change frequently.

**Comment by Hainish** [comment]
In Chrome I can enumerate a class of errors that are likely due to HTTPS misconfigurations:

```js
details.error.indexOf("net::ERR_SSL_") == 0 ||                               
details.error.indexOf("net::ERR_CERT_") == 0 ||                              
details.error.indexOf("net::ERR_CONNECTION_") == 0
```

For Firefox, this is very tricky.  I received these three errors in `details.error` for three different HTTPS bad configurations:

`NS_ERROR_CONNECTION_REFUSED`
`SSL received a record that exceeded the maximum permissible length.`
`NS_ERROR_UNKNOWN_HOST`

I could enumerate these but it seems like a maintenance nightmare, especially if there is no guarantee that they'll be constant from one version to the next.

I've fixed this for Chrome, anyway: https://github.com/Hainish/https-everywhere/commit/ef50c39b1e97648cb03459e00d2919a6dfa699f2.  This limits the interstitial page to showing only when HTTP Nowhere has done an explicit redirect to HTTPS.

One solution for Firefox that seems really ugly is just ignoring the error code and if an HTTP Nowhere HTTPS redirect is issued, show the interstitial page.  Of course, this will mean that DNS resolution failures will result in the interstitial page too.  I don't think that the trade-off is worth it in this case.

**Comment by Hainish** [comment]
I've added more SSL misconfigurations to this list: https://github.com/Hainish/https-everywhere/commit/dafe0c173a5466ceefb961c06198aca794066778

Chrome makes you pause on the browser error page before redirecting you to HTTPS Everywhere's interstitial, for some reason.  Probably for security reasons.  But then when you click back, forward, or reload it shows you the HTTPS Everywhere page.

So this seems ready to go in https://github.com/Hainish/https-everywhere/tree/disable-per-site

**Comment by Hainish** [comment]
Implemented in https://github.com/EFForg/https-everywhere/pull/16546
