### ISSUE TITLE
Revisting Ruleset for AJC.com

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#16633]
Type: ruleset issue
Domain: ajc.com

Hello @afarrow. I am a new collaborator on HTTPSE team and have taken up the mission at revisiting the rulesets that have `https` to` https` redirects. I have been going through them to see what I can clean up but taking a second look at the ones that seemed to have a bit more nuance. I saw your reasoning on this pull request: https://github.com/EFForg/https-everywhere/pull/9365.

I have been doing some testing and it seems the issue with the `www` vs. non `www` urls seem to be resolved now without the assistance of this particular redirect. I am referring to this comment: https://github.com/EFForg/https-everywhere/pull/9365/files/54bed7f883c884a80c01231ca458d9eaf2e7f786#r114831588

Before I remove this line: https://github.com/afarrow/https-everywhere/blob/569628f4537a6bb5d9580eca8f0a130767e79964/src/chrome/content/rules/AJC.com.xml#L33,
I wanted to clarify with you by getting you to retest this ruleset with me to get double confirmation. (Or perhaps inform me on context I may have missed.

Thank you for contributing!

**Comment by afarrow** [comment]
Hi @zoracon,

Sorry for not getting back to you sooner. I removed the rewrite rule on line 33 and tested it in Chromium 71. Everything seems to be working fine with it removed; it looks like they've redesigned the site since I wrote that rule but I wasn't able to find any place where https was broken. I think you should be fine removing that rule. Let me know if you need help with anything else.

**Comment by zoracon** [comment]
@afarrow 
Thank you so much for testing that with me. I will move forward with removing that line in my working branch. I'll close this out now.
