### ISSUE TITLE
Add About window to Chrome

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1684]
We should add the About/Credits window to Chrome. It's nice to give people credit where credit is due :)

We also get the donate to tor/eff links etc too

Subtask of #1681

**Comment by jsha** [comment]
:+1:

**Comment by pipboy96** [comment]
I'm not sure if this is even a good idea, since donate link for Tor is probably only applicable to Tor browser, and donate to EFF link already exists. It's possible to add an additional about page to the extension, but functionally, the main window already does everything it is supposed to do, and there is already an UX rewrite underway.

**Comment by pipboy96** [comment]
With death of non-WebExtensions HTTPS Everywhere, this issue also applies to FF.
