### ISSUE TITLE
Firefox http allow once

### ISSUE THREAD

**Issue by StraggleCraft** [EFForg/https-everywhere#16998]
Type: feature request

When using "Block all unencrypted requests" and viewing a page that can only be viewed in http, it would be nice to be able to allow the http once/1hr/24h/this session only/etc vs just adding it permanently to a whitelist.

**Comment by samtherussell** [comment]
Would this be on a page basis or origin basis?

**Comment by zoracon** [comment]
> Would this be on a page basis or origin basis?

The way the feature works at the moment, it's on a origin basis

**Comment by geekley** [comment]
To me it would suffice to have something like this in the extension popup:
> Disable HTTPS enforcement on this site:
> [Permanently](#) | [Only during this session](#)

And this in the warning page:
> HTTPS Everywhere noticed you were navigating to a non-HTTPS page, and blah blah
>
> URL: http://example.com
> Disable HTTPS enforcement on this site:
> [Permanently](#) | [Only during this session](#) | [Only this time](#)

Where clicking the URL on this page would be the same as disabling the enforcement only once.

The list of domains that are disabled only for the session should also appear in the settings page, in case you want to undo the "grant" without having to close the browser window.

**Comment by zoracon** [comment]
We are currently in the process of re-designing the UX this year. Referencing #16669 to keep this issue in line with other feedback we have gotten and closing this one

**Comment by thwaller** [comment]
I wanted to add some support to this request. The reasoning I was looking for this option is that I do not like the idea of making a bunch of rules (permanent) for things I may do once or not very often. This is something that site owners should be correcting, so many times I am fine with giving a one time pass sort of thing, but not setting a rule. Many times due to this, I end up disabling EASE to solve the issue, which is not really an ideal solution.

One could also just wipe the disabled list, although there does not seem to be a way to wipe the entire list with ease. The only issue with this option is there are sometimes good reasons to include a site in that list, so a wipe also wipes those.

**Comment by Ivoz** [comment]
Although the UI redesign is pretty cool, it never actually implemented this feature. Unless you don't want to add this, I think it could be re-opened.

**Comment by pipboy96** [comment]
I want to try implementing this.

**Comment by zoracon** [comment]
@pipboy96 If you want to take this on I'd be happy to give it to you. I would very much like to grant this feature but things are slightly full with planning for Manifest V3

**Comment by zoracon** [comment]
@pipboy96 I have a PR I am putting up soon for this since I managed time to work on this during the week.

**Comment by pipboy96** [comment]
@zoracon I hope I will be able to review it and suggest any improvements.

**Comment by zoracon** [comment]
> @zoracon I hope I will be able to review it and suggest any improvements.

I will ping you for a review once it's up
