### ISSUE TITLE
Feature Requests: Proposed UX Audit

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#17068]
Type: feature request

In #16669 There are two features so far that need a functional implementation

1. Number of Sites Visited
- This should be a local set of data to the user and clearly iterated that this is not sent back to us
- Overall this gives the user a sense of the number of sites visited and a contrast to how many upgraded
2. Total Upgrades
- This includes the caveat above about localized data and also this will give the user a "story" of what the plugin is doing for them ultimately

**Comment by Gitoffthelawn** [comment]
Per request by @pipboy96, I am posting the following in this issue.  Thanks!

Would it be possible to update the UI in the dropdown (and the toolbar button's counter) to reflect what HTTPS Everywhere is actually doing?

An example will hopefully best illustrate this feature request:

Let's say the user goes to `https://www.site-1.com`, and that site makes connections to `https://www.site-2.com` and `https://www.site-3.com`.

In this case, HTTPS Everywhere should be doing nothing, since every connection is *already* being established via HTTPS (please correct me if I'm mistaken).

Yet, depending on the sites involved (and thus the HTTPS Everywhere rules), it is not uncommon for the HTTPS Everywhere UI in the dropdown (as well as the counter on the button) to show that HTTPS Everywhere is involved in 1 or more actions.

In these cases - **which nowadays is a majority of cases** - I would like the HTTPS Everywhere UI to show that it did not do anything, and for the counter to reflect this as well.

Thanks for a great extension! Your hard work is appreciated!

**Comment by Gitoffthelawn** [comment]
@zoracon Hi Alexis.  It looks like this project will exist for another year, and then who knows, maybe someone will fork it.  How about re-opening this issue?  I don't think it will hurt anything, and maybe will help.

**Comment by zoracon** [comment]
> @zoracon Hi Alexis. It looks like this project will exist for another year, and then who knows, maybe someone will fork it. How about re-opening this issue? I don't think it will hurt anything, and maybe will help.

Fair. there's no harm in opening this one back up.
