### ISSUE TITLE
<something>.onion/ opens with "Block all unencrypted requests"

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#17063]
#### STR:

1. Enable "Block all unencrypted requests"
2. Visit http://something.onion/ (using Tor proxy obviously)

#### Expected:

The request should be blocked.

### Actual:

The website opens. (and Chromium displays "Not secure" warning before the URL)

**Comment by Bisaloo** [comment]
This is by design. Connections to onion services are actually encrypted and should therefore **not** be blocked by "Block all unencrypted requests".

Chromium UI is just confused because it is not supposed to know about onion services / it's not expecting you to visit onion services. But [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1382359) and Tor browser will correctly display it as secure.
