### ISSUE TITLE
http://zacharys.com/ not getting interstitial in Firefox EASE

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#17275]
Type: code issue

For EASE mode, http://zacharys.com/ is not getting the interstitial page in Firefox.

I'm seeing the interstitial in Chrome.

**Comment by Hainish** [comment]
cc @zoracon

**Comment by Hainish** [comment]
Tested in Firefox Quantum 64.0.2, x64 Linux

**Comment by zoracon** [comment]
I'm testing in FirefFox Quantum (64.0), Chromium 71.0.3578.80, and Chrome 70.0.3538.67 on Linux

All tests in EASE redirect me to a bad ssl https config page

For Chrome: 
`NET::ERR_CERT_COMMON_NAME_INVALID`

For Firefox:
_zacharys.com uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is only valid for . The certificate expired on October 18, 2016, 12:35:13 PM GMT-7. The current time is January 25, 2019, 1:48 PM._ 
`Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT`

I remember we discussed self-signed certs recently in #17192 

The consensus was since the interstitial page we have does not provide an option to add a self signed cert and the default pages for this error in browsers do, that is okay behavior.

**Comment by Bisaloo** [comment]
What about?

https://www.drawsvg.org/

> Error code: MOZILLA_PKIX_ERROR_ADDITIONAL_POLICY_CONSTRAINT_FAILED

It think it's related to #14738

**Comment by zoracon** [comment]
> What about https://www.drawsvg.org/ ?
> 
> > Error code: MOZILLA_PKIX_ERROR_ADDITIONAL_POLICY_CONSTRAINT_FAILED
> 
> It think it's related to #14738

Stramge, for url domain I get

_"www.drawsvg.org uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. The certificate expired on October 29, 2018, 4:59:59 PM GMT-7. The current time is January 28, 2019, 10:49 AM._ 
```Error code: SEC_ERROR_UNKNOWN_ISSUER```
"

**Comment by Bisaloo** [comment]
Strange indeed. Here is the full message FYI:

> # Warning: Potential Security Risk Ahead
>
> Nightly detected a potential security threat and did not continue to www.drawsvg.org. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
>
> Websites prove their identity via certificates, which are issued by certificate authorities. Most browsers no longer trust certificates issued by GeoTrust, RapidSSL, Symantec, Thawte, and VeriSign. www.drawsvg.org uses a certificate from one of these authorities and so the website’s identity cannot be proven.
>
>You may notify the website’s administrator about this problem.

(As mentioned in the message, I'm running Nightly)

**Comment by zoracon** [comment]
Gonna close this one for now, since it seems this is about self-signed/untrusted certs and not necessarily a case for interstitial trigger. Since our interstitial does not provide an option to add an untrusted cert.
