### ISSUE TITLE
README.md does not comply to Google Markdown style.

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#17547]
Type: code issue

**Comment by zoracon** [comment]
Trying to understand the issue here. We are not a Google based project and thought Google Markdown style was for Google open sourced projects. If this is not what you meant exactly, please clarify.

Now if you feel the README is unclear in anyway we can discuss that at least and I am open to suggestions.

**Comment by pipboy96** [comment]
@zoracon #14467

**Comment by zoracon** [comment]
> @zoracon #14467

Okay thanks for the older context. Will ask as to why the base README is not in compliance but the contribution docs are

**Comment by pipboy96** [comment]
@zoracon I think https://github.com/DavidAnson/markdownlint should be run over all .md files in the repo.

**Comment by pipboy96** [comment]
As far as I know, there is a plan to rewrite the documentation completely.
