### ISSUE TITLE
Settings window freezes Firefox for a long time / sometimes crashes it

### ISSUE THREAD

**Issue by alex42ka** [EFForg/https-everywhere#1771]
As described above. I'm using https-everywhere 5.0.4 within Firefox 38 on Ubuntu 14.04.

**Comment by reedy** [comment]
Can you try with a new ff profile to see if that helps?

**Comment by reedy** [comment]
Also, where did you build of FF 38 for 14.04 come from?

http://packages.ubuntu.com/trusty/firefox and http://packages.ubuntu.com/trusty-updates/firefox only offer 37.0.2

**Comment by alex42ka** [comment]
The package came via update:

https://launchpad.net/ubuntu/+source/firefox/38.0+build3-0ubuntu0.14.04.1

I will try to add a new profile and to test if the bug appears there as well.

**Comment by alex42ka** [comment]
Tried it with a new clean profile. Firefox didn't crash but produced high CPU-load and a lot of memory was in use. Then I tried my old profile again and realized that Firefox there as well wasn't crashing but in a freeze for more then a minute. The CPU load lasted even longer on 100% and up to 900MiB memory were in use. After more then a minute the settings window appeared but in the list there were no visible entries. I clicked "OK" and reopened the settings windows. This time the window appeared directly and the list were visible.
After closing and reopening the Firefox window again the first attempt to open the settings window of https-everywhere produced high load and made Firefox freeze and on the second attempt the window appeared directly.

**Comment by reedy** [comment]
See also #1775

**Comment by pde** [comment]
I can reproduce this in FF 39 / HTTPSE 5.0.5, but may not have time to work on it till late in the week.  May be able to provide some data to others, though...

**Comment by jsha** [comment]
This happens because the settings window includes a list of all rulesets packages with HTTPS Everywhere. To show that list, HTTPS Everywhere loads all rulesets into memory at once (normally it loads rulesets on an as-needed basis). That's a lot of memory, and it's also a lot of CPU time to parse all that XML.

My preferred approach is to remove the list of all rulesets, since it is rarely used. It's not that useful in a world of 15k rulesets, either. However, it would also be possible to show an empty list, wait for the user to type a query, and only load the rulesets matching that query.
