### ISSUE TITLE
Question about EASE

### ISSUE THREAD

**Issue by jadchaar** [EFForg/https-everywhere#17883]
Not sure if this is the best place to put this, but I did not know where else to bring it up, so here I go:

Is it possible to keep the EASE enforcement check until after a redirect chain occurs (e.g. a shortened URL expansion or HTTPS redirect), or does this completely defeat the purpose and safety advantage of using EASE?

I am asking because a number of times the EASE warning comes up after clicking a link in an email message (like a newsletter) or clicking a shortened URL (e.g. came across one recently on Twitter). Most of the time the links are for trusted sources but are not hardcoded as HTTPS, but instead have a redirect first to the HTTPS version. In cases like this, EASE ends up blocking the HTTP link, but when you click the link to proceed, it redirects to HTTPS.

**Comment by zoracon** [comment]
This would ultimately end up breaking the EASE function if we waited after redirect (since there's no real distinction if it truly came out of an email on the extension side). I have also came across this with emails and hopefully email marketing trackers get better at getting those links encrypted.

**Comment by jadchaar** [comment]
Dang that is a shame, I thought so :(. Well glad I brought it up--now I know.
