### ISSUE TITLE
Remove the "see more" dropdowns in place of hover text

### ISSUE THREAD

**Issue by j-james** [EFForg/https-everywhere#17894]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: feature request

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The two "See more" menus could be replaced with hover text. Currently, they contain only one line of text each. It would make the UI cleaner, eliminate bugs #17892 and #17893, and fit with design conventions of similar addons.

Cookie Autodelete and Noscript implement this quite nicely, but I unfortunately cannot get a screenshot.

**Comment by zoracon** [comment]
Thank you for the feedback. Removed the first "see more" completely since it redundantly repeats and wasn't as needed. The second one however reveals full settings for the site you are on and have much more than one line of text. Hopefully this resolves this pain point with release 2019.5.6.1 and closing for now.
