### ISSUE TITLE
cose.manifest: Unknown manifest directive

### ISSUE THREAD

**Issue by sagitter** [EFForg/https-everywhere#17945]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Hi all.

`https-everywhere` is provided inside a fork of Firefox web-browser.
Just a question about these errors which come out with latest `https-everywhere` code installed in Firefox-60.6.3ESR; what does mean?

```
BUILDSTDERR: Error: /builddir/build/BUILD/icecat-60.6.3/objdir/dist/bin/browser/extensions/jid1-KtlZuoiikVfFew@jetpack/META-INF/cose.manifest:1: Unknown manifest directive: Manifest-Version:
BUILDSTDERR: Error: /builddir/build/BUILD/icecat-60.6.3/objdir/dist/bin/browser/extensions/jid1-KtlZuoiikVfFew@jetpack/META-INF/cose.manifest:3: Unknown manifest directive: Name:
BUILDSTDERR: Error: /builddir/build/BUILD/icecat-60.6.3/objdir/dist/bin/browser/extensions/jid1-KtlZuoiikVfFew@jetpack/META-INF/cose.manifest:4: Unknown manifest directive: Digest-Algorithms:
BUILDSTDERR: Error: /builddir/build/BUILD/icecat-60.6.3/objdir/dist/bin/browser/extensions/jid1-KtlZuoiikVfFew@jetpack/META-INF/cose.manifest:5: Unknown manifest directive: SHA1-Digest:
BUILDSTDERR: Error: /builddir/build/BUILD/icecat-60.6.3/objdir/dist/bin/browser/extensions/jid1-KtlZuoiikVfFew@jetpack/META-INF/cose.manifest:6: Unknown manifest directive: SHA256-Digest:
```
Please, see at the bottom of this log:https://koji.fedoraproject.org/koji/getfile?taskID=34752996&volume=DEFAULT&name=build.log

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by zoracon** [comment]
It looks like the builder in whatever distribution this is in is not accounting for the new files that showed up in the META-INF directory that Mozilla added recently. 
The two new files that were brought in are `cose.manifest` and `cose.sig`

We do not control which files they are since AMO (Mozilla Addons) dictate what go in the META-INF folder. But these files did not exist until the 2019.5.2.1 release, so my hunch is that something in icecat is not picking that up. 

We do not officially support Icecat so maybe also bring up with that project how they are unpacking and packing HTTPS Everywhere.

**Comment by sagitter** [comment]
Thank you.
