### ISSUE TITLE
EASE does not work on first URL after refresh

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#17960]
Type: code issue

## Steps to reproduce

1. Disable the related `Freerangekitten.com` ruleset
1. Visit http://freerangekitten.com/
1. Enable EASE

## What happens

The page reloads and opens http://freerangekitten.com/

## What should happen

The page reloads and opens https://freerangekitten.com/

## Browser and Extension version

Firefox 66.0.5 with HTTPS Everywhere 2019.5.13

**Comment by cschanaj** [comment]
I can reproduce this issue on HTTPS Everywhere 2019.1.31 as well. So I guess this is unrelated to the recent UI redesign.

The problem is that `chrome.storage.onChanged` is not triggered immediately after `setOption_` is called. Having a decent timeout, say 1 seconds, before reloading the page resolve the issue for me. 

I believe several runtime settings are also affected. 

P.S. IMHO, having long timeout is not a very good solution since the extension UI will appear less responsive. 

https://github.com/EFForg/https-everywhere/blob/03e7474546853b6d5627e4f9f25c93156f066faf/chromium/background-scripts/background.js#L85-L104

**Comment by pipboy96** [comment]
See also #17746.

**Comment by zoracon** [comment]
Is this issue still persistent? Taking the time in the next week to go over these issues that have been sitting. Thank you for your patience.
