### ISSUE TITLE
Macromedia.com (rule) versus helpx.adobe.com/flash-player.html

### ISSUE THREAD

**Issue by grahamperrin** [EFForg/https-everywhere#18726]
Spun off from https://github.com/EFForg/https-everywhere/issues/12716#issuecomment-405039327 and https://github.com/EFForg/https-everywhere/issues/12716#issuecomment-532374200

> We don't officially support old Firefox versions and forks based on them, sorry.

With apologies for late follow-up, the issue is reproducible with: 

- Mozilla Firefox 71.0 (20191130193638)
- home-built Waterfox Classic 2019.10 (20191103135811). 

### https://helpx.adobe.com/flash-player.html

* https://www.eff.org/https-everywhere/atlas/domains/macromedia.com.html

**If** the rule for _Macromedia.com_ is enabled **then** the page response to a click on the amber 'Check now' button does not progress beyond: 

> Please Wait.
> Checking latest version info.

![image](https://user-images.githubusercontent.com/192271/70030105-6b74f880-15a0-11ea-998c-355791d5a6c4.png)

### Workaround

Disable the rule, allow the page to reload then again, click the 'Check now' button. 

### Environment

```text
$ date ; uname -v
Tue  3 Dec 2019 07:37:27 GMT
FreeBSD 13.0-CURRENT #44 r355172: Thu Nov 28 22:33:25 GMT 2019     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
$ pkg query '%o %v %R' firefox waterfox
www/firefox 71.0_1,1 FreeBSD
www/waterfox 2019.10.c.1 unknown-repository
$ 
```

**Comment by pipboy96** [comment]
Waterfox is not supported, as a fork, but since it's reproducible on original Firefox, this is still a valid issue. I can only successfully reproduce when Flash is actually installed and enabled. The issue seems to be caused by rewriting these URLs:

- http://fpdownload.macromedia.com/get/flashplayer/update/current/xml/crossdomain.xml
- http://fpdownload.macromedia.com/crossdomain.xml
