### ISSUE TITLE
Please remove "onboarding" page popping up when the extension is updated

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#19028]
IMHO it is absolutely useless and only creates nuisiance.

**Comment by pipboy96** [comment]
@KOLANICH I think you should discuss this with @zoracon due to it being either her or EFF internal decision. I do believe this page is useful, but I think it should be optional (the user should be able to opt out of seeing it again every update).

**Comment by zoracon** [comment]
@KOLANICH Hello. After many emails of users not knowing what is updated, and where updated features are, I decided it was high time for a page that shows significant visual changes in the U.I.

This may be useless to you, but this is recommended practice across extensions.

With that said, we do not plan on having this pop up each time if there is no significant U.I. update.

This only runs once on update. Close, and you won't see it again. If you see it pop up again before a release, please file an issue. Otherwise, this is staying to benefit users who have requested this feature for a while.
