### ISSUE TITLE
Don't show changelog after updating

### ISSUE THREAD

**Issue by uusijani** [EFForg/https-everywhere#19030]
Type: feature request

After starting Firefox today an unrequested "What's Updated" tab from HTTPS Everywhere (2020.3.16) popped up. I failed to find a way to prevent my workflow from being interrupted this way, so I had to resort to preventing automatic updates of the extension altogether.

Please don't open unrequested tabs. I can find the changelog if I need to.

**Comment by glennsl** [comment]
With Chromium, extensions are updated without needing to restart the browser, so this will just pop up whenever, even stealing focus from whatever else you might be working on. Great fun if you have multiple profiles as well. I've been interrupted three days today.

Thanks to the developers for all the good you're doing with this extension, but please don't do this. This behaviour is not just annoying but suspicious. It erodes the trust you've built up over the years.

**Comment by zoracon** [comment]
After many emails of users not knowing what is updated, and where updated features are, I decided it was high time for a page that shows significant visual changes in the U.I.

This may be useless to you, but this is recommended practice across extensions.

With that said, we do not plan on having this pop up each time if there is no significant U.I. update.

@glennsl are you saying you saw the extension's visual changelog pop up three times for in the same browser?

**Comment by zoracon** [comment]
Related #19028

**Comment by pipboy96** [comment]
@zoracon We need an opt-out switch, or possibly showing the page only once (on first installation), and then show the changelog in the extension popup only.

**Comment by zoracon** [comment]
> @zoracon We need an opt-out switch, or possibly showing the page only once (on first installation), and then show the changelog in the extension popup only.

@pipboy96 This was an update page that isn't for installation (which is being planned for new users). This is meant to only display once on update. I can toy with an "opt-in" rather than "opt-out" page, because it would just trigger on next update for everyone and cause a cascade of commentary again. So I'd rather just set that up so it wouldn't appear again for everyone.

Of course, that also means less savvy users would need to know where this option is. Which would mean I need to plan on many emails again from users being alarmed by visual changes. It's a rock and a hard place kind of decision. But I rather deal with the emails of users asking where things are. Instead of the adverse responses to the visual change log. The extension stores are doing a better job of generally educating users on extensions, so I am hoping more know where to find settings now.

**Comment by pipboy96** [comment]
@zoracon Should we disable this page for Tor Browser users?

**Comment by zoracon** [comment]
> @zoracon Should we disable this page for Tor Browser users?
@pipboy96 possibly, I think the opt-in option will take care of this since they would need to go into settings to enable this

**Comment by glennsl** [comment]
> @glennsl are you saying you saw the extension's visual changelog pop up three times in the same browser?

Yes, because I use multiple profiles (ie. sandboxes) I have the extension installed multiple times in the same browser. So that of course exacerbates the issue, but that isn't the real problem. The problem is that it hijacks my attention suddenly and without warning, regardless of whatever else I'm doing on my computer. That is very aggressive for what's just a change log and triggers memories of the pop-up ads of yore.

How about just opening a background tab on browser start-up instead? That would be pretty discoverable without being excessively annoying.

**Comment by pipboy96** [comment]
@zoracon Maybe we can just use a popup similar to the one that was previously used for a counter?

**Comment by zoracon** [comment]
> @zoracon Maybe we can just use a popup similar to the one that was previously used for a counter?

Yea, something like a notification dot maybe with a link in the menu. PB dev suggested maybe a "what's new" link in the popup menu along with the notification dot.

Maybe the flow can be 

- Notification dot
- Link in popup menu
- Go to page
- Opt in link for future updates page that redirects users to settings

**Comment by zoracon** [comment]
I can work on the above and adjust this and try to do a release with this fix in April

**Comment by zoracon** [comment]
Attaching a patch if anyone would like to test this workflow prior to PR release.

This triggers a notification badge and sets an inactive tab. Of course this isn't solidified, but it would be great to get some feed back prior to the PR for this.
https://gist.github.com/zoracon/eac248b54128dab18c2eded615ebde6c

**Comment by pipboy96** [comment]
@zoracon The notification should go away once the tab gets active for the first time, and the extension popup should have a link that makes the tab active when pressed.

**Comment by ssokolow** [comment]
As this is both extremely intrusive for me (a tech-savvy person) and the most recent example of behaviour that prompted my mother (a non-tech-savvy person) to call me, fearful that she'd been hacked because an addon was so thrilled that it had updated, I've opened a request that AMO forbid this kind of behaviour in favour of something less intrusive.

**Comment by VictorBlomberg** [comment]
I've installed this extension for a less tech-savvy person. This showed up while watching a movie on a streaming service, and the movie continued in it's tab while the user tried to understand what's happened. This is stressful, irritating, and completely unacceptable. It's also been a distraction for me in my workflow several times on different devices.

I do _really_ appreciate your hard work, and what you have done. And I hesitate to come here and criticize this fantastic extension. But this feature is a problem.

The way the popup is designed doesn't really help not making users stressed, but I don't see the design as the ultimate problem. It's how and when it appears (right in your face, anytime).

**Comment by ssokolow** [comment]
For the record, I've now seen that bleeping popup four separate times, across two devices and four Firefox profiles. Every time I see it, I question whether I care enough to keep HTTPS Everywhere installed a little more.

**Comment by pipboy96** [comment]
@ssokolow Unfortunately, it's impossible to make a release due to shelter-in-place order in the area EFF headquarters is located in. It's impossible to do anything with this issue right now.
