### ISSUE TITLE
Rules reseting after closing the browser

### ISSUE THREAD

**Issue by Tiamatti** [EFForg/https-everywhere#19163]
As you know, decentraleyes extension asks to add some exceptions to https everywhere.  However, after following the instructions [here](https://decentraleyes.org/configure-https-everywhere/), the https everywhere configs resets after closing and reopening Chrome or even Chromium Edge. 

The issue have already been reported to decentraleyes author, but it seems to be a https everywhere problem.
You can check it [here](https://git.synz.io/Synzvato/decentraleyes/-/issues/379)

**Comment by zoracon** [comment]
I'll look into this this afternoon. Can you also give me Chrome version and O.S.? For tracking purposes?

Thank you

**Comment by Tiamatti** [comment]
I tried with the last versions of Edge and Chrome. I just tested today, and the problem persists

https://decentraleyes.org/configure-https-everywhere/

**Comment by cschanaj** [comment]
@Hainish @zoracon this issue seems to be related to the WASM implementation not loading the `rule_active_states` correctly. On Google Chrome, the `ruleActiveStates` is properly stored in the browser storage and the pure JS implementation is correct. (Tested by commented out the following line of code in `rules.js`). 

https://github.com/EFForg/https-everywhere/blob/5271d73989762b566f9717eb100bee8295fe51b0/chromium/background-scripts/rules.js#L212
