### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG on custom local domain /etc/hosts

### ISSUE THREAD

**Issue by InkFlo** [EFForg/https-everywhere#19341]
Type: code issue
Browser: Firefox 77.0
OS: Linux

Hello,

I'm not sure if it is the right category for this issue, my apologies if it is not.

I'm using a custom domain (**django.local**) set on **`/etc/hosts/`**

The problem is that when I'm using **HTTPS everywhere** with **Encrypt All Sites Eligigibles ON**, the browser show me the HTTPS Everywhere popup to notice about security error

[https://imgur.com/a/FdKxijk](https://imgur.com/a/FdKxijk)

`HTTPS Everywhere noticed you were navigating to a non-HTTPS page`

But when I click on **Open insecure page** or **Open insecure page for this session only** I got a firefox error page

```
Secure Connection Failed

An error occurred during a connection to django.local:8000. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.
```

So it is impossible for me to access my custom local domain on **HTTP** without switching (**Encrypt All Sites Eligibles**) to **OFF**

Thanks

**Comment by pipboy96** [comment]
@zoracon This seems to be related to the whitelisting bug.

**Comment by MorgothSauron** [comment]
I experience the same problem (Firefox 79, Linux).

I have a host that can be reached by it's name thanks to local DNS (PiHole).

When I try to open `http://picloud:9080` I will the get the usual warning from the extension. I will use the "Open Insecure" options and 2 things can happen:

1. The extension warning page shows again
2. I'm redirected to `https://picloud:9080`. 

When redirected I get the `SSL_ERROR_RX_RECORD_TOO_LONG` error because there is no https available.

Like @InkFlo, I have to switch off "Encrypt All Sites Eligible is ON" to be able to connect.

On the other hand,  it works fine If I use the IP (`http://192.168.0.3:9080`)

**Comment by zoracon** [comment]
Can you re-test with version 2020.8.13 to see if your issue persists?

**Comment by MorgothSauron** [comment]
Looks good for me with 2020.8.13. I was unable to reproduce the problem using the same URL as before. Thank you.

**Comment by InkFlo** [comment]
It work fine for me too with 2020.8.13.Thanks !
