### ISSUE TITLE
Vox.com not loading all videos/images

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#1936]
Using Firefox 38.0.5 on Windows 7 with HTTPSE 5.0.5 Vox.com won't load all videos and images when you pull up an article.

https://www.vox.com/2015/6/15/8784191/apple-kill-mac-nope is an example.  If you load the page like this, not every image will load (the bottom one never appears, but disable the Vox.com rule and everything shows up properly.  https://www.vox.com/2015/5/14/8606453/fox-news-leeches has the same thing with video content.

**Comment by fuglede** [comment]
Two different things of the same nature going on here.

* On the first page, the missing content is available at http://www.vox.com/embed/cards/apple/what-is-apple, but is not loaded since it is regarded as mixed content (unsecure content referenced from a secure connection). It seems like the entire thing is on Vox' own server though, so they could possibly fix this by changing their "http://" references to "https://" or simply "//".

* The second page is worse; the problem is still mixed content but in this case, it's obtained from a third party domain. More precisely, the page tries to load http://media.mtvnservices.com/embed/mgid:arc:video:thedailyshow.com:45398c15-3937-4c26-9ced-aaa263602007 which fails at mixed content. Again, they could *almost* fix this by simply changing the reference to https, but actually the https setup on mtvnservices.com appears [to be problematic](https://media.mtvnservices.com/embed/mgid:arc:video:thedailyshow.com:45398c15-3937-4c26-9ced-aaa263602007), so that this is not actually possible in a reasonable fashion.
