### ISSUE TITLE
Copy button on EASE warning page

### ISSUE THREAD

**Issue by finn0** [EFForg/https-everywhere#19385]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: Feature request

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)
### Description
It would be nice, if HTTPS-everywhere has a copy button present just beside of URL (for which it is showing warning message) to copy URL directly to clipboard.

### Use-case
Sometimes I need know to URL for which HTTPS-everywhere showing warning message in EASE mode. HTTPS-everywhere do show URL on warning page, but longer URL replaced with `...` sign.

![ease-copy-button](https://user-images.githubusercontent.com/28824347/87101300-48997980-c23e-11ea-9b18-ef68909cdc4c.png)

Currently, I've to extract this URL from browser's address bar and then decode it, which may be harder for average user, but adding a copy button make things easier for average users.

PS: What do you think, is it good idea to add a copy button? If so, can I make PR for this?

**Comment by finn0** [comment]
And one more thing, is there any specific reason to keep `Open insecure page for this session only` button below `Open insecure page` button? To me, it makes sense to put one after another in smaller screen resolution like mobile phones, tablets etc, but for desktop, can't we put them same line? In desktop, we'll also have considerable amount of space between these two buttons.

**Comment by zoracon** [comment]
Thanks for the suggestion around the copy button. Maybe we can use the Clipboard API for this. I also want to look into the security implications of using such a feature. But either way, I will work to make the url more accessible. if we can't use the Clipboard API for some reason, we can just display the full url properly. Sometimes URLs get intensely long for email click-through links. Which was the reasoning behind the cap.

As far as the button arrangement, we just kept everything within a certain block.There no specific reasoning other than keeping the buttons stacked for flexibility on different screens. Right now our design efforts are on pause but we plan to pick back up when the capacity is there later this year or early next year. When we make future design choices, we really want to be intentional, even if it's a simple layout change.

**Comment by eilliwyehtor** [comment]
This is fun.  I never did anything like this. I still have suck a hard time with facebook. I love this stuff though man badd ass I'mma make something
