### ISSUE TITLE
Cause SoundCloud blank on Firefox 68

### ISSUE THREAD

**Issue by a0193143** [EFForg/https-everywhere#19511]
Type: ruleset/website issue
Domain: soundcloud.com
Brwoser: Firefox 68.11.0 ESR

Everything is fine until "Login" to SoundCloud, added soundcloud.com to Disabled Site seems do nothing, the page just couldn't load.
And have to clear cookie of SoundCloud to back to normal, not just disable this add-on.

Or maybe is some compatibilty issue with Firefox 68? Because it's fine on lastet Firefox and Chrome.

**Comment by zoracon** [comment]
A couple of questions:

1. Does the site work with the extension completely disabled?

2. Do any errors appear?

**Comment by rsguhr** [comment]
I have also problems with soundcloud.com while using HTTPS Everywhere.

HTTPS Everywhere cause the creation of a lot of cookies with every visit of the website (Cookie names: _tldtest_xxxxxx and undefinedxxxxxxxx). At some point there are so many cookies that soundcloud.com refuse new connections because the HTTP Header is too big (HTTP Error 431).

Disable HTTPS Everywhere for soundcloud.com didn't worked but disabling the stable rule for soundcloud.com (Partial) worked for me.

I'm using Vivaldi (based on Chromium). The problem appeared on 18.08. for the first time.

**Comment by pipboy96** [comment]
I tracked this problem down to a `<securecookie>` tag, see #19538.

**Comment by zoracon** [comment]
Thank you for the additional information. I will review the pending fix.
