### ISSUE TITLE
Keep opera browser plugin up to date

### ISSUE THREAD

**Issue by Root-Core** [EFForg/https-everywhere#19679]
Type: other

Please provide the current version for Opera users.
It would also be awesome, if the Opera plugin was released as frequently as for other browsers.

Last update: 08 January 2019 - which is **way** too old

I'm using the Chrome Plugin - but if this is the solution, please remove the plugin altogether from Opera addon store.

**Comment by zoracon** [comment]
Sorry for the lag on updating in Opera. For what's it's worth, there is no security update, if there was we wouldn't have allowed the older version to remain as in Opera.

The problem is that many downstream channels and officially supported channels rely on a major file (`rulesets.default`) that Opera wants us to rename for their standards (standards Chrome does not have). Changing the name would be easy enough if it didn't require so much coordination because many downstream channels rely on it.

But you are right, this delay on updating is not a solution, I will weigh the pros and cons of continued support in Opera (the team won't budge on their MIME type blocker, I asked) and make a decision this week.

Thank you!

**Comment by Root-Core** [comment]
Without knowing any details, would aliasing the `rulesets.default` file be a solution or rename it for the opera release while building it?

**Comment by pipboy96** [comment]
@Root-Core The main problem would be the fact we would have to publish a separate .crx for Opera.

**Comment by Root-Core** [comment]
Why not releasing the crx for other browsers too? Does it lead to any problems, if the file has another name in the release?
I imagine that the downstreams etc. rely only on the source beeing named as is, not on the name in the packed version.

Just an idea, but as I stated.. i have no idea about the structure of this project, so i'm sorry if that is stupid.

**Comment by zoracon** [comment]
@Root-Core Not stupid at all, some downstream partners directly reference the naming convention. And as @pipboy96 said, we would need to release a separate CRX file for Opera. I am currently looking at the build script to see if the workflow checks out.

**Comment by zoracon** [comment]
This is up to date in Opera now! Thank you.
