### ISSUE TITLE
[Question] - Quora redirection with ?share=1

### ISSUE THREAD

**Issue by shivasagarrao** [EFForg/https-everywhere#19787]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

How to add a rule for quora website such that **?share=1** should be added the end of every a Quora link. For example https://www.quora.com/How-do-I-read-more-books should be redirected to https://www.quora.com/How-do-I-read-more-books?share=1

Adding **?share=1** at the end helps in removing annoying popup of signin/signup.

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by pipboy96** [comment]
@shivasagarrao Thanks for a good question! Unfortunately, HTTPS Everywhere is not a good fit for this purpose, since Quora uses referrer URL to decide whether to block you from viewing the page. I recommend you to install [Referer Control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin) and blacklist the Quora website in it. That worked very well for me.

**Comment by shivasagarrao** [comment]
[Referer Control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin) last update is almost 2 years ago. I'm currently using [Redirector](https://github.com/einaregilsson/Redirector) extension to obtain this feature by following the steps mentioned [here](https://github.com/einaregilsson/Redirector/wiki/Removal-of-annoying-popup-of-signin-signup-for-viewing-any-question-on-Quora-website).
