### ISSUE TITLE
Radio.Garden Broken - https is not supported - stuck in loop - https forwards to http

### ISSUE THREAD

**Issue by war59312** [EFForg/https-everywhere#19927]
http://radio.garden/ does NOT support https.

So https-everywhere causes the site to reload forever.

It's because they forward https back to http :(

See: https://github.com/EFForg/https-everywhere/pull/19428

**Comment by puckey** [comment]
I run http://radio.garden and would love to get this fixed. 

Our website only functions on http and therefore redirects from https back to http. We did have our site on https before, but since new versions of browsers don’t allow for http media resources to be loaded in a https context we were forced to move back to http. (80% of the radio streams we embed are still hosted on http)

Let me know if there is anything I can do to assist!

**Comment by war59312** [comment]
Yea that's a bummer. Guess they (the radio providers) are going to wait until they are forced to make the switch (as in, when browsers stop supporting http outright).

So, as in, might as well be never. Really a shame, as I'm sure the radio providers could easily enough get a free cert from https://letsencrypt.org/ . Lazy bastards they are!

**Comment by zoracon** [comment]
@puckey I can remove the rule for that site since HTTPS is not supported at all.

I don't know how much influence you have over those radio streams, but we also have [Certbot](https://certbot.eff.org/about/), that helps web admins install Let's Encrypt certificates.

**Comment by war59312** [comment]
https://bettercrypto.org/ is another great resource for correctly setting up https
