### ISSUE TITLE
HTTPS Everywhere seems sometimes to break Jitsi

### ISSUE THREAD

**Issue by janvlug** [EFForg/https-everywhere#19989]
Type: ruleset/website issue

Sometimes [Jitsi](https://meet.jit.si) seems not to work because of HTTPS Everywhere.
The error you get is:
![image](https://user-images.githubusercontent.com/5903208/112625989-e5815e80-8e2f-11eb-98d4-a8484bea67a8.png)
For more details see: https://github.com/jitsi/jitsi-meet/issues/8380

**Comment by Thomas131** [comment]
Hi!
I am NOT from HTTPS Everywhere or EFF. I just also experienced this problem.

The root is https://github.com/amplitude/Amplitude-JavaScript/issues/326 but they seem ignorant.

A solution would be to block cookies completly for meet.jit.si - since it also works without. And clearing all the already set cookies for sure :) But I think that there is little that HTTPS Everywhere can do without loosing its functionality.

God bless :)

**Comment by Thomas131** [comment]
Should be fixed by https://github.com/amplitude/Amplitude-JavaScript/pull/381

**Comment by zoracon** [comment]
We unfortunately do not have access to fix this issue on the Amplitude's repo
