### ISSUE TITLE
Toolbar button disappears in Firefox popup windows

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2015]
I noticed that for popup windows (i.e. stuff created by window.open in a way that opens a new window), the toolbar button vanishes but the ruleset counter stays.

https://i.imgur.com/ifIMUU9.png

Tested with user-agents
* Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0
* Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0

To reproduce:
* Run <code>window.open("https://eff.org","_blank","width=600")</code> in the web console.

**Comment by jeremyn** [comment]
FYI: to see the toolbar for popups, `dom.disable_window_open_feature.toolbar` in `about:config` must be `true` (see [here](http://kb.mozillazine.org/Prevent_websites_from_disabling_new_window_features)).

@fuglede I see both the counter and the toolbar button so it looks like this issue is fixed to me. Is it fixed for you?

**Comment by fuglede** [comment]
Looks like it. And with the toolbar not being there by default anymore, it's even less of a problem. Thanks for trying it out, and wonderful if these bugs are just fixing themselves.
