### ISSUE TITLE
Support "*.taobao.com" and "*.tmall.com"

### ISSUE THREAD

**Issue by lqf96** [EFForg/https-everywhere#2031]
It seems that taobao and tmall has added full https support on nearly all their subdomains. however i have some problems writing a ruleset (build always failed). So please add rules for these sites, thank you.

**Comment by donced** [comment]
@lqf96 You are referring to #2030? Before you create pull request, you can test it yourself. Assuming you're on Linux environment, in https-everywhere folder, `bash fetch-test.sh src/chrome/content/rules/Taobao.xml`

**Comment by donced** [comment]
My suggestions:
Taobao.xml
1. you don't have to create `rule from to` for every `target host`. A single `<rule from="^http:" to="https:" />` is sufficient.
2. Remove `assets.taobaocdn.com` and `s.tbcdn.cn`. They are no longer valid and have been replaced with `*.alicdn.com`. One way to test the URL is `curl -I -L https://s.tbcdn.cn`.
3. Replace `<securecookie host="^\.login\.m\.taobao\.com$" name=".+" />` with `<securecookie host="^.*\.taobao\.com$" name=".+" />` to apply to `*.taobao.com` instead of just `login.m.taobao.com`.
4. you mentioned "Taobao now has full SSL support on their sub-domains, through a few of them is still suffering from mixed content problems.", which subdomain? does mixed content problem breaks the page? you might need to add exclusion rule.
5. Since tmall is separate product/website from taobao, I suggest to create new ruleset instead.

Pull request
I notice you create a pull request from your `master` branch which includes three files change. I suggest to create separate pull request for each file/ruleset. The reason is because `how-old.net.xml` and `ppy.sh.xml` might not have any issue, however issue of `Taobao.xml` prevents those two ruleset from getting merged if you put them in one pull request.
How to create separate pull request? Instead of:
```
master branch:
    how-old.net.xml
    ppy.sh.xml
    Taobao.xml
```
Pull request `your repo:master` vs. `EFForg:master`
why not,
```
how-old branch:
    how-old.net.xml
```
Pull request `your repo:how-old` vs. `EFForg:master`
and so on.

**Comment by 2d1** [comment]
tmall.com.xml and Taobao.xml are now structured such that just adding a target is sufficient for a simple http → https rewrite. Feel free to make pull requests adding targets that I've missed.
