### ISSUE TITLE
Tubechop.com doesn't work

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2228]
http://www.tubechop.com/watch/3

Turning off the YouTube rule allows videos to properly load and play.  

Using HTTPSE 5.0.6 with Firefox 39.0.

**Comment by finaljason** [comment]
Their integrated flash-based player (seems to be just a framework for the chromeless youtube player) fails to load https://www.youtube.com/apiplayer?version=3 over HTTPS
Excluding this URL from rewrite would solve the problem but also lower security provided by YouTube rule for other pages with a working solution. The YouTube FlashAPI used in this case is also deprecated since January 27, 2015.
Does someone has a good idea how to fix this issue?

**Comment by donced** [comment]
I'm not familiar with youtube API, but does the FlashAPI uses different URL (i.e. http://www.youtube.com/apiplayer?version=3)? If the URL is unique, perhaps we can exclude it? Another (a bit crazy) idea is to rewrite the URL to current API.

**Comment by finaljason** [comment]
The Flash API (the proper name is YouTube ActionScript 3.0 Player API, further information at https://developers.google.com/youtube/flash_api_reference) was deprecated in favor of the new IFrame API. The new API decides dynamically whether to embed the player as HTML5 or Flash and presents it via IFrame. I'm not familiar with the API's either and just looked over the documentation quickly, but i think we cannot rewrite to it because the approach is too different and would require more than just URL rewrites.
I just looked a little bit more into it and it seems that the flash application (theirs, which loads and controls the youtube player) seems to choke on forced HTTPS. With the YouTube rule deactivated it first issues a HTTP request and then gets redirected by a 301 from Youtube itself to HTTPS without problems. So maybe we can exclude it from rewrite? I will test some things out tomorrow or a the weekend.

**Comment by finaljason** [comment]
Okay, I opened a pull request for this issue and wrote a little summary about the problem there. The fix excludes http://www.youtube.com/apiplayer from rewrite and will hopefully prevent similar issues with other sites using third-party applications to play YouTube videos.

Thank you for your report and thoughts :)

**Comment by jsha** [comment]
Thanks for digging into this and finding a fix! Nice work @finaljason.
