### ISSUE TITLE
http://www.google.com/404 not redirected 

### ISSUE THREAD

**Issue by percyalpha** [EFForg/https-everywhere#2333]
Just curious why this URL is not redirected even though google.com is in the rule-set

**Comment by foobar13373** [comment]
Can confirm on FF39, Windows 10.

**Comment by donced** [comment]
At least the resources are HTTPS.
![404 Google.com](https://veuwer.com/i/3499.png)

**Comment by donced** [comment]
https://www.google.com/404 is valid.
![HTTPS Google.com 404](https://veuwer.com/i/349a.png)

**Comment by donced** [comment]
From the [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.xml), I can't find `<rule from="^http:" to="https:" />` which would cover all directories/pages of an URL. Instead, in the current state of the ruleset, each directory must be explicitly specified. Since www.google.com/404 is not specified, it is not covered.

**Comment by semenko** [comment]
Yeah, the Google rule is complex, since Google.com has a (large) handful of pages that don't support TLS.

Closing as wontfix for now.
