### ISSUE TITLE
Badges do not look consistent between HTTPS Everywhere and Privacy Badger

### ISSUE THREAD

**Issue by qirtaiba** [EFForg/https-everywhere#2470]
![screen shot 2015-08-06 at 4 31 04 pm](https://cloud.githubusercontent.com/assets/627911/9125761/c445bc04-3c58-11e5-8948-47dffc8ad6dc.png)

**Comment by reedy** [comment]
Do you mean as to where the numbers are listed, plus size, shape, colour etc?

**Comment by qirtaiba** [comment]
Yes they just look weird together, it's a visual thing. 

-- 
Jeremy Malcolm PhD LLB (Hons) B Com
Internet lawyer, ICT policy advocate, geek 
echo "9EEAi^^;6C6]>J^=^>6"|tr '\!-~' 'P-~\!-O'|wget -q -i - -O -

**Comment by reedy** [comment]
I don't disagree :). Just wanted to confirm

**Comment by reedy** [comment]
What browser (and version) is this on? And what versions of the 2 extensions? On Chrome 46 on OSX, Privacy Badger 2015.8.5.1 shows the number in the bottom right... And HTTPSE 2015.7.17 doesn't show any numbers.

**Comment by qirtaiba** [comment]
On 11/08/2015 9:45 am, Sam Reed wrote:
>
> What browser (and version) is this on? And what versions of the 2
> extensions? On Chrome 46 on OSX, Privacy Badger 2015.8.5.1 shows the
> number in the bottom right... And HTTPSE 2015.7.17 doesn't show any
> numbers.
>

Firefox 39, Privacy Badger 1, HTTPS Everywhere 5.0.7.

-- 
Jeremy Malcolm PhD LLB (Hons) B Com
Internet lawyer, ICT policy advocate, geek
echo "9EEAi^^;6C6]>J^=^>6"|tr '\!-~' 'P-~\!-O'|wget -q -i - -O -

**Comment by reedy** [comment]
<img width="309" alt="screen shot 2015-08-11 at 19 08 34" src="https://cloud.githubusercontent.com/assets/67615/9205868/88e80af6-405c-11e5-9309-19bd1697dcb3.png">

This is mine in Chrome...

**Comment by jsha** [comment]
Yep, the different styles are definitely an issue. Chrome doesn't support the ruleset counter, which I think is fine. On Firefox I'm thinking of making no-counter the default, since it doesn't add much useful information. Instead we could move to a simpler enabled / disabled indicator based on icon size (while still offering the counter for folks who find it useful, like ruleset authors).

**Comment by fuglede** [comment]
As a side note: Privacy Badger uses Australis to draw the badge (which is a [one-liner](https://github.com/EFForg/privacybadgerfirefox/blob/b9fc2fb7691f1829ae680c523f2d63e83341effd/lib/ui.js#L235) including styles and everything), whereas in HTTPS-E it's built with [XUL bindings](https://github.com/EFForg/https-everywhere/blob/93d2b57daad1acd08328c3be495d962e559a6342/src/chrome/content/toolbar_button_binding.xml#L16). In particular, this also means that the Privacy Badger badge is not actually drawn on older versions of Firefox (including for instance what's shipped with Debian Jessie). One should be able to restyle rscounter/rsapplied directly to make it consistent with Australis based add-ons (although porting it to Australis entirely might be beneficial in the long run).

**Comment by fuglede** [comment]
So, I went ahead and stole the styles from the SDK. In my tests, this worked both in Firefox 31 and Firefox 40. The badges have always looked different (and bad) in Linux though, so it would be great if someone could test how they look elsewhere. In particular because it took a bit of manually fiddling to make it look like the Australis style badges (and it might still be off by a pixel or two). The style is in the branch fuglede/toolbar-style. Here's how it looks here:

![toolbarstyle](https://cloud.githubusercontent.com/assets/6169306/9289619/71f6ba04-4377-11e5-9ac4-5d31d629ac5a.png)

I think the dropdown arrow should be removed as well (but couldn't quite figure out how to do so). Another todo which persists with these changes is to fix #2253.

References:
* [Relevant add-on SDK method](https://github.com/mozilla/addon-sdk/blob/dcd987d3a94af8a07d4a0f93296b7c2bcc737d14/lib/sdk/ui/button/view.js#L216)
* [Relevant XBL](https://dxr.mozilla.org/mozilla-central/source/toolkit/content/widgets/toolbarbutton.xml?offset=600#99)
* [Australis toolbarbutton CSS](chrome://global/skin/toolbarbutton.css)

**Comment by fuglede** [comment]
One final comment from here: while <code>display: none</code> caused the weird bug where the toolbarbutton would be absorbed into the "more tools" menu, <code>visibility: hidden</code> works completely fine. Here's the result:

![tilgithub3](https://cloud.githubusercontent.com/assets/6169306/9291145/b72f1330-43b0-11e5-8d2c-e6c1158007d2.png)

**Comment by reedy** [comment]
<img width="307" alt="screen shot 2015-08-22 at 10 47 08" src="https://cloud.githubusercontent.com/assets/67615/9423435/4cc68d56-48bb-11e5-977f-c725b4e6fbaf.png">

**Comment by reedy** [comment]
![image](https://cloud.githubusercontent.com/assets/67615/9423438/75eca850-48bb-11e5-8bee-d3fa04a01e01.png)

**Comment by reedy** [comment]
<img width="259" alt="screen shot 2015-08-22 at 10 49 00" src="https://cloud.githubusercontent.com/assets/67615/9423441/91a2eb54-48bb-11e5-8a8f-50e57664701e.png">

**Comment by reedy** [comment]
<img width="263" alt="screen shot 2015-08-22 at 10 53 01" src="https://cloud.githubusercontent.com/assets/67615/9423451/01cc8c46-48bc-11e5-8489-eef3082cdd52.png">

**Comment by fuglede** [comment]
Thanks a lot for testing, @reedy. That's as inconsistent as I feared it would be ...

**Comment by jsha** [comment]
Also as an FYI, Mozilla's plan to deprecate XPCOM may mean that in the long run (18 months), XUL is no longer a thing, and we have to migrate to the WebExtensions style of doing things: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/. I'm guessing that button stying will be different in that world too.

**Comment by vgturtle127** [comment]
@fuglede Those look really good, dude!

Will they be the same in the WebExtensions port, or will they have to be done again?

**Comment by fuglede** [comment]
@vgturtle127: I wish they did; that was a naive attempt to copy the Australis toolbarbutton CSS to hopefully get something consistent looking, but it did not work cross-platform. But to answer your question, yes, I'd imagine that in that world, one would use the API to make it [look like this](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action).

**Comment by vgturtle127** [comment]
@fuglede The WebExtensions port will use that API, right?

**Comment by fuglede** [comment]
@vgturtle127: I'd imagine so; if I were the one to write it, it would, anyway.

**Comment by vgturtle127** [comment]
@fuglede OK, just wanted to make sure.

**Comment by rugk** [comment]
BTW with the new HTTPSE icon this looks worse:
![worsecounter](https://cloud.githubusercontent.com/assets/11966684/17676070/f59b3f3a-632c-11e6-8c02-b685e878ed2c.png)

HTTPSE 5.2.1, PBadger: 1.8.1, Firefox 48.0, Linux (Cinnamon)

**Comment by vgturtle127** [comment]
@rugk Oh, my. :laughing:

**Comment by J0WI** [comment]
We should definitively be consistent about the counter position (top-right in ltr)

**Comment by sabret00the** [comment]
BTW, I don't have the badge at all on the Firefox WebExtension (test)

**Comment by J0WI** [comment]
That's #10002

**Comment by koops76** [comment]
#10773

**Comment by J0WI** [comment]
fixed in #12552
