### ISSUE TITLE
stocktwits.com does not work when https-everywhere is enabled

### ISSUE THREAD

**Issue by kwinz** [EFForg/https-everywhere#2586]
Only an uncomplete, unstyled version of stocktwits.com loads when httpseverywhere is anabled

**Comment by kwinz** [comment]
[Rendering with the bug](http://i.imgur.com/sbvH7iH.png?1)

**Comment by kwinz** [comment]
Any progress? This forced me to disable HTTPS everywhere since August!

**Comment by sirhc** [comment]
This appears to be due to a [redirection rule](https://www.eff.org/https-everywhere/atlas/domains/stocktwits.com.html) that indicates https://new.stocktwits.com/ should be used. StockTwits has, apparently, finished whatever they were doing with that subdomain.

```
$ curl https://new.stocktwits.com/
curl: (7) Failed to connect to new.stocktwits.com port 443: Connection refused
```

I don't immediately see a way to modify rules locally, but I was able to get the StockTwits website to work by disabling only the rules for StockTwits.
