### ISSUE TITLE
Checking "Google" Breaks google.cn outside of China

### ISSUE THREAD

**Issue by zzq1015** [EFForg/https-everywhere#2747]
google.cn are resolved to IP address `*.*.*.160` outside of China, and no HTTPS support on that IP (TCP port 443 is not open)
Unchecking "Google" solves the problem.

**Comment by youdly** [comment]
Can confirm the issue. Adding `<exclusion pattern="^http://(www\.)?google\.cn" />` on [Google.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.xml) would fix it. But I'm concern whether this fix would affect China user. (Too bad [China Channel](http://chinachannel.fffff.at/) is not supported on later version of Firefox, otherwise I can help testing it.)
