### ISSUE TITLE
blog.shakirm.com fails to display mathjax correctly

### ISSUE THREAD

**Issue by xcombelle** [EFForg/https-everywhere#2757]
With firefox version 42.0a2 (2015-09-03) (developper edition),

When going to http://blog.shakirm.com/2015/08/machine-learning-trick-of-the-day-2-gaussian-integral-trick/, after several mouse scroll (which are needed because by default, there is a preview of the equation in gif) the equation disapear
When disabling mathjax https-everywhere rule everything looks working normal

As far as I unterstand, the script called is http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

And when failing lines like the following shows on console log:
downloadable font: download failed (font-family: "MathJax_Size4" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source: http://cdn.mathjax.org/mathjax/latest/fonts/HTML-CSS/TeX/otf/MathJax_Size4-Regular.otf?rev=2.5.3

**Comment by J0WI** [comment]
Can you still reproduce with the current version? It works for me.

**Comment by jeremyn** [comment]
I can reproduce this problem with Windows 10, Firefox 48.0.2, HTTPS Everywhere 5.2.4.

I don't think the mouse scrolling triggers it. Just scroll down a little to see the first equation and then wait. At some point the browser will lag for a moment and then the equation gets replaced with a bunch of gray rectangles. You'll know you've waited long enough if, when you right click the equation, the right-click menu has `About MathJax` and `MathJax Help` options instead of the standard browser right-click menu.

**Comment by galeksandrp** [comment]
When you will be able to get MathJax menu right-clicking on formulas, you can sure that all things is loaded. I get CORS issue only in Firefox, seems that Chrome does not requre CORS headers for urls from CSS.

**Comment by Bisaloo** [comment]
I can't reproduce this issue. I think this is fixed and can be closed.
