### ISSUE TITLE
Rule "Akamai" breaks videos on ted.com

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2816]
Test case:
http://www.ted.com/talks/chris_urmson_how_a_driverless_car_sees_the_road
and hit the play button.

**Comment by Multibituser** [comment]
Look, I don't know what you guys are talking about, but last night I was in
get hub trying to figure out whether Evernote was safe you know I've been
using it for years, however I wanted to just see what you thoughts were. As
an instructional designer of major universities all of the United States
I've become quite aware of the possibility of being infected by such script
that these types of user-friendly but harmful type enhancers such as Java,
Adobe, and flash can be. But now I am locked out of my Google account and I
can't get back in because everything on my side in the world has been
stripped down to a very naked nonjob world and I need it back-- because
although your site and your points speak for themselves as there is no
argument from me, I'm out of the job. Please help- can you put me back
knowing that there are vulnerabilities that I could be hacked. I know I'll
be careful.  But with the basic strips down script that I have on my phone
right now I can't see my courses that I filled for eight months it's going
online right now. I can't see or hear anything going on on live power
stations that are done at least twice a week for the
universities's requirement. I'm in charge of these statewide university
standard requirements and I must get back to point I can  monitor the
course otherwise  millions of students counting on me ( as well as
professors) might be locked out of their courses! please put me back to the
way i was-- don't get me wrong I'm so very grateful for you showing me how
absurd Lee and sanely corrupt Evernote is through the script, but I have to
get back to the real world! I need it in order to continue my
profession. please please take me out of this although very efficient and
safe  online environment, please put me back because I have certain
requirements under my contract. I can't even see multimedia OR LOG IN!!! I
do appreciate it everything you've done to help me see that there are such
vulnerabilities however please somebody put it back where it was.
kindly yours,
Julie



On Monday, September 7, 2015, KommX <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Test case:
> http://www.ted.com/talks/chris_urmson_how_a_driverless_car_sees_the_road
> and hit the play button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/https-everywhere/issues/2816>.
>


-- 
- Julie

**Comment by semenko** [comment]
Closed by #2818
