### ISSUE TITLE
lego.com rule broken

### ISSUE THREAD

**Issue by austin987** [EFForg/https-everywhere#2858]
Trying to load http://www.lego.com/en-us/friends redirects me to https://wwwsecure.lego.com/en-us/friends, which gives:
Bad Request - Invalid Hostname

HTTP Error 400. The request hostname is invalid.

HTTPS-E 5.0.9

**Comment by MDawg957** [comment]
This ties to #1967 which is still not fixed as well

**Comment by TheNavigat** [comment]
@MDawg957 I don't think that's related.

Some pages are not available while using ```wwwsecure.lego.com```, however, the domain does work correctly with other pages. http://www.lego.com/en-us/friends and https://wwwsecure.lego.com/en-us/videos are not working examples while https://wwwsecure.lego.com/en-us/products and https://wwwsecure.lego.com/en-us/games do work.

Not sure what should we do regarding that, though. The problem here is if we excluded these directories, people on wwwsecure will still end up with these errors if they clicked on the links. On the other hand, I don't think we should disable the whole rule because it actually works for most of the site.

**Comment by semenko** [comment]
Fixed in above commit.
