### ISSUE TITLE
Intent of 9dcd474d?

### ISSUE THREAD

**Issue by simon04** [EFForg/https-everywhere#287]
What was the intent of the commit 9dcd474d for the `3.5` branch? For instance, this reverted the `OpenStreetMap.xml` file to a very old and outdated version?

**Comment by jsha** [comment]
It's common for submitted rulesets to have bugs or develop bugs that break sites. The stable branch has ~3k rulesets, and the development branch has ~14k rulesets. As I understand it, in April, @diracdeltas wanted to promote the development branch to stable, but was faced with too large a set of likely-broken rulesets. So she forked the development branch onto the 3.5 branch, and then in that branch delete all the rules, then copied in the current rules from the stable branch at that time. That's why you see a large number of deletions in 9dcd474 - those rules existed only on development branch at that time.

Unfortunately, this manual delete-and-copy made the histories of the stable branch and the development branch hard to reconcile, since many rulesets had changes in both branches. In December, I did a massive merge of the current stable branch (4.0) into the current development branch (master): 895e5351f651bfc91ac5490f68deaa93206de3de. In this merge, I reverse the delete-and-copy process, always preferring the copy of the rulesets in master.

You should find that any rulesets that showed up as deleted or reverted in 9dcd474 were restored by 795e535, including OpenStreetMap.

We plan to avoid this issue in the future by making it easier to test rulesets, so we can confidently promote the 5.0 development series to master without having to choose a smaller set of rulesets.
