### ISSUE TITLE
Include securecookie host style in ruleset-style.md

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2907]
Often we want to secure all cookies on all target hosts in a ruleset. As far as I can tell from the code ([relevant Firefox bit](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/code/HTTPSRules.js#L690) and [relevant Chromium bit](https://github.com/EFForg/https-everywhere/blob/master/chromium/rules.js#L308)), one easy way to obtain this is to let <code>host=".+" name=".+"</code>. Currently, most rulesets use long strings of subdomains (a la [this monstrous one](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/KK.dk.xml#L66)) which the new ruleset style explicitly wants to avoid for the actual rules.

Thus, for consistency, and if it is indeed possible, the ruleset style should probably suggest doing it the shorter way for securecookies as well.

**Comment by jsha** [comment]
I agree! Thanks for checking in the code.

**Comment by fuglede** [comment]
I guess this would also follow from #77 if one had some kind of 'complete coverage' attribute for rulesets, specifying that <code>\<securecookie host="." name="." /\></code> and <code>\<rule from="^http:" to="https" \></code> be automatic, so that one only needs to specify target hosts.

**Comment by jeremyn** [comment]
@fuglede In pull request #5639 , @J0WI pointed out to me that a `.+/.+` `securecookie` can cause problems if one of the domains is only partially included. Maybe this is what you meant by requiring a "complete coverage" attribute. I agree that it would be nice if, in the simple cases, a `securecookie` could be automatically applied.

Anyway this is an old issue, can we wrap it up somehow?

**Comment by fuglede** [comment]
Another thing one might need to be aware of is that subdomain-including `securecookie`s will be covered by `.+`, which can become an issue if not all subdomains are securable. I have yet to see an instance of this in the wild though.

In terms of wrapping it up, it would just be a matter of stating something to the extent of "If you are positive that all cookies can be safely secured, use `.+`/`.+`" in the style documentation.

**Comment by jeremyn** [comment]
What's the difference, if any, between my comment [here](https://github.com/EFForg/https-everywhere/pull/6731#issuecomment-244774660) (seen in the wild) and the below?

>Another thing one might need to be aware of is that subdomain-including securecookies will be covered by .+, which can become an issue if not all subdomains are securable.

**Comment by fuglede** [comment]
None, except different domains are involved, so that the issue may be more subtle: Say that a cookie is set on example.com and intended for use on subdomain.example.com. Then we'll cause breakage if the parent domain can be secured but the subdomain can not.

**Comment by jeremyn** [comment]
That's a good point.

> Then we'll cause breakage if the parent domain can be secured but the subdomain can not.

This is potentially extremely common. Any ruleset with "problematic subdomains" is a potential example. Also, even if `example.com` doesn't work, `subdomain1.example.com` [can set a cookie](https://stackoverflow.com/questions/3089199/can-subdomain-example-com-set-a-cookie-that-can-be-read-by-example-com) for `example.com` that is intended to be read on `subdomain2.example.com`.

Basically this means `.+`/`.+` cookies should never be used, and instead we should only specify subdomains. What do you think?

**Comment by fuglede** [comment]
Well, they can be used when all subdomains can be secured, which we do have examples of. They can also be used whenever we can ensure that they are not actually used on the non-securable subdomains (and in fact, that's one of the cases where the `securecookie` really shines, since they would otherwise be interceptable in that case).

**Comment by jeremyn** [comment]
We can never be sure all subdomains are securable, because we might not able to access them or even know about them. In issue #4910 for example the user reports a redirect loop after logging in on a subdomain that doesn't even exist in public DNS. In fact based on this discussion, that user's problem is probably caused by a [very general host attribute](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/SAS_Institute.xml#L48) in the `securecookie` tag in `SAS_Institute.xml`.

**Comment by fuglede** [comment]
We can't, but you could use the same logic to say that since we can not be sure that all subdomains of subdomains are securable, we should also not include `securecookie`s for the first level subdomains.

**Comment by jeremyn** [comment]
That's also a good point.

Honestly I think the `securecookie` stuff is confusing and I'm tempted to get rid of it entirely, or at least never encourage its use.

**Comment by fuglede** [comment]
They certainly require an extra level of attention to things that can go wrong. I never used them much myself for the same reason, but they do have legitimate use cases (such as the one from four comments above -- others can probably come up with better ones), where they can potentially prevent session hijacking. In reviewing, I'll generally take the more pragmatic approach of "it looks like this is very unlikely to cause issues (even in the potential event of unforeseen subdomains), so let's let it through" -- even if a ruleset takes all possible precautions, it can still run into issues down the line when webmasters change stuff, so we'll have to do with some level of pragmaticalness in any case.

**Comment by jeremyn** [comment]
This whole discussion is similar to the mixed content discussion in #6629 except that here we have even less ability to make judgment calls because maybe:

1. we need an account to generate a login cookie, or
2. the cookie is encrypted at rest or signed and thus safe to transfer over HTTP, or
3. the [heuristic checking](https://github.com/EFForg/https-everywhere/blob/5f907648a5e51d169b358fd5f91a88cad03c59ed/chromium/rules.js#L344-L354) that HTTPS Everywhere does will prevent a problem from happening

Also it's just harder to see what's going on with cookies. With the URL protocol (HTTP/HTTPS) you can just look at the address bar, but to check cookies in Firefox you have to either dig into an option submenu or enable a special devtools panel. So I think any casual contributor will not be confident enough to be `positive that all cookies can be safely secured`.

So my opinion is that

1. `securecookie` tags should only be used in targeted situations where we are trying to fix a identified vulnerability, instead of used as a default catch-all, but
2. we don't need to make special efforts to remove existing `securecookie`s, and
3. casual contributors should not be encouraged to create them.

What do you think? Also pinging @J0WI so they can participate.

**Comment by J0WI** [comment]
To be honest I don't really care about the `securecookie` rule.
1. If a site is secured, we don't allow insecure requests anyway
2. in most cases, users are not aware of cookies, Tor don't even accept them (depending on security preferences)
3. session hijacking is only possible if a user uses session cookies, means using an account there. Of course you can still hijack cookies to track the user, but I think there are easier possibilities to do this.

If a we have an unsecured login cookie that can be secured go for it, but we should not require it, since it's hard to test.

**Comment by jsha** [comment]
> If a site is secured, we don't allow insecure requests anyway

Keep in mind that it's very common for cookies to be sent to a domain and its subdomains. It's possible for a network attacker to trigger an HTTP request to `nonexistent.example.com`, which may send cookies.

That said, the original purpose of `securecookie` rules was to support sites that had logins, but would set HTTP cookies and have you logged in on the HTTP site. I think that's getting a lot less common now. There's a secondary purpose, to avoid leakage of tracking cookies that a network attacker could use to target you, but since our coverage there will always be dismal, I don't think we should consider that part of our threat model. Privacy Badger is better positioned to stop tracking cookies.

**Comment by fuglede** [comment]
Added a change to the documentation in #6845, which, if nothing else, at least makes it clearer what preliminaries to consider when using the wildcard `securecookie`.

**Comment by jeremyn** [comment]
To anyone using this thread as a reference: https://github.com/EFForg/https-everywhere/pull/7527#issuecomment-262405979 might help explain the problem with using `.+/.+` `securecookie` tags.
