### ISSUE TITLE
HTTPS Everywhere breaks videos on Maker.tv

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2937]
HTTPS Everywhere breaks videos on Maker.tv. I have been unable to figure out which rulesets are breaking the videos.
Sample: http://www.maker.tv/originals/erb/video/iUr0T9ZuVUSy/playlist/epicrapbattlesofhistory

**Comment by numismatika** [comment]
I assume JWPlatform, since it would be trying to load content between http and https sites.
Rewriting maker.tv to tls isn't fixing it either, because makerplayer.com is using an invalid certificate.

How about asking the site owner to serve TLS on all their domains including makerplayer and makerstudios.com?

**Comment by pipboy96** [comment]
The URL in question no longer works, verification is impossible. Issue first reported in 2015, no follow-up since.
