### ISSUE TITLE
[ruleset-bug] SPIEGEL Online "Liveticker" prevented from loading

### ISSUE THREAD

**Issue by Wikinaut** [EFForg/https-everywhere#3201]
Current ruleset prevents the loading of the so-called "Liveticker" (mixed-mode issue may also be present) on this page (spinner shown, content not loaded)

http://www.spiegel.de/politik/ausland/paris-liveticker-mehrere-tote-bei-schiessereien-geiselnahme-explosion-a-1062784.html

**Comment by jeremyn** [comment]
Thanks for the report. The given URL [does not trigger Spiegel.xml](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Spiegel.xml#L91) since at least 4ad2e53f3819d01fbb33f2f05f4e2a032359ee21, which is a little strange because that commit was before you reported this issue. In any case when I visit that URL, the Liveticker looks okay to me.

I'm closing this issue, but please feel free to reopen it with a comment if this is still a problem for you.
