### ISSUE TITLE
feedproxy.google.com is http

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#3275]
Steps to reproduce:
1. set `Block all HTTP requests` in https-everywhere
2. open: https://feeds.feedburner.com/arstechnica/vnzV
3.a. left click any of the links (nothing happens because it tries to go http instead of https)
3.b. right click a title link and choose `Open Link in New Tab` - you see the http link in the new tab eg. `feedproxy.google.com/~r/arstechnica/vnzV/~3/8JSrSrCjNGA/` (eg. http not https)

But looks like there are rules for `feedproxy.google.com' as seen here: https://www.eff.org/https-everywhere/atlas/domains/google.com.html

I'm not sure but it seems that this would leak some(or all) of the google.com cookies (from what I can tell from uMatrix) - or maybe not the important ones (assuming they are marked to send only for secure connections only)

**EDIT:** forgot the important stuff:
firefox 42.0 dev. edition on gentoo linux
https-everywhere 600bb08baf379208b388d11412d4f04089177596

**Comment by zazdxscf** [comment]
The weird thing is, I guess, that if I just go `feedproxy.google.com` instead of `feedproxy.google.com/~r/arstechnica/vnzV/~3/8JSrSrCjNGA/`  it does go https by redirecting to `https://accounts.google.com` ...   so this maybe tells me that because the target is http(on the latter link), that's why it doesn't go `https` at all (maybe it does some form of redirect - that I don't understand)

**Comment by pipboy96** [comment]
@ghost, opened in 2015, no further comments, can't verify the issue. closing. If you believe this is a mistake, contact me.
