### ISSUE TITLE
Firefox for todoist bug

### ISSUE THREAD

**Issue by PaBLoX-CL** [EFForg/https-everywhere#3299]
I can't load the firefox extension using https everywhere:

```
Found

<p>You should be redirected automatically to target URL:</p><p><a href="https://firefox.todoist.com/app?lang=en&amp;mini=1&amp;v=717">https://firefox.todoist.com/app?lang=en&amp;mini=1&amp;v=717</a>. If not click the link.</p>
```

My guess is because the ruleset doesn't include `*firefox.todoist.com`.

**Comment by J0WI** [comment]
Can you post an url?

**Comment by vlad003** [comment]
I can confirm this bug. If I disable HTTPS Everywhere, the Todoist extension works fine. I get that same message when HTTPS Everywhere is enabled.

**Comment by J0WI** [comment]
Ah, so it's not about the site itself, but the Todoist Add-On is broken if both are installed?

**Comment by vlad003** [comment]
Site works fine. But now it looks like the addon works fine, too.

It didn't work for a while, but then I saw this issue so I disabled HTTPS Everywhere, and then the addon started working again. It continues working even with HTTPS Everywhere enabled.

The addon is just a panel which loads https://firefox.todoist.com/app, and it hasn't been updated since last November.

**Comment by J0WI** [comment]
Okay, thank you!

**Comment by iamarcel** [comment]
This seems to be a problem again!

If I disable HTTPS Everywhere (restarting Firefox), the popup opens without any problems. 
After enabling HTTPS Everywhere again it *still* works though, until I log out.

**Comment by jeremyn** [comment]
We've removed the Todoist rule (see pull request #7004 ) because `todoist.com` with subdomains are now [HSTS preloaded](https://hstspreload.appspot.com/), so the HTTPS Everywhere functionality is redundant. This should take effect with the next HTTPS Everywhere release.

So, I'm closing this issue, but please feel free to reopen with a comment if the problem persists after the next release.
