### ISSUE TITLE
Lynda.com login page

### ISSUE THREAD

**Issue by kylerphillips** [EFForg/https-everywhere#3607]
Having trouble using HTTPS Everywhere with [Lynda.com](http://lynda.com "Lynda") login page (see attached screenshot)

<img width="1245" alt="screen shot 2015-12-24 at 02 01 55" src="https://cloud.githubusercontent.com/assets/9768489/11988118/6b4743c8-a9e2-11e5-9cec-08e42f3d5e3e.png">

**Comment by bkimmett** [comment]
This is due to the fact that the site is normally unencrypted by default, and making only the login page encrypted trips a security policy:
"Load denied by X-Frame-Options: https://www.lynda.com/user/login/modal does not permit cross-origin framing." (from http://www.lynda.com, presumably)

I imagine this could be fixed by making the Lynda.com homepage covered under the relevant HTTPS-Everywhere rule.

**Comment by funkydude** [comment]
@J0WI This can be closed, resolved.
