### ISSUE TITLE
Add Xirkle

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#3640]
[Xirkle](https://www.xirkle.com/) is a privacy oriented search engine that doesn't track its users and there is currently no ruleset for this domain.

**Comment by semenko** [comment]
Thanks for the suggestions! I've closed some of your submissions, since we don't currently have the resources to add new rule site-by-site (and lots of sites use HTTPs!).

If you would like to see this site in HTTPS Everywhere, please submit a pull request with a new ruleset: https://www.eff.org/https-everywhere/rulesets
