### ISSUE TITLE
icon color doesn't change if HTTPS-E is enabled/disabled via about:config

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#378]
because the code that changes the icon color listens for clicks on "Enable/Disable rules" in the HTTPS Everywhere popup menu, not the `globalEnable` preference change directly.

**Comment by jeremyn** [comment]
@diracdeltas With HTTPS Everywhere enabled, if I have one tab open to an active HTTPS page like https://www.eff.org/ , then when I'm looking at that tab the icon is dark blue. If I open `about:config` in another tab, the icon is gray blue when I'm on that tab because there is no ruleset for `about:config`. If I change `extensions.https_everywhere.globalEnabled` to `false`, then while I'm still on the `about:config` tab the icon is still gray blue. If I switch to the eff.org tab, the icon changes to gray, and if I switch back to the `about:config` tab, the icon is still gray.

Does this mean this issue is resolved? I can't tell if you meant that you wanted the icon on the `about:config` tab to change from gray blue to gray immediately.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
