### ISSUE TITLE
Stack Exchange (partial) breaks Firefox Web Sockets to qa.sockets.stackexchange.com

### ISSUE THREAD

**Issue by AlexanderOMara** [EFForg/https-everywhere#3884]
Basically all the web-socket related features like live updates are broken on Stack Exchange websites when "Stack Exchange (partial)" is enabled, and the following appears in the Firefox console:

> Firefox can't establish a connection to the server at wss://qa.sockets.stackexchange.com/.

Disabling "Stack Exchange (partial)" makes it work again, at the expense of not having `http` rewritten to `https`. I've checked, and the web sockets do behave the same using `http` or `https` URL's with the rule disabled.

You have to be logged in to see this issue. Then just visit any question [like this one](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454) and see the error in the console.

I've also looked over [the rules](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Stack-Exchange.xml), but nothing jumps out as being the issue.

**Comment by vyznev** [comment]
It looks like the downgrade rule is matching the websocket host qa.sockets.stackexchange.com, causing the websocket connection to be incorrectly downgraded.  Changing the downgrade rule to something more specific, like, say:

    <rule from="^https://meta\.([\w-]+)\.stackexchange\.com/" to="http://meta.$1.stackexchange.com/" downgrade="1" />

should fix this.  Alternatively, if there's some way to configure an exception so that only qa.sockets.stackexchange.com (or maybe *.sockets.stackexchange.com) is not downgraded, that should work too.

**Comment by AlexanderOMara** [comment]
@vyznev There are exclusions documented here:

https://www.eff.org/https-everywhere/rulesets#exclusions

I would try it out, but I was never able to figure out why it was failing to test from source last I tried.

**Comment by braiam** [comment]
Adding

    <exclusion pattern="^https://qa\.sockets\.stackexchange\.com/" />

should be good enough. I spent half an hour figuring out why where <test> ignored, until I presumed that they are ignored because the exclusion, but this is not said anywhere:

> Exclusions are always evaluated before rules in a given ruleset. Matching any exclusion means that a URL **won't match any rules within the same ruleset**. However, if other rulesets match the same target hosts, the rules in those rulesets will still be tried.

But when I removed the <test>, then this error appeared:

    ERROR rules/Stack-Exchange.xml: Not enough tests (0 vs 1) for <Exclusion pattern '^https://qa\.sockets\.stackexchange\.com/'>

If you add an exclude rule without test, it will complain, but if you do it won't inform you!

I'm poring style guidelines to see where should I include the exclusion and test rules.
