### ISSUE TITLE
Review Internet-Society

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#4035]
Is the [Internet-Society ruleset](https://github.com/EFForg/https-everywhere/blob/d1f8c60458fe05e95df71ce451cecaf0f5de5b9b/src/chrome/content/rules/Internet-Society.xml) still up-to-date?

There are many exclusions, but when I tried to access some exclusions over HTTPS, they all worked. So possibly this ruleset can be simplified.

/cc @internetsociety

**Comment by bgkonzman** [comment]
I've got a patch to simplify this in progress.

The site seems to be down to 5 specific pages that explicitly redirect to http. I've cut the exclusion and tests down to those 5.

In the process, I discovered a couple of pages where mixed content will disable part of the page, e.g., https://www.internetsociety.org/publications/global-internet-report. They're already broken with the current ruleset. What's SOP here?

I also came across a new subdomain, which I can add: wp.internetsociety.org. Mixed content warning there, too, though.

Any guidance appreciated.

**Comment by jeremyn** [comment]
@bgkonzman Issue #6629 has a recent discussion on mixed content. Also see [here](https://www.eff.org/https-everywhere/rulesets#mixed-content).

What to do depends on the page and the overall ruleset. For the specific example of https://www.internetsociety.org/publications/global-internet-report , an important part of the page is broken because of blocked mixed content, so however you handle it, that page should not be active by default unless you have `platform="mixedcontent"` and are on a `mixedcontent` platform such as the Tor Browser.

**Comment by rugk** [comment]
Any news here?

**Comment by jeremyn** [comment]
@rugk I'm not sure who you're asking. From my side, you or anyone is welcome to submit a pull request updating the ruleset and reference this issue.

**Comment by bgkonzman** [comment]
@rugk I blew away the machine with this patch ages ago and am not likely to pick it up again anytime soon. Anybody who wants to contribute should consider the bug wide open.
