### ISSUE TITLE
HTTPS Everywhere is broken on Firefox Developer Edition

### ISSUE THREAD

**Issue by vgturtle127** [EFForg/https-everywhere#4195]
I am using 64-bit Firefox Developer Edition 46.0a2 (2016-02-20).

I installed HTTPS Everywhere from AMO, not EFF.org.

I have version 5.1.3.

The SSL Observatory option doesn't work in the toolbar icon, and neither does the about option. On top of that, all of the settings in the observatory (accessed through the about:addons menu) are broken and don't work.

Is this related to changes in how Firefox handles addons, or is this a bug?

If anybody can help me confirm I am not the only one having these issues, that would be great.

Feedback appreciated.

**Comment by zymase** [comment]
Broken, on Firefox stable release as well (44.0.2).
A few days ago someone mentioned problems, mainly user rulesets not being effective. Someone acknowledged (sorry, I don't know who's who around here), mentioned it was reproducible and that he had found the culprit, and then the issue was removed.

The issue being removed here I concluded that an update to 5.1.3 (for Firefox at least) would be available : nothing. As I always saw it at Github an issue is removed once the update is available (or of course if the issue is considered nonsense).

HTTPS Everywhere 5.1.3, be it at EFF's or at AMO has't changed, which means users are proposed an application which is faulty, which has an issue acknowledged here, and no one knows what is going on.

All I can observe is a flagrant gap between the seriousness of incentives to adopt HTTPS Everywhere and what seems to be a rather mystery when it comes to tha application having problems.

What is the problem with EFF concerning its HTTPS Everywhere? is the application starting a decent to abandon, is EFF's mind and strategy elsewhere? I mean : what's going on?

**Comment by vgturtle127** [comment]
@zymase I seem to be having many of those issues as well, but maybe they are preparing a WebExtensions port to alleviate some of the problems? I would work on the port if I knew what exactly needed to be done and what is possible. I assume they want it done a specific way, though.

**Comment by zymase** [comment]
@vgturtle127 whatever is being prepared why is there no communication? I'm not annoyed by a bug, I'm annoyed by the fact nothing is being told, especially here. Otherwise, I'm a simple user, I have no idea of the reasons of the bug (related to JSON format which replaced SQLITE?) and I'd just like to run HTTPS Everywhere normally or at least know why it's problematic (5.1.3), what's being done and planned. What's so complicated with that?

**Comment by Hainish** [comment]
Thanks for the report @vgturtle127, I can reproduce this issue.  Looking into it now

**Comment by Hainish** [comment]
@zymase a new release is forthcoming, we want to make sure to fix all issues with the current release before deploying a new one.

**Comment by vgturtle127** [comment]
@Hainish Thank you for responding, I mostly get no response when I open issues.

Thanks for the info about the new release, as well.

**Comment by zymase** [comment]
@Hainish OK- Thanks for the information, that's all I -- and perhaps others -- wanted to know. Now, if a user on HTTPS Everywhere 5.1.3, encountering problems comes here to know what's going on, he'll have this information available. I know that when a problem is handled it may seem so obvious that not worth being mentioned, on another hand users don't yet read in the minds of developers.

**Comment by vgturtle127** [comment]
@Hainish Thanks!

Did you see #4194 ? This may help with getting a WebExtensions port going, now that I think about it.

**Comment by zymase** [comment]
There you go again, closing an issue when a new version of HTTPS Everywhere including the resolved issue is not available:

On AMO - Version 5.1.3 Released February 19, 2016 2.3 MB 
On EFF - Version 5.1.3 Last-Modified: Fri, 19 Feb 2016 02:16:50 GMT

Why are you removing this issue since there is NO update available, since 5.1.3 is buggy?
What is your problem?

**Comment by vgturtle127** [comment]
@zymase It has been committed to the repository, so closing it does make sense in regards to the issue being fixed.

Now we just have to wait for them to release the next build, they have stated they want to fix as many bugs in the next release as possible. I assume they are trying to go through the many issues in the GitHub repo, which is quite daunting at the moment.
