### ISSUE TITLE
Videos won't load on TeamFourStar.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4216]
http://teamfourstar.com/video/dragonball-z-abridged-episode-52-flashpoint/

An error message comes up on videos unless the rule Longtail (partial) is disabled.

**Comment by dddux** [comment]
Just to say that I also noticed a fortnight ago that some videos just stopped playing on some websites like Vodlocker, for example. It took me a while to find out which add-on is causing this and I was quite surprised to find out that HTTPS Everywhere is the problem. So I had to disable it until the issue is solved.
