### ISSUE TITLE
Add shoutwiki.com

### ISSUE THREAD

**Issue by davidabian** [EFForg/https-everywhere#4378]
Please add the website shoutwiki.com and all subdomains, which support HTTPS.

**Comment by molex** [comment]
I checked multiple sub domains on this one and the only one that actually has a working certificate is
the [blog](https://blog.shoutwiki.com/) and it hasn't been updated since July of 2017. Other related issues have been closed. I suggest we close this one as well. See [issue #4464](https://github.com/EFForg/https-everywhere/pull/4464)

**Comment by pipboy96** [comment]
Closed by #17681.
