### ISSUE TITLE
Subscription-based definition (like ABP)

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#4380]
Current:
In order to use updated http-rules, you must update the add-on itself.
If you don't update it, you will use old, outdated rules.

Idea:
HTTPSE is just an add-on, and fetch https://s.eff.org/definition/httpsrules.xml regulary.
In this way, user don't have to update their add-on.
Old, outdated rules will be removed automatically.

Security:
To counter DNS-hijack, new HTTPSE must verify EFF's certificate/hash before accepting a new ruleset.

**Comment by espress0** [comment]
With my idea, the user who have time can make their own ruleset.

1. New user create his own rulesets(like ABP subscription).
2. Upload to his webapge: http://test.test/https.xml
3. Other user 'subscribe' the list.

Benefit:
1. EFForg can focus on other thing.
2. These people(shown below) will become happy because "No.1" done it for them.

---
 Add shoutwiki.com
#4378 opened Mar 15, 2016 by davidabian
0
Add sabemosdigital.com
#4376 opened Mar 15, 2016 by davidabian
0
Add vozpopuli.com
#4375 opened Mar 15, 2016 by davidabian
0
Add three Spanish universities
#4374 opened Mar 15, 2016 by davidabian
0
Add three Wikimedia sites
#4373 opened Mar 15, 2016 by davidabian

**Comment by pipboy96** [comment]
Closed by custom update channels.
