### ISSUE TITLE
Add multiple adult sites

### ISSUE THREAD

**Issue by githubuseraccount321** [EFForg/https-everywhere#4843]
Please can you add the following adult sites. Obviously SSL is very useful here as it prevents blackmail and/or dangers to individuals in many non-western countries.

Even if most domains redirect to HTTP after a successful HTTPS connection, the user will be able to detect active man-in-the-middle attacks when first loading the site due to the SSL error thrown when the site the user is redirected to can't provide a valid cert.

Due to the general low quality of SSL implementations across adult sites, I've limited the list to sites that pass SSL Labs tests (grades shown next to domains) without throwing any errors which prevent page-loads. I would suggest carrying out "user testing" before deploying these rules :)

youjizz.com C
www.youjizz.com C
m.youjizz.com C
mobile.youjizz.com C

kink.com A
www.kink.com A
cdn.kink.com B
cdnp.kink.com B
content.kink.com B
forum.kink.com A

pornhub.com B
www.pornhub.com B
de.pornhub.com B
es.pornhub.com B
fr.pornhub.com B
it.pornhub.com B
jp.pornhub.com B
pl.pornhub.com B
pt.pornhub.com B
rt.pornhub.com B
ru.pornhub.com B

youporn.com C
www.youporn.com C
mobile.youporn.com C
br.youporn.com C
de.youporn.com C
es.youporn.com C
fr.youporn.com C
it.youporn.com C
jp.youporn.com C
nl.youporn.com C
pl.youporn.com C
ru.youporn.com C

xhamster.com B
m.xhamster.com B
partners.xhamster.com F
de.xhamster.com B
es.xhamster.com B
fr.xhamster.com B
it.xhamster.com B
ja.xhamster.com B
jp.xhamster.com B
nl.xhamster.com B
pl.xhamster.com B
pt.xhamster.com B
ru.xhamster.com B

**Comment by Bisaloo** [comment]
I don't really support the idea of adding rules for websites that redirect https->http.

It will have a performance cost and provide absolutely no privacy protection. You mention MITM protection but I fail to see a threat model where MITM on "adult sites" leaks more info than simple eavesdropping. 

They MITM you, great!, then what? They know which page you're visiting (since you are mentioning blackmail)? They do even with those rules because you're browsing http.

**Comment by J0WI** [comment]
You may go through common lists like `urlblacklist.com` to find even more.
