### ISSUE TITLE
costco.com broken with https everywhere 

### ISSUE THREAD

**Issue by zeugmatis** [EFForg/https-everywhere#5377]
Cotsco is one of the biggest retailers in the US: http://www.costco.com ...when viewing images of products with https everywhere enabled, viewing product images by clicking the plus sign in the lower left corner of the main image brings up an applet that goes blank and cannot click any other images or even the "x" in the upper left to close the pop-up window - effectively breaking the site.

**Comment by zeugmatis** [comment]
BTW tested in recent versions of Chrome and Firefox (both recent stable and nightly) on OSX El Capitan.

**Comment by tomwys** [comment]
I got "Access Denied" when clicking that link. Is this only me, or website is completely broken?

**Comment by zeugmatis** [comment]
Please copy/paste the URL?  As opposed to generating randomness, how about fixing the bug?

**Comment by zeugmatis** [comment]
I'm figuring the website is broken - I did let Costco know as well.  Such a large US company though, they did not respond.

**Comment by jeremyn** [comment]
FYI, I can specifically reproduce the problem by going here:

http://www.costco.com/Costco-Cash-Card.product.10024438.html

clicking the magnifying glass in the lower right part of the picture, below the card, and observing that clicking the X in the top right of the interstitial that appears does nothing other than throw messages to the JavaScript console. Turning off the [Costco-static.com ruleset](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Costco-static.com.xml) fixes the problem.

@fuglede @J0WI What's the fix here? Just disable the static ruleset entirely?

**Comment by fuglede** [comment]
@jeremyn: I can not actually reproduce the issue as described in your comment: indeed I can not close the bigger version of the image, but disabling the ruleset (or HTTPS Everywhere in its entirety for that matter) does not appear to be sufficient to fix the faulty behaviour. I have not looked into it in any greater detail than that, but this also means that I can not quite tell what causes the issue right here and now. In general, the proper fix will depend on how you want to prioritize security versus breakage: it would be nice to pin down the issue exactly, for example to a specific static serving folder which you could then exclude, but often that can be rather involved, and if noone is around to do the job, and if the issue is likely to affect a lot of users (as in this case), it might very well be preferable to simply disable the ruleset. Different people will have different opinions, and I don't think anything has been written down on the matter, but my impression is that most of us prefer to avoid the usability issues even if it costs a bit of security somewhere else.

**Comment by zeugmatis** [comment]
I just tested and same - disabling the [Costco-static.com ruleset](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Costco-static.com.xml) also made it work for me.  Costco being as big a company as it is, highly doubtful we can get them to make any changes on their side unfortunately.

**Comment by jeremyn** [comment]
I've reproduced the problem with Firefox 48.0.1 on Windows. It looks like the popup uses Flash so that should be enabled before trying this.

When I click the first magnifying glass to open the popup, the developer tools console reports:

```
[imageFlexZoom] - calling loadXML: http://images.costco-static.com/image/media/10024438-847__1_z/zoom.info.js rfxloader:2421:9
[imageFlexZoom] - Adding flex viewer: 10024438-847__1_z rfxloader:2421:9
```

When I click the X to try to shut the popup down, the console reports

```
TypeError: document.getElementById(...).originalSize is not a function embed_costco.js:268:2
```

I tried adding `<exclusion pattern="^http://images\.costco-static\.com/image/media/10024438-847__1_z/zoom\.info\.js$" />` to see if that helps, but it doesn't. Maybe some http URL is hardcoded in some Flash application.

Anyway I don't know. My recommendation is to disable the ruleset by default by adding `default_off="https://github.com/EFForg/https-everywhere/issues/5377"` to the ruleset tag. What do you two think?

**Comment by fuglede** [comment]
The lack of Flash here could explain why the page did not respond at all, I guess, although I did see the same errors as you in the console, even without HTTPS Everywhere. I wanted to test with Flash as well, but it looks like their site is down right now.

In any case, if you do not see a straightforward fix, then disabling it might be better than the status quo indeed. Another possibility that I've applied a couple of times is to add an exclusion for all URLs ending with `.js`. Of course the active content is what we would want to secure the most, so depending on how you look at it, this is not a huge improvement over disabling it completely.

**Comment by jeremyn** [comment]
I'm not planning to dig into this more myself anytime soon.

@zeugmatis @tomwys If one of you could submit a pull request either [disabling this ruleset entirely](https://github.com/EFForg/https-everywhere/issues/5377#issuecomment-241231004), or [adding a targeted exclusion](https://github.com/EFForg/https-everywhere/issues/5377#issuecomment-241246750) to fix the problem, that would be great. Please refer to this issue in that pull request and I'll review it.

**Comment by zeugmatis** [comment]
I'm super busy too, but if this sits here for a month (or three :-)) and is still open then I'll look into further and submit a PR.

**Comment by pipboy96** [comment]
Can't reproduce, website seems to be changed.
