### ISSUE TITLE
Unable to right-click zip repository on Windows because of characters in filenames

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#5613]
Filenames in the HTTPS Everywhere repository containing certain characters cause problems when using the "Send to > Compressed (zipped) folder" feature in Windows 10 when the system locale is "English (United States)". The files that cause the problem are:
- `cert-validity\mozilla\builtin-certs\NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt`
- `test\rules\platform_certs\cacert\Cert-010_EBG Elektronik Sertifika Hizmet Sağlayıcısı_EBG Bilişim Teknolojileri ve Hizmetleri A.Ş.pem`
- `test\rules\platform_certs\cacert\Cert-126_NetLock Arany (Class Gold) Főtanúsítvány_NetLock Kft.pem`

Please consider renaming these files, wrapping them in other files, or something like that.
##### Workaround attempts
- If I change the system locale through "Control Panel > Clock, Language, and Region > Region > Administrative > Change system locale..." to "Hungarian (Hungary)", the first and third files work but the second still causes an error. If I change the system locale to "Turkish (Turkey)", the second works and first and third still cause errors.
- The [Compress-Archive](https://technet.microsoft.com/en-us/library/dn841358.aspx) PowerShell cmdlet compresses the file without error, but unfortunately it [quietly excludes hidden folders](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/14754069-compress-archive-does-not-include-hidden-files-fol) like the `.git` folders.
##### How to reproduce the error
1. Download the zip file for commit 09414188005c2819691953daf2505d9ef92c9caf from GitHub
2. Unzip the file.
3. Right click the `https-everywhere-master` directory and select "Send to > Compressed (zipped) folder".
4. Observe the error: "[filename] cannot be compressed because it includes characters that cannot be used in a compressed folder, such as [character]. You should rename this file or directory."

**Comment by jeremyn** [comment]
@Hainish Is there any reasonable chance we would rename or wrap the certificate files I named above to prevent this problem?

**Comment by Hainish** [comment]
Renaming them shouldn't pose any problem AFAIK.

I wonder if we even need the `cert-validity` top-level path for anything?  I don't see it referenced anywhere.  @jsha, do you know what this path is for?  Is it still being used?

**Comment by jsha** [comment]
Let's delete that dir. AFAIK not used for anything.

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/pull/6807 removes `cert-validity`

**Comment by jeremyn** [comment]
Update: I still get this error as of https://github.com/EFForg/https-everywhere/commit/368b8da10e7a44ae3fe944cf473d4e9d002ebdfb.

**Comment by jeremyn** [comment]
I'm closing this issue with these observations:

The direct problem was caused by the inability of the Windows "Send to > Compressed (zipped) folder" feature to support certain characters based on the system locale. Of course we can't fix problems with Windows features. I also don't think we should, for example, "ASCII-ify" filenames just to accommodate a Windows limitation. So, this problem may not be permanently solvable by us.

Problematic filenames can be found using the instructions at https://unix.stackexchange.com/a/109753. The current filenames with non-printable ASCII characters as of 229efbbb6bb9df2c42c0ac60788187c6f81005ff are all under `test/rules/platform_certs/`.

We should consider not including certificate files in the repository, for maintenance and security reasons. `test/rules/platform_certs/chromium/` and `test/rules/platform_certs/firefox/` both symlink to `test/rules/platform_certs/default/`. We could change this symlink to point to, for example, `/usr/share/ca-certificates/mozilla/` where Mozilla puts its certificates on Ubuntu 16.04, or otherwise adjust where the checker finds the certificates. This however ties into issue https://github.com/EFForg/https-everywhere/issues/13815 "Which developer operating systems do we support?".

I'm not sure how, or even if, the CAcert certificates at `test/rules/platform_certs/cacert/` are used anywhere. Maybe these can be removed entirely

**Comment by Hainish** [comment]
@jeremyn I looked into this some today.  On Debian 8, my local fetch tests were failing and I was wondering why this was only happening on my host and not on the `httpse` docker image.

It turns out that in the later version of `curl` or `pycurl` that we're using in docker passes both `/etc/ssl/certs/ca-certificates.crt` as the `CAfile` and `test/rules/platform_certs/<platform>` as the `CApath`.  This seems not to be the case on my host setup.  So as those old certs in `test/rules/platform_certs/` age, we're increasingly relying on `/etc/ssl/certs/ca-certificates.crt` (which comes from `ca-certificates`) for validity.

We should either
1. upgrade the certs for the Chrome, Firefox platforms, or
2. Simply use the OS-level certificate store

Option (1) is the more accurate way to determine which URLs will fail for the browsers we support, but it also will require ongoing maintenance as you mentioned.  Seems like we can continue for the time being with our mixed approach, all the while being aware that we're increasingly relying on the OS-level store.

**Comment by jeremyn** [comment]
We should use either the system stuff or our own, not both. Using both is arguably a bug in any case.

It [looks like](https://www.chromium.org/Home/chromium-security/root-ca-policy) Firefox uses its own certificates but Chrome uses the OS certificates on Windows, macOS, and Android, and Mozilla's certificates on Linux. On Ubuntu at least, the files in `/etc/ssl/certs/` are mostly symlinks to Mozilla's collection at `/usr/share/ca-certificates/mozilla/`. `/etc/ssl/certs/ca-certificates.crt` appears to be a single file generated by [`update-ca-certificates`](http://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html) which is part of the `ca-certificates` package. I don't know where `ca-certificates` fits into things: it's not a dependency of either `firefox` or `curl` on Ubuntu.

I assume our included certificates are taken from Mozilla's Linux collection. This can at best only roughly track what, for example, Chrome/Windows users are validating against, since those users are using the Windows certificate store. (I assume Chrome/Windows has our biggest single userbase.)

Probably the most correct thing to do is to use the [NSS library](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS), like Chrome does, to validate certificates. It looks like `curl` has some way of doing that, see https://curl.haxx.se/docs/sslcerts.html "Certificate Verification with NSS".

**Comment by Hainish** [comment]
> We should use either the system stuff or our own, not both. Using both is arguably a bug in any case.

This is essentially my suggestion above.  We've been using the mixed approach for a long while, and as time goes on and the `platform_certs` become outdated, we naturally gravitate towards option (2) for builds on newer distributions.

> It [looks like](https://www.chromium.org/Home/chromium-security/root-ca-policy) Firefox uses its own certificates but Chrome uses the OS certificates on Windows, macOS, and Android, and Mozilla's certificates on Linux. On Ubuntu at least, the files in `/etc/ssl/certs/` are mostly symlinks to Mozilla's collection at `/usr/share/ca-certificates/mozilla/`. `/etc/ssl/certs/ca-certificates.crt` appears to be a single file generated by [`update-ca-certificates`](http://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html) which is part of the `ca-certificates` package. I don't know where `ca-certificates` fits into things: it's not a dependency of either `firefox` or `curl` on Ubuntu.

This is something most people have installed on their system due to their dependency graph.  A lot of applications rely on it, and it seems to be a dependency for `chromium`, which we install at setup time.  When it is available, `curl` uses it as the default store to validate certificates.

> I assume our included certificates are taken from Mozilla's Linux collection. This can at best only roughly track what, for example, Chrome/Windows users are validating against, since those users are using the Windows certificate store. (I assume Chrome/Windows has our biggest single userbase.)
>
> Probably the most correct thing to do is to use the [NSS library](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS), like Chrome does, to validate certificates. It looks like `curl` has some way of doing that, see "Certificate Verification with NSS".

We also have to tell `pycurl` what TLS library to use, as we do here: https://github.com/EFForg/https-everywhere-docker-base/commit/c12c1114e6274d181f7cc034bf4bb0e501b7a337.

https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/ seems to indicate that we can use [this file](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt) to determine the NSS root certificates.  Getting it into a format `curl` can handle is a different story.  https://gist.github.com/jjb/996292 provides some additional context here, including that we can use http://curl.haxx.se/ca/cacert.pem for the root store.

In 9e48776a5a07baf069e4a9da9a265a852e6b4a70, we remove the NSS ciphers from the list of supported ciphers, due to removing Fedora support.  Fedora `curl` depends on `libcurl` with NSS support OOTB.  Debian `curl` depends on `libcurl` with GnuTLS, which we've switched to OpenSSL.

**Comment by Hainish** [comment]
> This is essentially my suggestion above.  We've been using the mixed approach for a long while, and as time goes on and the `platform_certs` become outdated, we naturally gravitate towards option (2) for builds on newer distributions.

I'm not saying this is desirable, this is just the fact.  We should make an explicit change to either option I specified.

**Comment by jeremyn** [comment]
It might be worth recompiling `libcurl` to use NSS if it means we can otherwise avoid including certificates directly in the repository, but otherwise we seem stuck. 

For getting the certificates into the right format, can't we just point `curl` at `/usr/share/ca-certificates/mozilla/` instead of the `platform_certs/default/` directory we include?

We could also consider including the `cacert.pem` you linked -- or one we build ourselves -- in the repository, instead of a bunch of files. That would address the trivial problem of zipping the repository on Windows, at least.

**Comment by Hainish** [comment]
@jeremyn

> It might be worth recompiling `libcurl` to use NSS if it means we can otherwise avoid including certificates directly in the repository, but otherwise we seem stuck.

No recompile is necessary for `libcurl` - on most debian-based distributions, there are several packages available for `libcurl` with differing underlying TLS libraries.  For instance, on `artful`:  `libcurl4-gnutls-dev`, `libcurl4-nss-dev`, `libcurl4-openssl-dev`.  The only recompilation has to happen on `pycurl`, specifying which `libcurl` library to use.

> We could also consider including the `cacert.pem` you linked -- or one we build ourselves -- in the repository, instead of a bunch of files. That would address the trivial problem of zipping the repository on Windows, at least.

I think this is the most sensible way forward.  In a perfect world, we'd want to use the intersection of root certificates from all supported browsers on all supported OSes: the Microsoft, Apple, Mozilla internal and NSS certs.  This would avoid false positives (URLs from domains which are signed from a root only contained in one root store).   This seems like a maintainership nightmare though, and picking one reasonable library likely suffices.
