### ISSUE TITLE
How to handle sites broken by CDN rules

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#5631]
Some rules breaks third party sites, see e.g. #4510 or #4545.
I'm not happy with the idea of disabling such rules completely since many other sites depends on them and are working fine.
How can we handle this growing issue?

@fuglede @Hainish @jsha

**Comment by J0WI** [comment]
In some cases this is related with #49

**Comment by terrorist96** [comment]
The `Google Videos` ruleset was disabled when it was found to be causing problems. Why not disable the rules when they cause problems, and only re-enable them once the problem has been solved? I don't know about you, but I value a site's functionality more than HTTPS for every single possible element.

**Comment by Hainish** [comment]
I'm generally in favor of the approach described by @terrorist96 as well.

With the larger sites, it's likely we can find someone on their security teams that could maintain these rulesets for us, which would probably be a more streamlined process.  Then we could open any issues directly with them, rather than these issues percolating to the major ruleset maintainers.

With the smaller sites with broken rulesets, it won't be a big deal if we disable them completely for a while until someone comes along and fixes them.

**Comment by Hainish** [comment]
Some of this discussion has continued in https://github.com/EFForg/https-everywhere/issues/7338

**Comment by gloomy-ghost** [comment]
#15157 solves a big proportion of issues caused by CDN rules (if not all of them), should this be closed?

**Comment by Hainish** [comment]
@gloomy-ghost yes, thanks.
