### ISSUE TITLE
redirect from http to https

### ISSUE THREAD

**Issue by ploctaux** [EFForg/https-everywhere#5720]
when the "block all HTTP requests" feature is enabled, is it possible to "try" to do a request on https instead of an http request?

for example: I load my website http://philippeloctaux.com with "block all HTTP requests" enabled, is it possible to try to do the same request but on https, instead of just blocking the request and not doing anything else?

**Comment by J0WI** [comment]
It might be a helpful feature in some cases, but not all sites are serving the same content on https or have redirects back to http. So this could end in some unexpected issues.
For your site you can fix this by adding a ruleset or, even better, by implementing [preloaded HSTS](https://hstspreload.appspot.com/).

**Comment by Hainish** [comment]
I agree with @J0WI here - we should not attempt to access an https site unless the https url is entered.  In certain cases different processes may be running on port 80 vs 443, causing unintended consequences.  We should defer to  the browser behavior for unspecified protocols (i.e. just typing 'example.com' rather than 'http://example.com')

**Comment by ploctaux** [comment]
okay!  thanks guys for your feedback!
