### ISSUE TITLE
HP Support 

### ISSUE THREAD

**Issue by Maxxxxxx** [EFForg/https-everywhere#5872]
Driver downloads don't show.
I disabled all of HTTPS to view it.
Of course, the HP website is buggy.

Here:  http://support.hp.com/us-en/drivers/selfservice/hp-officejet-pro-8500-all-in-one-printer-series-a909/3752454/model/3752458#Z7_3054ICK0K8UDA0AQC11TA930C7

Thank you.

**Comment by jeremyn** [comment]
I can download the driver `OJ_AIO_P8500_A909_Full_Win_WW_140_408-5.exe` from the example URL without a problem and without disabling HTTPS Everywhere on Windows 10 on both Firefox and Chrome. So, I can't reproduce the problem. Is this still an active problem for you?

**Comment by Maxxxxxx** [comment]
jeremyn,

Yes, it is.  
![https enabled](https://cloud.githubusercontent.com/assets/10837831/18803372/46e7001e-81a4-11e6-90a5-05c79f702fe8.jpg)
![https disabled](https://cloud.githubusercontent.com/assets/10837831/18803374/4da1162e-81a4-11e6-9e1f-2294a7112787.jpg)

For some reason, I am not getting notifications, so I apologize for the delay.
The last time I downloaded the driver was the beginning of _this_ week.
With HTTPS disabled, I can see which driver to download; with HTTPS enabled, I get a completely different looking screen -  without any drivers.

Thank you. 
Firefox 48.0.2
Win 10.

**Comment by jeremyn** [comment]
Thanks for the update. I get something like your first screenshot if I enable the `HP (buggy?)` ruleset, which is [`Hewlett-Packard.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Hewlett-Packard.xml`). That ruleset should be disabled by default because [`default_off` is set](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Hewlett-Packard.xml#L142).

Could you please create a new Firefox profile using [these instructions](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles), install only HTTPS Everywhere, don't change any of its settings, and try to reproduce the problem there?

**Comment by Maxxxxxx** [comment]
Jeremy,

  You are welcome.
  Thank you for responding so quickly, although I wish it were for the DuckDuckGo issue, not this one (!)

    I think the solution is that this ruleset _should_ be disabled by default, but it is not.   If it is, then I think I need to Reset Defaults.  I didn't realize that I made permanent changes to my settings since there isn't a settings, per se.   How often should I hit reset?

I remember from the HTTPS home page, you list NYT.com as a prime example of a mostly problematic website. 
  Along these lines, HP screams loudly that there is a potential problem when you see "buggy?" as the rule.  (> right click "Enable/Disable Rule - is this HP,com [buggy?] called a rule?) 
 Is a ruleset a rule w/a couple of pieces? 

  I thought if a website's design is such that it might cause problems with personal viewing, there's nothing HTTPS can do about it.   Proceed w/caution until the company cleans up its/their act.   

I always try to report issues in order to help improve my favorite or most useful programs. 
SOON I have to create a new FF profile to fix a different problem.
Do you still want me to do this? 

Thank you.

**Comment by jeremyn** [comment]
You can read about rulesets [here](https://www.eff.org/https-everywhere/rulesets). In my previous comment I linked to the `Hewlett-Packard.xml` ruleset, which is identified in the HTTPS Everywhere interface with the name `HP (buggy?)`.

This ruleset has a `default_off` attribute set, which means that by default the ruleset should not be active. Since the problem you described only seems to appear when the ruleset is active, then my theory is that you are encountering this problem because you enabled a ruleset that was disabled by default, in which case problems like this can be expected. Creating a new Firefox profile, installing HTTPS Everywhere there, and visiting the URL you provided in the first comment should confirm that the default behavior is for the ruleset to be off and for the site to work as expected, in this case to show you the driver you want.

`Reset to Defaults` should do the same thing as installing into a new profile, but I'm not asking you to do that because I don't want to ask you to reset changes that you meant to do and want to keep.

**Comment by jeremyn** [comment]
Also, what's the DuckDuckGo issue? I don't see it.

**Comment by Maxxxxxx** [comment]
Hey, Jeremy,

The up arrow - aka Return to the Top of the Page - hasn't been seen in two months.
 I can barely navigate the page without it.

Look for Maxxxxx - I posted it the same day.
I mentioned that GitHub is difficult to navigate for us non-tech people, so it might not be in the place that I remember putting it. 
Either I created a new post - which I can picture - or it's in response to my last post with the same topic.

Thank you for asking.

**Comment by jeremyn** [comment]
It looks like you're referring to issues (206, 224) that you filed against the duckduckgo repository, is that right? That's a different project and not something I can help you with. I thought you were referring to a problem using DuckDuckGo caused by HTTPS Everywhere.

**Comment by Maxxxxxx** [comment]
I don't see there ever being a problem between those two.
 I still haven't gotten a response from anybody.
  You, though, get two points - thank you.

**Comment by gloomy-ghost** [comment]
support.hp.com has moved to https, and I can't reproduce the issue even with `HP (buggy?)` enabled.
