### ISSUE TITLE
Broken pictures on piriform.com

### ISSUE THREAD

**Issue by TheFinalCut83** [EFForg/https-everywhere#6073]
https://www.piriform.com/ccleaner/builds
[Pictures aren't loading](http://i.imgur.com/cR2yeGr.jpg) when "Piriform (partial)" enabled.
After disabling this rule [all is ok](http://i.imgur.com/UEduNc8.jpg). Probably ruleset bug, i think.

**Comment by fuglede** [comment]
The issue is caused by the subdomain `static` not serving a proper certificate, cf. https://static.piriform.com/, and that the fix in place (redirecting to CloudFront) is outdated: the rule redirects to https://d3dsdp2n8y8ktk.cloudfront.net/pf/install_48_grey.gif which no longer exists, but https://d3sg17i8imdw59.cloudfront.net/pf/install_48_grey.gif does.

    $ dig +short static.piriform.com | grep cloudfront
    d3sg17i8imdw59.cloudfront.net

An update is contained in #6112.

**Comment by TheFinalCut83** [comment]
Many thanks!
