### ISSUE TITLE
Build `firefox-latest` broken

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#6079]
In all builds using `FIREFOX=firefox-latest`, the following errors occur, while the `firefox-esr-latest` appears to work as intended:

	+ echo 'running tests'

	running tests

	+ '[' -n /firefox-latest/firefox/firefox ']'

	+ xvfb-run cfx test -b /firefox-latest/firefox/firefox --profiledir=/tmp/tmp.xigEYiSDRl --verbose

	Using binary at '/firefox-latest/firefox/firefox'.

	Using profile at '/tmp/tmp.xigEYiSDRl'.

	libGL error: No matching fbConfigs or visuals found

	libGL error: failed to load driver: swrast

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

	process 211: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text

	See the manual page for dbus-uuidgen to correct this issue.

	[211] WARNING: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message: 'glib warning', file /builds/slave/m-rel-l64-00000000000000000000/build/src/toolkit/xre/nsSigHandlers.cpp, line 142

	(firefox:211): GConf-WARNING **: Client failed to connect to the D-BUS daemon:

	/usr/bin/dbus-launch terminated abnormally without any error message

**Comment by Hainish** [comment]
@fuglede I'm working on this currently.

We recently upgraded the version of `firefox-latest` in https://hub.docker.com/r/electronicfrontierfoundation/https-everywhere-docker-base/ to v48, but even after solving the issue above there are other issues that I think require us to finally ditch cfx and move to jpm for tooling.

**Comment by Hainish** [comment]
I'm having a lot of trouble getting `jpm` to work with `firefox-latest` within `docker` (though it works well with `firefox-esr-latest`).  I'll temporarily remove `firefox-latest` from the travis tests while I try to debug this problem.

**Comment by Hainish** [comment]
[Firefox Extension Signing](https://wiki.mozilla.org/Add-ons/Extension_Signing) seems to be the culprit.  On Firefox 48, no extensions will be installed on release or beta without first being signed by AMO, and there is no override.  This is a problem because both the extension in it's state at the point of testing as well as the additional extension we use to run tests on it are unsigned.

Previously, we provided a profile with an [about:config option to disable signature checking](https://github.com/EFForg/https-everywhere/blob/master/test/firefox/test_profile_skeleton/prefs.js#L21), but the latest security updates to Firefox 48 will no longer allow this option.

So we need to either automate the AMO signing process at test time (seems complicated) or find another release channel that doesn't require code signing (less complicated but may not be available).

**Comment by Hainish** [comment]
Apparently the unbranded builds are for just this purpose.  Unfortunately, there is currently no predictable URL for the unbranded tarball of a given version - it's simply listed on https://wiki.mozilla.org/Add-ons/Extension_Signing.  This makes automatically fetching it in our https://github.com/EFForg/https-everywhere-docker-base/blob/master/Dockerfile more difficult.  I'll open an issue with bugzilla to help us get predictable URLs for our CI.  In the meantime, I'll have to manually edit our https://github.com/EFForg/https-everywhere-docker-base any time a new stable release is made.

**Comment by Hainish** [comment]
With https://github.com/EFForg/https-everywhere-docker-base/commit/12a860dcb4a6b3fab6d94bc4c816d2b16bc8430e and https://github.com/EFForg/https-everywhere/commit/ccbbfa6f0dc126282fad951c09a454388c4346d7, travis tests should be working now.

In the process of resolving this issue, I started the process of moving us from cfx to jpm.  We didn't seem to need to transition in the end, and my work isn't yet complete for this (for instance, with jpm after the tests are run the browser does not quit for some reason, thus the tests are not able to complete).  At any rate, I've made my partial work available should we need it in the future:
https://github.com/Hainish/https-everywhere/tree/cfx-to-jpm
https://github.com/efforg/https-everywhere-docker-base/tree/support-jpm

We may not need to use jpm at all, since even it is now deprecated and we may be able to leapfrog it by our transition to WebExtensions.

**Comment by Hainish** [comment]
I've re-run all old travis jobs since the failures started.

**Comment by fuglede** [comment]
Thanks for all the information on this; that's good to be aware of. One thing I was wondering about: does the developer edition of Firefox have the same deficiency as the release build, and if not, would it make sense to use that one?

**Comment by Hainish** [comment]
@fuglede according

**Comment by Hainish** [comment]
@fuglede according to https://wiki.mozilla.org/Add-ons/Extension_Signing it's just the release and beta channels that have no way to override extension verification.  I just verified this - we can use developer edition if desired.  We already have `firefox-latest` and `firefox-esr-latest`, we could add something like `firefox-dev`.  Here's what I see the utility of each test is:

`firefox-latest`: Alerts us to problems for our core userbase
`firefox-esr-latest`: Alerts us to problems for Tor Browser users
`firefox-dev`: Alerts us in advance when there will be problems down the road

It's possible to add an additional test to `.travis.yml` to use all three.  But since the fetch tests are rather finicky and run in each of the different environments, this will increase the chances of a good ruleset failing (roughly by 3/2).  We could replace one of the tests with `firefox-dev`, but I'm reluctant to do that.  Finally, we could separate out the tests in `.travis.yml` like so:

```yaml
env:
  - TEST=firefox FIREFOX=firefox-latest
  - TEST=firefox FIREFOX=firefox-esr-latest
  - TEST=firefox FIREFOX=firefox-dev
  - TEST=chromium
  - TEST=rule
  - TEST=fetch
```

Keep in mind, though, that for each of these different `env`s, the dockerhub image for `https-everywhere-docker-base` is downloaded.  This makes for a lot of downloads, which I don't mind unless it causes problems, but something to keep in mind.

I'm in favor of breaking up the tests like above.  What do you think @fuglede, @J0WI, @jsha?

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/pull/6220 separates out the tests as described above
