### ISSUE TITLE
Version 5.2.1 breaks find and quickfind page searches in firefox 45.3.0 ESR

### ISSUE THREAD

**Issue by iwsbarker** [EFForg/https-everywhere#6144]
Ctrl+F, / and ' open the search box, but don't bring focus to it, and the search finds nothing regardless of what is typed in the search box. Downgrading to https-everywhere 5.2.0 fixes the problem

**Comment by fuglede** [comment]
I can not reproduce this issue in the Firefox-ESR 45.3.0 packaged with Debian Jessie.

![gh](https://cloud.githubusercontent.com/assets/6169306/17491817/7be49340-5da9-11e6-9f81-b79b9b3cce65.png)


Does the issue persist if you reinstall 5.2.1? And if you run it in an otherwise clean Firefox profile?

**Comment by iwsbarker** [comment]
I completely removed 5.2.0 and then reinstalled 5.2.1, and the issue is gone. So perhaps just an issue with upgrade-in-place.

**Comment by jeremyn** [comment]
I can't reproduce this using Firefox 48.0.2 with HTTPS Everywhere 5.2.3 on Windows 10. Since nobody on this issue can reproduce the problem now, I'm closing this issue.
