### ISSUE TITLE
fetch-test.sh incorrectly reports "not enough tests"

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#6295]
If I run `fetch-test.sh` against [this](https://github.com/jeremyn/https-everywhere/blob/14807228548c8e1b6518111ef30568e26d1deaea/src/chrome/content/rules/HSBC.xml) updated ruleset for HSBC, I get this error:

```
ERROR rules/HSBC.xml: Not enough tests (0 vs 1) for <Rule from '^http://www\.business\.hsbc\.co\.uk/' to 'https://www.business.hsbc.co.uk/'>
```

even though there is a test for that specific domain:

```xml
<test url="http://www.business.hsbc.co.uk/" />
```

**Comment by fuglede** [comment]
That's because that test URL counts towards the rule in [line 42](https://github.com/jeremyn/https-everywhere/blob/14807228548c8e1b6518111ef30568e26d1deaea/src/chrome/content/rules/HSBC.xml#L42). In particular, the relevant rule (as well as the corresponding target hosts) is actually redundant.

    /^http:\/\/([^\/:@]+)?\.hsbc\.co\.uk\//.test('http://www.business.hsbc.co.uk/')
    true

That being said, that that's the case is not exactly clear from the error, but I also do not see an immediate improvement that would make the cause clearer.

**Comment by jeremyn** [comment]
Thanks. Do you see anything wrong with just deleting `<target host="www.business.hsbc.co.uk" />`?

**Comment by fuglede** [comment]
No, removing that -- and the rule of course -- should be fine (but I'd probably spin up a browser to make sure I didn't miss anything).

**Comment by jeremyn** [comment]
I deleted the `www.business.hsbc.co.uk` target and rule and had to add an extra test for `<rule from="^http://([^/:@]+)?\.hsbc\.co\.uk/" to="https://$1.hsbc.co.uk/" />`.

Thanks for your help.

**Comment by fuglede** [comment]
You're welcome. While we're talking about it, note that there are some open issues regarding the test counting, so this could have equally well been an actual problem (at least, I had to go through the ruleset a couple of times before figuring out what was going on).
