### ISSUE TITLE
cnet.com

### ISSUE THREAD

**Issue by m2c2lure67** [EFForg/https-everywhere#6570]
Cnet.com videos won't play while HTTPS Everywhere is enabled?

**Comment by jeremyn** [comment]
Please provide an example link.

**Comment by m2c2lure67** [comment]
http://www.cnet.com/products/google-android-nougat/

**Comment by jeremyn** [comment]
Thanks, I can confirm the problem on that page.

**Comment by Bisaloo** [comment]
This seems fixed. I am assuming it was a CORS issue that got fixed when cnet.com switched to HTTPS.

**Comment by jeremyn** [comment]
The video at https://www.cnet.com/products/google-android-nougat/ plays for me, so I agree this seems fixed.

I'm closing this issue myself instead of asking @m2c2lure67 to do it, since they seem inactive on GitHub, however @m2c2lure67 please feel free to add a comment here if this is still a problem for you.

**Comment by m2c2lure67** [comment]
It looks good to me to...thank you for following up.  I'm not certain, but it also looks like C-Net may have removed a big chunk of remote-linked advertisement that was choking HTTPS as well as some other extensions.

**Comment by jeremyn** [comment]
@m2c2lure67 Thanks for confirming the fix.
