### ISSUE TITLE
hungryhouse.co.uk rules break blog

### ISSUE THREAD

**Issue by thomaspurchas** [EFForg/https-everywhere#6798]
The hungryhouse.co.uk blog can only serve it's assets over http. https returns 404 (weird I know). This means the hungryhouse.co.uk rule set results in their blog loading without any CSS or images.

Example:
https://hungryhouse.co.uk/blog/

**Comment by jeremyn** [comment]
Thanks for the report.

The fix is to load the given URL, look at the Network tab in the browser developer tools, and add an exclusion for the various `404` resources to [`Hungryhouse.co.uk.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Hungryhouse.co.uk.xml), including for example `hungryhouse.co.uk/wp-content/plugins/` and `hungryhouse.co.uk/wp-includes/js/`.

**Comment by Bisaloo** [comment]
This is no longer an issue as far as I can tell. Can we close this issue?

**Comment by thomaspurchas** [comment]
Looks good, closing.
