### ISSUE TITLE
JHU.edu (partial) breaks font style

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#6853]
http://guides.library.jhu.edu/c.php?g=202483&p=1334849

`JHU.edu (partial)` makes the fonts look uglier than they're supposed to be.

**Comment by jeremyn** [comment]
An example error in the web console is:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.library.jhu.edu/fonts/webfonts/Gentona-Medium.ttf. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

The relevant rule is [here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/The_Johns_Hopkins_University.xml#L205).

My understanding of cross-origin request problems is not totally solid ( @fuglede @J0WI can you please check this?), but I think there are two problems:

* The response from https://www.library.jhu.edu/fonts/webfonts/Gentona-Medium.ttf doesn't have a `Access-Control-Allow-Origin` header, so the request from http://www.library.jhu.edu (note HTTPS vs HTTP) can't access it. (I don't know why Firefox refers to the `http` resource in the error, though.)
* Even if it did have the header, it wouldn't work because of issue #49 .

One way to fix this is to add an exclusion for `www.library.jhu.edu/fonts/webfonts/` to the `JHU.edu (partial)` rule.

**Comment by gloomy-ghost** [comment]
massive close per #15157
