### ISSUE TITLE
issuu.com upload broken

### ISSUE THREAD

**Issue by pekala** [EFForg/https-everywhere#6856]
issuu.com document upload flow is HTTP, while the rest of the site is HTTPS. The second step of the flow (adding document meta data) breaks if https-everywhere plugin is enabled. To reproduce, create a free account, go to http://issuu.com/publish, and upload a PDF.

**Comment by jeremyn** [comment]
Thanks for the report. Since this issue requires an account to see, it would be helpful if you yourself could submit a pull request to fix it. You can get started [here](https://www.eff.org/https-everywhere/development) and [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md), and please feel free to ask questions here if you need help.

**Comment by pipboy96** [comment]
Website seems to be fully HTTPS now.
