### ISSUE TITLE
TI.com 

### ISSUE THREAD

**Issue by daveloyall** [EFForg/https-everywhere#6866]
When HTTPs Everywhere is enabled, this page fails to render:

http://www.ti.com/ww/en/launchpad/launchpads-msp.html 

Here is a screenshot:
![capture](https://cloud.githubusercontent.com/assets/1524866/18476755/e5af7008-7990-11e6-81c6-7f044469bd37.PNG)

Looks like it is due to failing to load some scripts:
![capture2](https://cloud.githubusercontent.com/assets/1524866/18476754/e5a704f4-7990-11e6-9259-306ffd283420.png)

I hope this helps.  I will forward a link to this Issue to the TI.com webmaster.

**Comment by jeremyn** [comment]
The problem is mixed content blocking (MCB), as you can see. The rules are: [`Texas-Instruments.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Texas-Instruments.xml) , [`TI.com-falsemixed.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/TI.com-falsemixed.xml) . An exclusion for `https://www.ti.com/ww/en/launchpad/` should be added somewhere.

@fuglede @J0WI What is "false" MCB, as in: `For rules not causing false/broken MCB, see Texas-Instruments.xml.`? Does that just mean MCB? Should the exclusion go into `TI.com-falsemixed.xml`?

**Comment by J0WI** [comment]
"false" MCB means that HTTPS Everywhere would redirect you to the secure version, but Firefox blocks the request previously.
So if Firefox would allow us to redirect the request before the MCB, we could mitigate it.

**Comment by jeremyn** [comment]
So really it is just "normal" mixed content blocking, except that it would work on `platform="mixedcontent"` (Tor), right?

**Comment by J0WI** [comment]
Yes, or any user that sets `extensions.https_everywhere.enable_mixed_rulesets` to true in Firefox' about:config.

**Comment by jeremyn** [comment]
In this specific case, if I set `extensions.https_everywhere.enable_mixed_rulesets` to `true`, the URL http://www.ti.com/ww/en/launchpad/launchpads-msp.html is still broken, so that means the exclusion should go in the main file and not the `falsemixed` file, right?

**Comment by J0WI** [comment]
This setting just turs on all `platform="mixedcontent"` rules, like Tor does.
This path need to be excluded from the main file, but could be allowed in the `falsemixed` file.

**Comment by jeremyn** [comment]
If a domain is excluded in one file and allowed in another, does that mean it's allowed overall? It must not, because `www.ti.com` is allowed in `falsemixed` and the URL is still broken when `enable_mixed_rulesets` is `true`. So how could it be specifically enabled in `falsemixed`?

**Comment by J0WI** [comment]
We have `utils/duplicate-whitelist.txt` for such cases, but you can also just make an exclusion to avoid this extra work.

**Comment by daveloyall** [comment]
FYI, an application developer at TI.com responded to a ticket I put in and is aware of this thread.

**Comment by fuglede** [comment]
The "false" part of the MCB is sufficiently different from expectations that it's considered a bug in Firefox and Chromium: https://bugzilla.mozilla.org/show_bug.cgi?id=878890. IIRC, the bug is the entire reason Tor Browser uses a non-default value of `security.mixed_content.block_active_content`.

In particular, right now `platform="mixedcontent"` rules are on by default only in Tor Browser, but as far as I'm aware Tor Browser lets through *all* active mixed content; not just what is blocked falsely. If you use it together with "block all unencrypted requests", you should get the desired effect though.

**Comment by J0WI** [comment]
Obsolete after #16701
