### ISSUE TITLE
learn.vmware.com doesn't deliver a valid certificate

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#6875]
see title

we shouldn't redirect to a certificate warning

**Comment by jeremyn** [comment]
Thanks for the report.

[Here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/VMware.xml#L71) is the target. The fix is to add an exclusion for `learn` [here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/VMware.xml#L73) and a corresponding test between [these two lines](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/VMware.xml#L78-L79).

This issue is a good example of the problem with wildcards.
