### ISSUE TITLE
Would you provide one tool to generate rules?

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#6912]
To search subdomains , get cert status, auto check in local, and so on.

**Comment by jeremyn** [comment]
That would be nice. I mentioned wanting those sorts of tools [here](https://github.com/EFForg/https-everywhere/issues/6322#issuecomment-246866651).

**Comment by fuglede** [comment]
I'm not sure what you mean by cert status and auto-checking in local exactly, but it sounds like what our tests achieve? Those you can (and probably should) run locally.

It would be nice to have a subdomain finder utility as well though (cf. #4279).

**Comment by jeremyn** [comment]
It should be straightforward for one script, given some wildcard domains, to generate a ruleset that pre-resolves the to-do list in the various pull requests I link in issue #6863 , including the one for [`udn.com`](https://github.com/EFForg/https-everywhere/pull/6824#issuecomment-246125911) that @renyouguo was involved with.

Creating a script to use Google to filter domains, run curl to note basic failures, and create an XML file to note the results should be within the skill-set of a beginner programmer. It would be slightly more complicated to identify mixed content and to crawl sites looking for `static.`-type domains, but not too much harder. [Here](https://www.google.com/#q=selenium+mixed+content)'s a simple Google search discussing solutions to the mixed content problem. Humans should only be needed to write `exclusion`s and custom `rule`s.

The real challenge for anyone wanting to make this happen is being willing to focus on a medium-sized task like this, make it work within the existing ecosystem, and endure the inevitable bikeshedding from myself and others.

**Comment by Foorack** [comment]
@jeremyn This idea has been catching my interest for a while. I've done an attempt on it already but it's not finished yet. It can be optimized a lot but this is **only a proof-of-concept**. To test it I have been running it against a portion of the europa.eu domain as it has 788 functional subdomains. :+1: 
My personal test approach is as following:

1. First use Sublist3r (without the bruteforce option!) which uses Google, Bing, dnsdumpster as well as a few other sources to find all subdomains. This does generate some false-positives which I sort out in next step.
2. Curl with head probe to see if the subdomain responds to basic http. If not then should be safe to assume it was a false-positive.
3. Compiles ruleset with python script.

I still planning on implementing automatic mixed-content checking with bramu's mixed-content scan https://github.com/bramus/mixed-content-scan but most features such as different content, https->http redirect, timeouts, certificate-chain errors and so on.

https://gist.github.com/Foorack/51893f7d0f8b16d6d8be25073131d4b6

**Comment by jeremyn** [comment]
@Foorack That's awesome that you're already looking at that! Thank you. Please feel free to submit it as a pull request to get more feedback when you're ready. A basic tool that is ready to use will be more useful than something with big plans that we never see, you know what I mean?

I haven't reviewed your code in super detail, and not to make huge criticisms at an early stage, but two big structural changes I'd like to see are:

* I don't know how Sublist3r works but it would be nice if the whole thing were pure Python instead of bash+Python.
* Use an XML writer to output the rulesets instead of writing manually to a file. The big top comment can be separately written and prepended to the XML file.

**Comment by renyouguo** [comment]
[lijiejie/subDomainsBrute: A simple and fast sub domain brute tool for pentesters](https://github.com/lijiejie/subDomainsBrute)

**Comment by Foorack** [comment]
@jeremyn Thanks! A few questions however. First, as this have external dependencies, would it be best to make it a sub-project or just push it as a utility script? Secondly, I am a beginner python developer and I am still shocked the code actually works as I intended. Therefor I assume there are lots of improvements which can be made to the code. This is only a proof-of-concept hence the use of bash; my plan is to port it over to python once I get the fundamentals working. Regarding the second point, for what reasons would it be beneficial to switch to a XML writer instead of the current system printing to a output stream? Unless it poses clear improvements, I don't see the point in writing the comment section to a external file.

@renyouguo I have already seen that project before. I have started experimenting with this idea but I am absolutely in no position to decide what approach should be made! Having that said, I am strongly against bruteforcing subdomains. It increases the probability of finding internal or debug DNS's which searches on Baidu and Google would in most cases only return address used by the public.

**Comment by jeremyn** [comment]
@Foorack In the end this tool should go into the main HTTPS Everywhere repository like [https_everywhere_checker](https://github.com/EFForg/https-everywhere/tree/3d78fee6a04a89b1d11cced6117f7b8308b92cf9/test/rules/src/https_everywhere_checker), but for development you can do whatever you want. You might find it easier to make a separate project for development rather than try to manage changes and feedback in a pull request or Gist.

XML writing is a solved problem and you should use an existing solution rather than reinvent the wheel. I recommend `lxml` since [it's already a dev dependency](https://github.com/EFForg/https-everywhere/blob/aa05861ed496082dd334e07e0ab5975e76bcf3a3/requirements.txt#L1).

**Comment by renyouguo** [comment]
@Foorack Sublist3r only works in Python2.7 . While #6749 be fixed someday, change it again?

**Comment by Foorack** [comment]
I just realised this idea cannot be efficiently realised. Lets say this program is "finished" so it efficiently covers every possible situation, how would the reviewers possibly be able to keep up and review the rulesets? If this program is created then what would be stopping someone from just hooking it up with the Alexa top 100-million list? I think questions like these needs to be sorted out before the actual implementation of this program.

Example: https://github.com/EFForg/https-everywhere/pull/6991

**Comment by jeremyn** [comment]
@Foorack The idea is that this tool could be used by a contributor who wants to make or update a ruleset for a site they're interested in. It would produce such a high quality ruleset that the reviewer only needs to make a few tweaks, if any.

I would rather have the problem of having too many high quality rulesets to review, than to have go through tedious testing and style corrections for most rulesets that for example you and I did in pull request #6857 . I know you mean well, but you are proposing that we slow down the ruleset creation process by not creating helpful tools so both contributors and I have to spend more time on tedium.

I agree that in this hypothetical post-scarcity world where we are flooded with millions of high quality rulesets, we'll have new concerns, for example see the discussion [here](https://github.com/EFForg/https-everywhere/issues/6322#issuecomment-240574166) and following. But we could just make new rules, such "everything in the Alexa top-10k is okay, anything below must pass some sort of Wikipedia-style notability test".

**Comment by galeksandrp** [comment]
https://github.com/galeksandrp/https-everywhere/tree/check

**Comment by jeremyn** [comment]
@galeksandrp For most of your pull requests, do you just find a domain that needs HTTPS support and then run your script against it?

**Comment by galeksandrp** [comment]
@jeremyn Yes. However, Google Custom Search is limited to first 100 results (that's why I can't close famous aist.go.jp and fnal.gov rulesets). It also can't check mixed content yet, through there are https://www.jitbit.com/sslcheck/ and other phantomjs checkers and even `curl | grep 'http://'`. Looks like in end similar checker by `@Hainish` will be attached to Github Issues webhook and there are no more reviewing at all.

**Comment by jeremyn** [comment]
@galeksandrp It's cool that your process is far enough along to generate human-quality rulesets. It might be a good base for the tools we're discussing in this issue.

The thing is that the PRs generated by your process sometimes have simple problems. They leave out domains that can be found with an easy search, or they have simple mis-sorting. I can find these problems in your PRs from last week, a month ago, two months ago. You've submitted and we've merged enough of your PRs that I'm sure you can find these problems yourself. I think automation is great and I hope you keep working on it, but please review and correct the output before submitting it as a PR, and also go through your existing open PRs and do the same thing.

I don't understand your point about `fnal.gov` (PR #5265 ) and `aist.co.jp` (PR #5222 ). You can just go in and make the changes yourself, in fact for `fnal.gov` I gave you a long, specific list.

**Comment by jeremyn** [comment]
I created a pull request for Sublist3r to modify the output sort order to match what we like, see https://github.com/aboul3la/Sublist3r/pull/38 .

**Comment by jeremyn** [comment]
@aboul3la has merged my sorting change into Sublist3r (thanks!), so the subdomains produced by Sublist3r should now be sorted the way we want it.
