### ISSUE TITLE
HTTPS everywhere breaks Youtube switching to "theater mode" and closing the "language chooser" bar on top of the video.

### ISSUE THREAD

**Issue by allue** [EFForg/https-everywhere#7222]
That is all.

**Comment by jeremyn** [comment]
Thanks for the report. I can't reproduce a problem with theater mode. Also the "language chooser" bar is at the bottom of the page for me, not the top, as described in this YouTube help video: https://www.youtube.com/watch?v=FVwo77t88nc . I don't have a problem changing the language either.

Can you please describe more specifically what the problem is, with screenshots if possible? Also, what browser and operating system are you using?

**Comment by allue** [comment]
Reporting back again that everything seems to be fine now. I disabled it and I wanted to troubleshoot now and it works like a charm.

The "language chooser bar" I was referring to is this one: ![1](https://cloud.githubusercontent.com/assets/18418334/18975319/ea6874ae-86b1-11e6-9581-8605e98e8feb.png)

It re-appears daily, since I clear cookies upon exiting the browser. (FF on Win 7 x64)

Anyways, I'll close this now. Thanks for the plugin - httpS should be standard!
Keep fighting the good fight!

**Comment by jeremyn** [comment]
Thanks @allue .
