### ISSUE TITLE
Would the MCB fix rule be high priority?

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#7230]
For example:
#6941 
#6956

**Comment by J0WI** [comment]
Personally I don't think so. The Torbrowser is not affected by MCB issues and users can easily bypass them or disable the rule.

**Comment by jeremyn** [comment]
We have almost 400 open issues and very few people working on them so we have to be very conservative about what `High Priority` means.

`High Priority` to me includes:

* core functionality for mega-sites like Google or Facebook is completely broken
* the add-on is entirely unusable for a large group of users, like all Chrome users, or all Mac users, or all Brazilian Portuguese users
* there is a serious security problem like a ruleset that secretly redirects users to download virus-infected software
* something is breaking all builds

I can't think of anything else.

If you think something should be high priority then ping us reviewers and explain why you think it's high priority, like "This is the most important social networking site in $COUNTRY and this problem is preventing anyone from logging in."

Just my opinion, @fuglede @Hainish @J0WI what do you think?

**Comment by Hainish** [comment]
I would add to this conflicts with other commonly used extensions.  For instance, if HTTPS Everywhere disabled all other extensions from functioning, that would also be high priority.

**Comment by Hainish** [comment]
Perhaps more generally "disrupts the functioning of other user-installed software" or something.

**Comment by jeremyn** [comment]
I would classify that under "entirely unusable for a large group of users".

**Comment by Hainish** [comment]
The phrase "the add-on is entirely unusable for a large group of users" makes it sound like you are referring to HTTPS Everywhere being rendered unusable, not other addons becoming unusable due to HTTPS Everywhere.

**Comment by jeremyn** [comment]
That's a fair point.
