### ISSUE TITLE
Use GitHub for documentation instead of eff.org

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#7256]
While creating #7255 I realized that we have some parts of our docs here on GitHub, some parts on EFF.org and some parts on both.

I think it would be easier to maintain when EFF.org just refers to the docs here on GitHub. To be more specific, I mean the pages "FAQ", "Report Bugs / Hack On The Code" and "Creating HTTPS Everywhere Rulesets". They should be copied into the GitHub Wiki or into the existing .md files.
This would allow contributes to help improving the documentation and update it when core functionality or requirements changed.

cc @jsha @Hainish

**Comment by J0WI** [comment]
See also [docs/rulesets.html](https://github.com/EFForg/https-everywhere/blob/master/docs/rulesets.html)

**Comment by jeremyn** [comment]
I strongly support this. Given the options of `.md` files and the GitHub Wiki, I prefer `.md` files.

**Comment by jsha** [comment]
Yep, I am 100% agreed: This repo should be the primary source material for the documentation. However, I think the EFF website is a friendlier place to offer the documentation to end users. @J0WI pointed out `docs/rulesets.html`. I created that from the content on https://www.eff.org/https-everywhere/rulesets, with the intent that we edit it here, and then someone with EFF edit privs updates it on EFF.org. If you have time to do the same process with additional pages from that site, I'm in support of the idea!

It may also make sense for the more developer-facing documents to live entirely with the source code, rather than on the web site. That way we could save a step for certain updates.

**Comment by Hainish** [comment]
I agree that the repo should be the canonical place for documentation.  I think we should convert `docs/rulesets.html` to markdown, and use [pandoc](http://pandoc.org/) to generate the HTML used on the EFF website.

Likewise, we should add an FAQ.md and Report_Bugs_Hack_Code.md

**Comment by Hainish** [comment]
Related: https://github.com/EFForg/https-everywhere/pull/7469

**Comment by Hainish** [comment]
#7469 closes this
