### ISSUE TITLE
A certain NSIDC page is broken

### ISSUE THREAD

**Issue by kemokid** [EFForg/https-everywhere#7367]
If I navigate to http://nsidc.org/arcticseaicenews/charctic-interactive-sea-ice-graph/

HTTPS Everywhere redirects to

https://nsidc.org/arcticseaicenews/charctic-interactive-sea-ice-graph/

but then the chart doesn't load. Console message:

Mixed Content: The page at 'https://nsidc.org/arcticseaicenews/charctic-interactive-sea-ice-graph/' was loaded over HTTPS, but requested an insecure resource 'http://nsidc.org/data/tools/arctic-sea-ice-chart/'. This request has been blocked; the content must be served over HTTPS.

Given that the resource is from the same website, why doesn't HTTPS Everywhere simply load it from https://nsidc.org/data/tools/arctic-sea-ice-chart/ ?

**Comment by numismatika** [comment]
The MixedContentBlocker triggers before HTTPS-Everywhere had the chance to rewrite domains, so you will get errors although the requested content could be secured and rewritten to TLS.
In Firefox this is a work in progress issue.

**Comment by jeremyn** [comment]
@kemokid : Adding onto what @numismatika said, what you're seeing is documented [here](https://www.eff.org/https-everywhere/rulesets#mixed-content), and in fact I can confirm that the link works in the Tor Browser as expected based on the description in the link.

The ruleset that's rewriting the URL is [`National-Snow-and-Ice-Data-Center.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/National-Snow-and-Ice-Data-Center.xml), so that's where any fix or exception should be added. It's an old-style ruleset and should be rewritten too, especially to remove the wildcard `*.nsidc.org`.

**Comment by smw-koops** [comment]
This is the rewritten rule I suggest:

https://gist.github.com/smw-koops/afd8245af7427d951565a5e350b77bcb

If it works correctly I will try adding an exclusion for that page.

**Comment by jeremyn** [comment]
@smw-koops Please feel free to submit a pull request directly, there's no need to pre-submit a gist. Thanks for helping by the way, we can definitely use more volunteers.
