### ISSUE TITLE
Chrome: User-added rules don't persist enabled/disabled state across restart

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [EFForg/https-everywhere#741]
When there's a site with either defective https cert, or one that I manually added (add rule set), there's no way to permanently remove that defective rule set for that site! I have to manually uncheck the site's name from the extension for it to work, every time I visit it!

Can you please provide a way to permanently remove a site?

**Comment by StevenRoddis** [comment]
I think we should increase the priority of this issue, given it's impact.

**Comment by jsha** [comment]
Agreed. I added the High Priority tag. @StevenRoddis, @semenko, do either of you think you might have time to work on this?

I think there are two things to fix:
 - 'Add this site' should only be available on the HTTPS version of a site. Alternately, when you click 'add this site', it should navigate you to the site while you are filling out the form, so that you have an opportunity to notice the site is broken.
 - Unchecking a custom-added rule should be persisted across browser restarts.
