### ISSUE TITLE
When "Block all unencrypted requests" is activated, redirect to archive.org

### ISSUE THREAD

**Issue by arthuredelstein** [EFForg/https-everywhere#7533]
When "Block all unencrypted requests" is activated, instead of simply failing when a user requests an HTTP site, HTTPS-Everywhere could redirect to the latest Wayback Machine copy on https://web.archive.org/ . I'd be willing to work on a patch if the maintainers think this is a good idea.

**Comment by Hainish** [comment]
I understand the utility, but I don't think this is a desired or expected behavior.  A user may be accessing a site they do not wish to disclose to the archive.  A user may be alarmed that they are redirected to a domain that they did not directly request and may have built no trust relationship with.  Perhaps they are prepared to enter login credentials to the site.  They may ignore the banner at the top which indicates that this is not the site they entered into the URL bar.  A MITM could force every request to go through the archive by actively blocking HTTPS, where the user may only want to access the HTTPS version of the intended site.  This also conflicts with https://github.com/EFForg/https-everywhere/pull/7435

**Comment by arthuredelstein** [comment]
What about a link on the error page that allows the user to manually load the archive.org version?

**Comment by Hainish** [comment]
@arthuredelstein yes, I think that would be useful.  Do you want to prepare a PR?  Can you fork from https://github.com/EFForg/https-everywhere/pull/7435 or wait for that to get merged?

**Comment by Hainish** [comment]
If you could add some explainer text to the interstitial page that would be really good - why you're seeing this, that the link is to a third party that has mirrored the content, etc

**Comment by arthuredelstein** [comment]
I'll give it a go!
