### ISSUE TITLE
arstechnica.com & arstechnica.co.uk should be fully HTTPS now?

### ISSUE THREAD

**Issue by mgol** [EFForg/https-everywhere#7585]
I believe arstechnica.com (& .co.uk) should be fully HTTPS now. Current rules only handle forum and the login page but the whole site seems to work with HTTPS now.

Ref #4196 #4201

**Comment by terrorist96** [comment]
Still reverts to http for me.

**Comment by mgol** [comment]
Yes, that's what I mean with this ticket...

**Comment by jeremyn** [comment]
@mgol If a site redirects itself from HTTPS to HTTP, then we can't include it in a ruleset because we'll have a loop. For example:

* User enters http://arstechnica.com
* HTTPS Everywhere rewrites to https://arstechnica.com
* Ars Technica redirects to http
* HTTPS Everywhere rewrites (again) to https
* Ars Technica redirects to http (again), etc

You can test this yourself by creating a [custom ruleset](https://www.eff.org/https-everywhere/rulesets#testing) with `<target host="arstechnica.com" />` .

So I think this issue should closed. What do you think?

**Comment by mgol** [comment]
It seems it redirects HTTPS to HTTP if you're not logged in... What a terrible idea. I agree it's not possible then.
