### ISSUE TITLE
Add UI to temporarily disable HTTPS Everywhere for Chrome

### ISSUE THREAD

**Issue by Superluigi6** [EFForg/https-everywhere#760]
I'm using HTTPS Everywhere for Chrome, and it's great. My only suggestion, is to add a feature that temporarily disables HTTPS Everywhere and turns back on when you tell it too.

**Comment by diracdeltas** [comment]
You can do this by going to `chrome://extensions` and unchecking the "enabled" box for now.

**Comment by semenko** [comment]
Love this idea.

I might implement this as a temporary disable button (e.g. "press to disable HTTPSe for 1 hour") or a toggle that auto-reenables itself whenever chrome is restarted -- so users don't forget and disable the extension for an extended period of time.

**Comment by jsha** [comment]
I like the ideas for making it harder to forget and leave HTTPS
Everywhere off. I'm happy with whichever of these you choose. Let's get
some feedback on the Chrome version and update the Firefox version not
too long after so the behavior and messaging matches.

**Comment by semenko** [comment]
Also worth considering what UI changes we want -- perhaps before pushing a version with HTTP Nowhere mode. 

HTTP Nowhere mode makes the icon to RED.

One option:
Have HTTP Nowhere mode to turn the icon GREEN and have the disabled extension RED

Another:
Have HTTP Nowhere mode stay RED, and have the disabled extension GREY.

**Comment by jsha** [comment]
> Have HTTP Nowhere mode stay RED, and have the disabled extension GREY.

I like this because it matches the current Firefox behavior and I don't
want to change that for fear of confusing people.

Red also makes sense for HTTP Nowhere because it breaks a lot of sites,
and at least in Firefox it's not clear why the site is failing to load.
The red is a nice reminder that HTTPS Everywhere might be causing it.

**Comment by cooperq** [comment]
I think that red is a good color for http-nowhere mode since it 'breaks' non-encrypted sites. It is a good reminder to the user that they have turned on a feature that will break things. I think that the icon should be more distinct though if https everywhere is disabled, since this is a potentially dangerous state. Maybe something like a warning sign on top of it? Or a crossed out sign? Something to strongly indicate to the user that security is turned off. 

Also :+1: for both of these features in https-everywhere for chrome.

**Comment by Superluigi6** [comment]
Wait what is HTTP Nowhere?

**Comment by reedy** [comment]
"Block all HTTP requests"
