### ISSUE TITLE
Exclusion for different source type

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#7953]
Learn from Redirector:
```
Main window (address bar)
IFrames
Stylesheets
Scripts
Images
Objects (e.g. Flash videos, Java applets)
XMLHttpRequests (Ajax)
Other
```
Some MCB rule is so complicated.
Most of them , only we need is skipping the address bar.

**Comment by jeremyn** [comment]
I'm sorry, but I don't know what you are asking for here.

**Comment by ivysrono** [comment]
One rule for Redirector:
```
        {
            "description": "Google -> 科大 1",
            "exampleUrl": "https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js",
            "exampleResult": "https://ajax.proxy.ustclug.org/ajax/libs/jquery/3.0.0/jquery.min.js",
            "error": null,
            "includePattern": "^https?://(ajax|fonts)\\.googleapis\\.com/(.+)",
            "excludePattern": "https://ajax.googleapis.com/ajax/libs/jquery/(1.2.3|1.2.6|1.3.0|1.3.1|1.3.2|1.4.0|1.4.1|1.4.2|1.4.3|1.4.4|1.5.0|1.5.1|1.5.2|1.6.0|1.6.1|1.6.2|1.6.3|1.6.4|1.7.0|1.7.1|1.7.2|1.8.0|1.8.1|1.8.2|1.8.3|1.9.0|1.9.1|1.10.0|1.10.1|1.10.2|1.11.0|1.11.1|1.11.2|1.11.3|1.12.0|1.12.1|1.12.2|1.12.3|1.12.4|2.0.0|2.0.1|2.0.2|2.0.3|2.1.0|2.1.1|2.1.3|2.1.4)/jquery.min.js",
            "redirectUrl": "https://$1.proxy.ustclug.org/$2",
            "patternType": "R",
            "processMatches": "noProcessing",
            "disabled": false,
            "appliesTo": [
                "main_frame",
                "sub_frame",
                "stylesheet",
                "script",
                "image",
                "object",
                "xmlhttprequest",
                "other"
            ]
        },
```

**Comment by gloomy-ghost** [comment]
@ivysrono is probably saying that we should have a mechanism that excludes all URLs which are opened in main windows (for normal users, a URL occurring in the address bar usually means it's a page), so that we can rewrite all other resources easily. The point is a domain can have a lot of MCB pages and we have to exclude them on Chrome/Firefox, but http resources in the page are still accessible in https. `mixedcontent` ruleset which allows redirecting MCB pages currently only works on Tor, and redirecting resources for Chrome/Firefox using current mechanism isn't graceful enough. (e.g. [Gtimg.cn.xml](https://github.com/EFForg/https-everywhere/blob/9a842ff8ecaee27530758b22220811c026414bcd/src/chrome/content/rules/Gtimg.cn.xml))

**Comment by ivysrono** [comment]
webRequest.ResourceType - Mozilla | MDN
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType
