### ISSUE TITLE
Clarify license so GitHub can detect it

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#7978]
GitHub can detect and display a project license if the included LICENSE file matches "a short list of known licenses", according to https://github.com/blog/2252-license-now-displayed-on-repository-overview.

HTTPS Everywhere's license file is [here](https://github.com/EFForg/https-everywhere/blob/c8c4ae35a2f27745480cd52d5f042b5c8bd32b19/LICENSE.txt), and it's complicated so GitHub can't figure it out. I think [this](https://github.com/EFForg/https-everywhere/blob/c8c4ae35a2f27745480cd52d5f042b5c8bd32b19/LICENSE.txt#L27-L28) is saying the overall license is GPLv3.

I propose we change `LICENSE.txt` to the standard GPLv3 text so GitHub can detect it, and move the rest of the license information to another file.

**Comment by jeremyn** [comment]
Pinging @Hainish .

**Comment by jeremyn** [comment]
@Hainish Is the license for HTTPS Everywhere actually GPLv3, and we just need to change the text around to make that clear, or is there some actual question about the overall license?

**Comment by koops76** [comment]
#13062

**Comment by brainwane** [comment]
(Some discussion ongoing in #13062.)

**Comment by jeremyn** [comment]
@Hainish I would like to have at least one open issue or pull request reflecting an ongoing discussion, or at least reflecting that my concerns have not been fully addressed.

**Comment by brainwane** [comment]
@jeremyn Per https://github.com/EFForg/https-everywhere/pull/13062#issuecomment-347375367 and your response there: it sounds as though you do not think an EFF lawyer's word would be authoritative here in responding to your concerns, since as you see it this is less a matter of legal compliance than of the developer experience of other potential downstreams and contributors and your take on open source citizenship norms, which are social and technical issues more than legal issues. Am I right? I want to understand so I can potentially get people with the right expertise into any future discussion (whether it's in a GitHub issue, a mailing list thread, or elsewhere).

**Comment by jeremyn** [comment]
@brainwane I'm not sure what you are asking. Staff lawyers generally oppose open source licensing and support the status quo if their client isn't facing significant legal trouble. I don't expect an EFF staff lawyer to lead an effort to clarify licensing problems for the benefit of contributors and/or downstreams.

**Comment by brainwane** [comment]
@jeremyn let's unpack what you've just said or implied.

You've implied that, when it comes to open source licensing, EFF staff lawyers should be expected to be as reluctant to promote or approve open source licensing as lawyers at the average company or organization. I haven't had that experience, and if you have, I'd like to know.

Where I asked about finding people to participate in a discussion, you have read me as talking about who would *lead* an effort to address your concerns. These are different things, and I would like for you to acknowledge that.

I'm finding this particular conversation difficult for a few reasons. I would very much like to work it out with you and I think a synchronous chat (e.g., on IRC) or phone call would help me a lot, not least because I'm having trouble reading your emotional cues. I'd be happy to then sum it up and report it back to this issue. May I email you to set that up? This does not have to be something that happens frequently, in case you are concerned about setting a precedent.

**Comment by jeremyn** [comment]
@brainwane I'm still not sure what you are asking me. You mentioned whether I "think an EFF lawyer's word would be authoritative". The only time a lawyer has been involved here, that I know of, is during an in-person meeting with @Hainish mentioned at https://github.com/EFForg/https-everywhere/pull/13062#issuecomment-341176504, which was so superficial that they did not correct a typo in a very short file, and before I made my later, more lengthy comments. So it would be incorrect to, for example, frame this discussion as saying that I've rejected the carefully researched findings of the EFF's legal team.

I'm sure that the lawyers who choose to work at the EFF are more sympathetic toward open source than the average lawyer. However any lawyer's primary responsibility is to protect and advise their actual client. They are not going to come in here and publicly raise doubts about their client's legal position out of a general sympathy for open source or for the benefit of contributors and downstreams who are not their clients. I would be interested in any specific legal argument they want to make but I assume their general statements will be to the effect of "my client is doing, and has done, things correctly".

It's unclear what you are expecting from me at the moment. The entire discussion is visible here and in https://github.com/EFForg/https-everywhere/pull/13062 and I don't think it requires unpacking or emotional considerations. I think my concerns are readily visible from this existing discussion. I don't know who the right person is at the EFF to respond. I think the concerns I've raised are straightforward and I hope we can avoid further "meta-discussion" like we're having now.

I would like to avoid private discussions related to this. Licensing confusion affects all contributors and downstreams, so the discussion should be visible to everyone.

For your quote:

> Where I asked about finding people to participate in a discussion, you have read me as talking about who would *lead* an effort to address your concerns. These are different things, and I would like for you to acknowledge that.

I am unclear as to the point you are making but I want to acknowledge that I have read this and do not mean to offend you by leaving out reference to it.

**Comment by jeremyn** [comment]
I've reopened this issue since the discussion is still ongoing. Please don't re-close it unless another issue is opened to replace it, or someone says clearly that the discussion is over and we shouldn't talk about it anymore.

***

This discussion might go more smoothly if I make it clear what I want to achieve. None of this should contradict anything I've said up to this point.

Here's how I think this project should work. None of this should be surprising or novel for a FLOSS project:

* every file in the project should have an easily identifiable license and copyright holder. The identification can be done either by a statement in the file, or by the file's location in the project's structure. If there are multiple copyright holders for a file, they should be indicated clearly in that file, for example:

```python
# Original file copyright 2010 by ABC Foundation.
# Modifications copyright 2011 by the EFF.
```

* the terms of all licenses for code included in or distributed with the project should be followed, for example adding the license text to the project, putting in copyright notices, noting modifications in some way, etc.

* the licensing and copyright status for all contributions should be made clear to contributors before they release their contributions, for example, before they submit a PR.

* where possible, the EFF should relicense all code it releases under a single license, for simplicity.

* code released under certain "dangerous" licenses such as the Affero GPL should be moved into other repositories.

Here are some current problems:

* the repository is jumbled, for example it's not clear what parts of `utils/` count as "HTTPS Everywhere", or which parts are derived from the Python Software Foundation build code.

* the project doesn't entirely follow the terms of other licenses, such as noting modifications as the PSF license requires, or including the MIT license for CodeMirror.

* the current [`LICENSE.txt`](https://github.com/EFForg/https-everywhere/blob/38f55dc9018509b0c1788193b4d8e0d71341e4b0/LICENSE.txt) is vague. For example, the rulesets section says "To the extent copyright applies to the rulesets, they can be used according to GPL v2 or later." Almost everything is copyrighted, so the first clause is not appropriate. FLOSS licensing is concerned mainly with distribution, not "use", so the intention of saying a thing can be "used according to GPL v2" is perhaps legally unclear.

* **perhaps most seriously**, the project contains many thousands of contributions from people, many anonymous, who have contributed their code under arguably unclear licensing terms. It would be impossible to contact them all to have them relicense their code and/or assign copyright to the EFF, if that turned out to be necessary.

***

This is all "Licensing 101" stuff that should be clear to anyone with basic knowledge of open source legalities. I should not have to keep explaining it.

The intent here is not to meet some GitHub technical requirement for displaying license text. However the GitHub requirement is such a low bar that it raises questions that we cannot meet even that.

I think clarifying licensing is a matter of respect to the thousands of hours of contributor and maintainer time that has been volunteered toward this project. I hope the EFF sees it the same way.

I don't know how to proceed because I don't know how the EFF sees this problem. If the EFF sees this as a licensing problem, then it can figure out on its own who to talk to and what work needs to be done to solve it. If it wants my advice or suggestions, it should feel free to ask me. If on the other hand, the EFF sees this as a problem with an unhappy maintainer who keeps complaining about some trivial problems, then I would prefer we just stop talking about it altogether. At this point the problems should be clear enough.

**Comment by Hainish** [comment]
> the current LICENSE.txt is vague. For example, the rulesets section says "To the extent copyright applies to the rulesets, they can be used according to GPL v2 or later." Almost everything is copyrighted, so the first clause is not appropriate. FLOSS licensing is concerned mainly with distribution, not "use", so the intention of saying a thing can be "used according to GPL v2" is perhaps legally unclear.

This is language specifically crafted by EFF lawyers.  The nuance is intentional.  Raw data reflecting the HTTP to HTTPS mappings of websites on the internet constitutes a data source, lacking copyright since it lacks [creative arrangement](http://articles.baltimoresun.com/1991-03-28/business/1991087010_1_copyright-law-copyright-infringement-rural-telephone).  Comments and arrangement **are** copyrightable.  Thus the nuance.  Your base assumption that "almost everything is copyrighted" is substantively false.

As we've repeatedly stated, separating out every separately licensed bit of code into its own repository is practically undesirable.  https://github.com/EFForg/https-everywhere/issues/6749#issuecomment-363289535 is the latest case in point.  We've had that discussion, and I find it to have diminishing returns.

> the project doesn't entirely follow the terms of other licenses, such as noting modifications as the PSF license requires, or including the MIT license for CodeMirror.

The first part of the statement is untrue.  See the following:

```
2. Subject to the terms and conditions of this License Agreement, PSF
hereby grants Licensee a nonexclusive, royalty-free, world-wide
license to reproduce, analyze, test, perform and/or display publicly,
prepare derivative works, distribute, and otherwise use Python
alone or in any derivative version, provided, however, that PSF's
License Agreement and PSF's notice of copyright, i.e., "Copyright (c)
2001, 2002, 2003, 2004, 2005, 2006 Python Software Foundation; All Rights
Reserved" are retained in Python alone or in any derivative version 
prepared by Licensee.

3. In the event Licensee prepares a derivative work that is based on
or incorporates Python or any part thereof, and wants to make
the derivative work available to others as provided herein, then
Licensee hereby agrees to include in any such work a brief summary of
the changes made to Python.
```

These are the only relevant notes pertaining to the PSF-licensed part of our code.  Both of these are being followed, both in `master` and my own `python3` branches.

For CodeMirror, you're probably right.  The PR adding CodeMirror should have included a note about the MIT license.

> I think clarifying licensing is a matter of respect to the thousands of hours of contributor and maintainer time that has been volunteered toward this project. I hope the EFF sees it the same way.

To portray developer time as disrespected is to misconstrue of the efforts so many contributors have put into this project.  The licensing **is** clear.  All the more so when it dedicates the appropriate amount to the nuance of different aspects of the project.  Please don't speak for the many different contributors who have been involved in this project and have a very different experience.

Contorting our `LICENSE.txt` for the sake of a *perceived* simplicity, at the cost of nuance and against the advice of EFFs legal team, is not something that will happen.  We've hashed and rehashed this conversation: this issue is closed.

Adding copyright notices to the top of individual source code files is something that can be opened in a separate issue.
