### ISSUE TITLE
Clarify relationship with HSTS in FAQ

### ISSUE THREAD

**Issue by pinobatch** [EFForg/https-everywhere#8187]
The section "[Why does HTTPS Everywhere include rules for sites like PayPal that already require HTTPS on all their pages?](https://www.eff.org/https-everywhere/faq#why-does-https-everywhere-include-rules-for-sites-like-paypal-that-already-require-https-on-all-their-pages)" in the FAQ currently states the following with regard to sites that redirect from HTTP to HTTPS:

> (Note that HTTPS Everywhere currently does not include a comprehensive list of such sites, which are mainly financial institutions.)

In [a comment to another pull request](https://github.com/EFForg/https-everywhere/pull/8180#issuecomment-272204277), jeremyn wrote with respect to lines 70 and 92 of [a proposed change to the FAQ](https://github.com/EFForg/https-everywhere/pull/8180/commits/82f94f41121758813e7bbcb1ec67eae00fd8ea73):

> I'm not entirely sure what "Such a list would largely be redundant to the HSTS preload list." means.

The FAQ currently implies that HTTPS Everywhere's rewriting primarily covers sites that do not yet redirect all cleartext HTTP requests to HTTPS. It also includes a few sites that do redirect, primarily banks, because those are especially sensitive to first-visit SSL stripping. Both HTTPS Everywhere and the HSTS preload list are measures against first-visit SSL stripping. But if a site is in the HSTS preload list of all browsers that support HTTPS Everywhere, it doesn't need to be in HTTPS Everywhere. This is why in the section "[How do I add my own site to HTTPS Everywhere?](https://www.eff.org/https-everywhere/faq#how-do-i-add-my-own-site-to-https-everywhere)", the FAQ recommends instead getting onto the HSTS preload list in order to protect even those users who do not use HTTPS Everywhere.

So to clarify HTTPS Everywhere's role as a supplement to HSTS, I propose the following:

* In "[How do I get support for an additional site in HTTPS Everywhere?](https://www.eff.org/https-everywhere/faq#how-do-i-get-support-for-an-additional-site-in-https-everywhere)", add a notice for webmasters to read the section "How do I add my own site to HTTPS Everywhere?" below.
* In "Why does HTTPS Everywhere include rules for sites like PayPal that already require HTTPS on all their pages?", mention why "HTTPS Everywhere currently does not include a comprehensive list of such sites".

**Comment by jeremyn** [comment]
I'm actually not sure what "(Note that HTTPS Everywhere currently does not include a comprehensive list of such sites, which are mainly financial institutions.)" is trying to say in the current FAQ. I think it means that HTTPS doesn't distinguish or make a sub-list of covered domains that already force a redirect from plain HTTP to HTTPS. I would remove that line from the FAQ answer because it's confusing, but maybe it was added after EFF got a lot of questions on that specific point. I don't know.

I don't want to clutter the FAQ by linking one FAQ to another FAQ fifty lines down. Maybe instead we could merge [How do I get support for an additional site in HTTPS Everywhere?](https://www.eff.org/https-everywhere/faq#how-do-i-get-support-for-an-additional-site-in-https-everywhere) and [How do I add my own site to HTTPS Everywhere?](https://www.eff.org/https-everywhere/faq#how-do-i-add-my-own-site-to-https-everywhere)

Also @pinobatch you may find these two issues relevant: https://github.com/EFForg/https-everywhere/issues/7126 for HSTS and https://github.com/EFForg/https-everywhere/issues/7707 for documentation. I think @Hainish has a personal to-do to try to sort all the documentation out.

**Comment by Hainish** [comment]
FYI: My main concern is to sort out the documentation with `CONTRIBUTING.md`, the progress for which you can track with this (currently work in progress) PR https://github.com/EFForg/https-everywhere/pull/8193
