### ISSUE TITLE
DEV2 - popup.xml error

### ISSUE THREAD

**Issue by sirald66** [EFForg/https-everywhere#842]
HP G72 253NR
MS WIN7 HP x64
FIREFOX 34.0
EVERYWHERE 5.0-DEV2
chrome://global/content/bindings/popup.xml:28

Selecting HTTPSE toolbar icon drop-down menu, then Enable / Disable Rules, browser freezes until it displays 'chrome://global/content/bindings/popup.xml:28' as unresponsive; after a few cycles of this, empty rules list window appears.
![foo](https://cloud.githubusercontent.com/assets/2006904/5536515/6a4e688c-8a50-11e4-9dac-7c3ad779d1d1.png)

ANDY - Salt Lake, UT US

**Comment by sirald66** [comment]
Please reply.

**Comment by sirald66** [comment]
Has development been abandoned?

**Comment by jsha** [comment]
Development is definitely not abandoned, but we've just finished with a long holiday period in the US so we're catching back up on issues.

The popup issue is a known one- there's a very large list of rules, and it takes a long time to load them all. We need to do some work so that window only responds to queries rather than trying to load the whole thing.

**Comment by jeremyn** [comment]
@sirald66 The UI seems to have changed so this is no longer a problem, so I'm closing this issue. Please feel free to reopen it with a comment if the problem still exists for you.
