### ISSUE TITLE
Entertainment Weekly rule doesn't work

### ISSUE THREAD

**Issue by aladar42** [EFForg/https-everywhere#8657]
HTTPS Everywhere 5.2.11 currently does not work with ew.com, all of the requests go straight to HTTP version of the site, even though the ruleset seems to be present.

**Comment by oscitancy** [comment]
This is due to mixed content on the ew.com page. Images from wordpress domains.
i0.wp.com
i1.wp.com
i2.wp.com

This is similar behaviour on both Chrome and Firefox.

https://github.com/EFForg/https-everywhere/issues/2389
https://bugs.chromium.org/p/chromium/issues/detail?id=122548
https://bugzilla.mozilla.org/show_bug.cgi?id=418354

You aren't crazy :) The rules are fine and valid, and they are working. Certificates for both ew.com and wp.com are fine too. if you load ew.com with Chrome it does show the green padlock for a split second until it sees the mixed content. This is just due to the way Chrome and firefox work for mixed content regardless of extensions rewriting requests. Best bet is to ask the Entertainment Weekly devs to change their images to https.

**Comment by aladar42** [comment]
I'm not sure if I'm misunderstanding something, but on my end, the connection never goes to https:// on Firefox, unless I type the URL manually. Then I get the mixed content warning. But just typing ew.com on Firefox sends me to the plain http site.

**Comment by oscitancy** [comment]
There is an experimental rule for Entertainment Weekly that you can enable if you click the extension icon. Just check the check box to turn it on for Entertainment weekly then it will work.

**Comment by pipboy96** [comment]
Can no longer reproduce, website works correctly over HTTPS.
