### ISSUE TITLE
Edit CONTRIBUTING.md w/ better instructions how to become a ruleset maintainer

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#9111]
The current process in `CONTRIBUTING.md` is pretty much "contact us":

https://github.com/EFForg/https-everywhere/commit/5609071840e4016c5ed2859d0e99ffb328517b3c

@jgillula suggests:

> One thing we might want to add is a section with more detail about how
> to be a ruleset maintainer--what to look for, what to test, etc. I think
> even just a couple sentences that refer to the testing and style
> sections saying "refer to these sections" would be useful.

We should also encourage people from different regions of the world and non-English speakers to become ruleset maintainers, who can judge if pages are being served correctly in the transition to HTTPS.

**Comment by jeremyn** [comment]
The pattern I'd like to see is for would-be ruleset maintainers to, as they feel comfortable, comment on pull requests by providing guidance, criticism etc to contributors just like actual ruleset maintainers do. Then they can ping an actual maintainer for final approval of the pull request. This way they can get practice and guidance, and the current maintainers can develop some trust in them.

**Comment by Bisaloo** [comment]
Slightly related:

I am not a maintainer and I am not looking to become one at the moment. How helpful is it for you if I go ahead and help people who have trouble with travis tests failing for example?

I do it sometimes and I want to do it more often but if that's making it more difficult for maintainers, I'd rather not.

**Comment by jeremyn** [comment]
Anything you can do to get a pull request into mergeable shape would be helpful. In particular, handling the sometimes tedious discussions with novice contributors regarding bad formatting, many missing subdomains, interpreting documentation etc would be great.

**Comment by bardiharborow** [comment]
@Hainish I've being watching this repo for a little while now, and I guess I'm an aspiring ruleset maintainer so I thought I'd weigh in with some random thoughts:

1. I've found the documentation mostly manageable, but there are a few shortcomings (e.g. discussion around how to correctly construct and test `securecookie` rules).
2. I've been wondering why there doesn't seem to be a `/utils` program that takes a list of subdomains and builds rules for all the passing subdomains, automatically creating a note in the comments about any failing subdomains.
3. There seem to be a number of different "standard" comment formats that indicate to me that maybe such a program does exist or at least iterations of one have existed in the past, but I can't find documentation of such.
4. I went through the ruleset coverage checker looking for a timestamp controlling the [February 2015 coverage whitelist](https://github.com/EFForg/https-everywhere/blob/a27cd74fceb65af1da1f0393582288ec727b09ef/test/rules.sh#L35), and I haven't found one. I'm assuming that all relevant files are just in the main `utils/ruleset-whitelist.csv`. Is fixing rulesets and removing them from `ruleset-whitelist.csv` helpful? (e.g. #11697)
5. Would it be a good use of my time to help write some more scripts to make bulk changes/cleanup to rulesets, and if so what areas would you be interested in me focusing on.

**Comment by Bisaloo** [comment]
>- I've been wondering why there doesn't seem to be a /utils program that takes a list of subdomains and builds rules for all the passing subdomains, automatically creating a note in the comments about any failing subdomains.
>- There seem to be a number of different "standard" comment formats that indicate to me that maybe such a program does exist or at least iterations of one have existed in the past, but I can't find documentation of such.

https://github.com/EFForg/https-everywhere/issues/7691, nothing official though.

**Comment by jeremyn** [comment]
@bardiharborow I'm a ruleset maintainer and I appreciate your interest.

To give some background, as far as I can tell there are about five or less active participants in the project with commit access, including one paid EFF staff programmer/researcher ( @Hainish ), and unpaid volunteers who do ruleset maintenance. @Hainish has other EFF responsibilities outside of this project, and the volunteers are active at varying levels.

An important problem with the project's structure is that there is no path for non-trivial improvements from the community to be approved in advance and accepted when complete. The only one with authority is @Hainish , and he has too much to do. Getting feedback from the maintainers can be difficult because we are not obligated to participate. The technical challenge of writing a semi-automated ruleset creator shouldn't be too hard for an experienced programmer, but it requires buy-in from @Hainish and the ruleset maintainers and the project just isn't equipped to provide that. The result is issue https://github.com/EFForg/https-everywhere/issues/7691 that @Bisaloo linked where you have a bunch of people solving the problem separately and none of them in a way that quite matches what maintainers want. At a higher level, the result is that unless your pull request just modifies rulesets, it's not entirely clear how to get it approved, and even then you might wait indefinitely.

If you want to maximize the usefulness of your time then I recommend you dive into messy issues and (especially) PRs and just start helping. You can do this immediately even without official commit access by doing what I wrote in https://github.com/EFForg/https-everywhere/issues/9111#issuecomment-287239772, which is just to get started talking to people to improve their PRs and then asking official maintainers to push the merge button.

There are over seven billion people who can submit PRs but only about five who can approve them, so being part of the five is obviously more useful. Also, maintainers and regular contributors often get involved because of positive experiences they have as casual contributors, so working on others' PRs is good for this reason too.

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/commit/04b4e1df08543be683655c67652b8d337d61daf7 incorporates the suggestion in https://github.com/EFForg/https-everywhere/issues/9111#issuecomment-287239772 in a little bit more succinct form.
