### ISSUE TITLE
Test page to see reaction ssl-observatory to the MITM attack?

### ISSUE THREAD

**Issue by kronblase** [EFForg/https-everywhere#9135]
Is there a test resource on which one could see the response of the ssl observatory to the mitm attack?

**Comment by jeremyn** [comment]
Not that I know of, but this might be a good test case to add to https://badssl.com , from https://github.com/chromium/badssl.com.

@Hainish What do you think? Is this something I can help with?

**Comment by kronblase** [comment]
I tried this before, but I did not understand how to distinguish what the browser blocked from being blocked by addon. Also, I never saw that certificates would be sent. Although constantly monitoring the connection. But I already read that addon has its own offline list for checking certificates. No need to send a certificate.

**Comment by Hainish** [comment]
Currently the SSL Observatory simply collects certificates, it doesn't attempt to build the cert chain or detect validation against a root store.  Does this answer your question?  Perhaps I'm misunderstanding?

**Comment by jeremyn** [comment]
@Hainish The Observatory description in the add-on [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/locale/en/ssl-observatory.dtd#L55-L71) says:

> HTTPS Everywhere can use EFF's SSL Observatory.  This does two things: (1) sends copies of HTTPS certificates to the Observatory, to help us detect 'man in the middle' attacks and improve the Web's security; and (2) lets us warn you about insecure connections or attacks on your browser.

There's a related checkbox [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/locale/en/ssl-observatory.dtd#L47-L48):

> Show a warning when the Observatory detects a revoked certificate not caught by your browser

I, and I assume @kronblase too, would like to see a page that has this described warning.

Honestly though, I always disable SSL Observatory because I don't want to send information about what sites I'm visiting to a third party (EFF) if I can help it, so I may not understand what the Observatory does or what it looks like in normal operation.

**Comment by Hainish** [comment]
Thanks @jeremyn, I honestly haven't done a deep-dive into the DSO code yet and I've never seen HTTPS Everywhere detect revocations where the browser hasn't.  Revocation in the browsers has changed a lot in recent years, and I'm not quite sure what the utility of that checkbox actually is nowadays.  Nonetheless, I'll have to port a lot of the DSO code to WebExtensions once those APIs become available (and we're working on that currently).

**Comment by koops76** [comment]
@J0WI Close please.
