### ISSUE TITLE
Breaks "Enhanced Steam"

### ISSUE THREAD

**Issue by ourichermath** [EFForg/https-everywhere#9264]
The stable rule for Enhancedsteam.com breaks the Enhanced Steam (ES) extension in Google Chrome on steampowered.com.  When that rule is on, Enhanced Steam fails on each game's Store page (the normally green ES status indicator at the top right of the page is a red exclamation mark with three failed URLs listed).  Turning the rule off, lets the extension work correctly.  Also, on various Steam Community pages under the user's name, there's the same red exclamation mark with an error concerning https://store.steampowered.com/about/ .  Turning off the rules I can find doesn't seem to fix that, though (I'm assuming it's related to ES, but it might not be).

I've attached a screenshot of the 3 Store page errors for one particular game.
![20170314 -- enhanced steam errors](https://cloud.githubusercontent.com/assets/14967405/24336420/f0e09622-1243-11e7-8b54-5f073a148246.PNG)

Windows 10 Pro x64
Google Chrome Version 58.0.3029.33 beta (64-bit)
Enhanced Steam v 9.2 ( https://chrome.google.com/webstore/detail/enhanced-steam/okadibdjfemgnhjiembecghcbfknbfhg?utm_source=chrome-app-launcher-info-dialog )

**Comment by WilliamFeely** [comment]
I'd personally complain to Valve for forcing us to use insecure connections in their store, especially on the agecheck pages; I have PROVEN that even though they claim not to store the PII entered on those pages it is being transmitted to their servers in a manner that is insecure and anti-privacy.

**Comment by odie5533** [comment]
Enhancedsteam.com is an HTTPS Everywhere rule listed as stable. While it may be stable directly visiting their website, the whole point of their website is for people to download and use their extension, which that rule breaks. I think the rule should be moved to Experimental and disabled by default because most people going to Enhancedsteam.com are going to want to use the extension, which the rule breaks.

You can see Enhancedsteam extension users complaining about the rule here: https://github.com/jshackles/Enhanced_Steam_Firefox/issues/101

**Comment by seeeeew** [comment]
The conflicts between HTTPS Everywhere and Enhanced Steam are mostly resolved in version 9.6, which was just released. This is probably as good as it can get without Steam fixing things on their end.
(see jshackles/Enhanced_Steam#1452)

**Comment by Bisaloo** [comment]
As far as I can tell, this should indeed be fixed by https://github.com/jshackles/Enhanced_Steam/pull/1452. Closing this issue. Feel free to let me know if you are still having issues.
