### ISSUE TITLE
Wikia not HTTPS

### ISSUE THREAD

**Issue by rtnielson** [EFForg/https-everywhere#9364]
HTTPS Everywhere is not working with any Wikia sites, and that is a large amount of sites. Upon visiting any sites, it seems the rule is disabled by default.

Clicking the rule to toggle it on then refreshing, the site still remains HTTP.

**Comment by advaith1** [comment]
There is no more Wikia rule, because Wikia does not support TLS.

It is not a matter of HTTPS everywhere not working, the site simply does not support TLS, and there is nothing anyone else can do about it.

**Comment by TheFinalCut83** [comment]
Wikipedia supports TLS [according to SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=en.wikipedia.org&s=208.80.153.224&hideResults=on).

**Comment by TheFinalCut83** [comment]
Wikia supports TLS [according to SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=wikia.com&s=151.101.64.194&latest).

**Comment by advaith1** [comment]
@TheFinalCut83 Well if you try it, it just redirects back to http://.

**Comment by gloomy-ghost** [comment]
[Wikia.xml](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Wikia.xml) is disabled because most pages redirect back to http. They still use https for login though, if anyone want to address that in the ruleset feel free to do so. Closing this issue for now as the website doesn't support https.
