### ISSUE TITLE
In FAQ, add more info on reaching out to site owners

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#9467]
In response to an inquiry, I suggested:

> I think it's perfectly fine for people to write site admins explaining why
> HTTPS is important.  I don't think we want this as part of the extension  
> itself (too pushy and seems misplaced) but perhaps somewhere in the FAQ.

**Comment by jeremyn** [comment]
It would be nice to clarify the relationship we want with site owners. We've generally been very accommodating to site owners, however my experience with them has usually been that if there is any ambiguity or difficulty, they would prefer that we not include their site in the add-on. This makes sense if you think about it: HTTPS Everywhere can break the experience for users, break ads, and is outside of the site's direct control and requires a technical person's time to work with us to fix problems. They can use HSTS if they want what HTTPS Everywhere does.

**Comment by Hainish** [comment]
We can specify this in the FAQ and perhaps this belongs in `CONTRIBUTING.md` as well.  
Something like:

> When reaching out to the site owners, ensure that they themselves are confident of the layout and longevity of their TLS deployment, and prefer to be included in HTTPS Everywhere.  Otherwise, the ruleset(s) that are created can be brittle and cause problems for users trying to access the site.

**Comment by Bisaloo** [comment]
What I really would like to see is a small email template we can use to write to website owners.

Many contributors (myself included) are not native speakers are therefore don't always convey ideas in the most clear and efficient way. 

A template explaining why `https` matters and how eventually it is to going to be mandatory (given Google and Mozilla stance on this) would help a lot with this issue.

**Comment by jeremyn** [comment]
On further thought I'm not sure what this issue/proposed FAQ update is for. When I've contacted site owners, it's because I want their help to write a rule because there is something unusual or difficult about their site. An email template wouldn't help with that because each problem is unique.

We don't need to email site owners about why HTTPS is important. The tech people at these sites that we talk to know about HTTPS and why it's important, they want to support it, and they are competent enough to do it. However unless the site is trivially small or was built from the start to support HTTPS, actually deploying HTTPS is complicated by stuff like CDNs, ad networks, analytics, competing business needs, testing requirements etc. Emailing them a beginner's level description of HTTPS when they are already fighting the HTTPS battle with their management and customers will not help.

**Comment by jeremyn** [comment]
Also, of course, we are only able to create rulesets for sites because those sites have already gone to the trouble of at least partially supporting HTTPS. We are always building on the work of the site owners.

**Comment by Bisaloo** [comment]
> The tech people at these sites that we talk to know about HTTPS and why it's important, they want to support it, and they are competent enough to do it.

I don't argue with that. But I don't think site owners are necessarily the same people as site developers. You also seem to talk only about "big" websites but those are not the targets I have in mind for this kind of email.

For example, some independent news websites don't support https. It may be because they don't realise that all their traffic is in clear text. The people who run it are not always tech literate. I believe in this case, a short email saying that as a user, you would like to protect your privacy and how https helps with that would be great. Even if they are already aware of the issue, proof that it matters to their users may motivate them to focus more on it.

Then, I agree their tech are surely capable enough to take care of the technical stuff or they can easily seek help. Hence the fact I didn't mention it in my proposed points for a template.

**Comment by Hainish** [comment]
At EFF the canonical resource we've used to explain the importance of HTTPS is our "Encrypting the Web" page: https://www.eff.org/encrypt-the-web

This specifically has a "What you can do as a web site owner" section.  I would not assume that any site we're interested in adding coverage for already knows the importance of HTTPS.  Often, those offering very sensitive information just haven't thought about offering HTTPS, or don't *really* know what it provides.

I think an email template would be fine, but definitely linking site owners to the "Encrypting the Web" page is best practice.

**Comment by jeremyn** [comment]
Also keep in mind that even tiny businesses and nonprofits will have technical people involved in making the websites, often as part-time help from a consulting agency.

**Comment by Hainish** [comment]
I have a hard time trying to convince myself that the level of email traffic generated by the proportion of the population doing HTTPS ruleset contributions will reach the level of "spam".  In fact, the problem is the exact reverse.  Often, people simply don't know what HTTPS is, or what it does (even now.)  I myself have reached out to sites with sensitive content to ask them whether they'd consider adopting HTTPS, and they have personally thanked me for the tips and responded that yes, they would implement it.

This is a win, period.  If someone is annoyed by a friendly email asking them to protect their users, then so be it.  Hopefully they'll be annoyed beyond a certain threshold, to actually start protecting their users.

**Comment by Hainish** [comment]
Perhaps one of the things we can do in any new ruleset intake system (as discussed in https://github.com/EFForg/https-everywhere/issues/3069, https://github.com/EFForg/https-everywhere/issues/6322) would be to have a flag for when the last time a site owner has been reached out to.  This way that owner won't accidentally get multiple emails asking them to move their site to HTTPS.  I honestly don't see this as being a realistic problem, but it's not as if this is an intractable problem if people are actually worried about it

**Comment by jeremyn** [comment]
I actually don't know what this issue is for. No one needs the EFF's permission to send an email to a webmaster asking them to enable HTTPS. So what is specifically being proposed?

**Comment by Hainish** [comment]
It looks like we already do have *some* copy about how one can reach out to site owners: https://www.eff.org/https-everywhere/faq#what-if-the-site-doesnt-support-https-or-only-supports-it-for-some-activities-like-entering-credit-card-information

Drawing out this suggestion to add info about how to find site owners email addresses might be helpful, and if we do have an intake system that supports it, adding info which indicates a site owner has been contacted.

**Comment by Hainish** [comment]
I've changed the issue title accordingly

**Comment by jeremyn** [comment]
If this issue is just to encourage the EFF to share tips in the FAQ about convincing site owners to implement HTTPS, then I'm fine with that (FWIW). It may be worthwhile to add in the FAQ that

* any contact to site owners should be personalized and absolutely not mass-emailed, to provide cover for the EFF in case an over-eager privacy advocate comes up with a (web crawler+email service+simple script) spammer, and
* remind people that the person reading the emails may not have any decision-making authority and may in fact already be on-board with HTTPS and so the person sending the email should not, you know, be mean about it.

I'm sure you @Hainish and others at the EFF can judge well enough whether these problems are important enough or likely enough to mention.

**Comment by zoracon** [comment]
Closing for now, we offer guidance on how a site owner can upgrade their site. There's no streamlined way to currently contact site owners. Been thinking of how we can do that, but so far, tools like Let's Encrypt do a good job for those who may have been routed thanks to Chrome and FireFox having proper indications in place that one's site is not secure. API calls are starting to fail, mixed content is being blocked now, etc.
