### ISSUE TITLE
Audit CACert rulesets

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#9582]
Since Let's Encrypt has been launched some `platform="cacert"` may need an update to be enabled for all users.

**Comment by clairew** [comment]
Hi @J0WI, this is my first time contributing to open source. Would like some pointers on how to get started with this task! Could you elaborate? Thank you so much, and sorry if I'm asking for a lot of details.

**Comment by J0WI** [comment]
Thanks for picking up this task!
First I recommend to read our [CONTRIBUTING.md](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md). We have some quality standards for rulesets.

Then you can choose any ruleset that contains `platform="cacert"`. If the ruleset already uses our current code style, you can just update it. If not, you need to rewrite those parts to pass our automated tests.
[`Toofishes.net.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Toofishes.net.xml) seems to be an easy one to start with.

Please use a separate branch/PR for each ruleset if they are not related.

**Comment by clairew** [comment]
Thanks for the pointers!

**Comment by cschanaj** [comment]
I have made a very simple script to test the hosts in `cacert` rulesets. (since the script is so simple, I will assume there are false results). thanks.

```bash
#!/bin/bash

REGEX1='platform=\"cacert\"'
REGEX2='<target host= *\"\([-.a-zA-Z0-9]*\)\" \?\/>'
REGEX3='s/^[\t ]*<target host= *\"\([-.a-zA-Z0-9]*\)\" \?\/> *$/\1/g'

OUTPUT_PHASE1='/tmp/cacert_flist.txt'
OUTPUT_PHASE2='/tmp/target_hlist.txt'
OUTPUT_PHASE3='./output_list.txt'

# Fetch the current master
git clone 'https://github.com/EFForg/https-everywhere.git'

# Collect the list of file containing "platform=\"cacert\""
grep -l "$REGEX1" ./https-everywhere/rules/*.xml > "$OUTPUT_PHASE1"

# Obtain the first target
while read rfile;
do
	grep "$REGEX2" "$rfile" | sed "$REGEX3" | head -n 1
done < "$OUTPUT_PHASE1" > "$OUTPUT_PHASE2"

while read host;
do
	curl -s -o /dev/null "https://$host" && echo "$host" 
done < "$OUTPUT_PHASE2" > "$OUTPUT_PHASE3"
``` 
Out of 105 `cacert` rulesets, I suspect that 62 of them can be enabled (after auditing, of course) for all users.

6xq.net
allmend.ch
alloscomp.com
anonbox.net
api.bitcoincharts.com
bitcoin-contact.org
mail.bluepoint.com.ph
www.c-base.org
chaox.net
clearchain.com
www.clear-code.com
ccodearchive.net
cypouz.com
webirc.darkfasel.net
bugs.exherbo.org
fuskator.com
habets.se
hackover.de
hands.com
casper.infradead.org
www.init7.net
lists.linux.it
lists.itnog.it
jolexa.net
josefsson.org
kubieziel.de
l0cal.com
legtux.org
linux-dev.org
lp0.eu
lpice.eu
olasagasti.info
networktimefoundation.org
planet.nuug.no
nuug.no
op-co.de
openmandriva.org
www.open-mesh.org
orezpraw.com
rusty.ozlabs.org
parabolagnulinux.org
parabola.nu
www.pekwm.org
pro-linux.de
randombit.net
bugzilla.rpmfusion.org
config.schmidtcom.de
honk.sigxcpu.org
sipsolutions.net
stuvel.eu
svn.python.org
piwik.sysmocom.de
tip.net.au
tog.ie
toofishes.net
www.ubuntu-nl.org
umeahackerspace.se
trent.utfs.org
vinilox.eu
windowmaker.org
wza.us
envy.zenspider.com

**Comment by Bisaloo** [comment]
`svn.python.org` should be fixed in https://github.com/EFForg/https-everywhere/pull/5109

**Comment by Bisaloo** [comment]
@cschanaj, could you update your comment as a checkbox list to coordinate our efforts, please?

**Comment by Bisaloo** [comment]
`chaox.net` is weird. I think it's a private server (subdomains have the name of common services : git, mumble, imap, smtp, vpn, wiki, ssh, deluge, etc.) and most subdomains redirect to a bogus page for external IPs.

What should be done in this case? This ruleset will most likely have zero use.

**Comment by cschanaj** [comment]
I have a similar question too. Some of the above sites like `ip0.eu` serves little to no content and most of its sub-domains simply perform redirections. I see little values of it to most of our user since `ip0.eu` is not even on top-1m list. Personally, I prefer a `rm` over `update` the ruleset, is there any instruction on site like this? Maybe this is related to HTTPS Everywhere coverages?

**Comment by cschanaj** [comment]
P.S. I would like to run the newly modified script after the more related PRs are merge, please do not close this immediately. thanks!

**Comment by cschanaj** [comment]
I have updated the audit list against the current `master`. Only 8 more `rulesets` require audition according to the script I used. thanks.

**Comment by Bisaloo** [comment]
`fr33tux.org` is soon to be preloaded.

https://hstspreload.org/?domain=fr33tux.org

**Comment by cschanaj** [comment]
See also https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/BufferedIO.xml, Related #9887

**Comment by cschanaj** [comment]
I would like to note that issue can be closed once the pending PRs #9707, #9767, #7937 and #10069 are merged.  Thanks.

**Comment by Bisaloo** [comment]
- [ ] https://www.stack.nl
- [ ] https://osmocom.org
- [ ] https://ccc.de
- [ ] https://blog.websterwood.com

**Comment by koops76** [comment]
#11385

**Comment by koops76** [comment]
List of all CACert rulesets: #11385

**Comment by J0WI** [comment]
Looks like this is done :tada:
