### ISSUE TITLE
bugs in opera browser

### ISSUE THREAD

**Issue by blahxblah** [EFForg/https-everywhere#990]
enter www.microsoft.com (non-english like korean, japanese, suomi...)
click link starting with "windows.microsoft.com"
![3](https://cloud.githubusercontent.com/assets/10733724/5930684/4152c1b0-a6d6-11e4-8bb3-f3cf27cb48d0.png)
then invalid certificates popup appear
![4](https://cloud.githubusercontent.com/assets/10733724/5930706/936bba88-a6d6-11e4-85ff-9fcc7c857b2e.png)
and ubuntu forum is broken
![5](https://cloud.githubusercontent.com/assets/10733724/5930736/141493b2-a6d7-11e4-94dd-64c71e29b29e.png)
it's issues only in opera browser.

**Comment by reedy** [comment]
There doesn't seem to be any obvious evidence of Opera code (even packaging stuff) in this repo/master.

https://addons.opera.com/en/extensions/details/https-everywhere/?display=en

Not sure who actually maintains this. But it does say rules from FF version 4.0.3

https://github.com/EFForg/https-everywhere/blob/4.0/src/chrome/content/rules/Ubuntu_Forums.org.xml and https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Ubuntu_Forums.org.xml are the same bar comments.

**Comment by reedy** [comment]
Ok, ubuntu forums is similarly "broken" on FF and Chrome if you try and visit the page via HTTPS. But the ruleset is disabled by default in FF and Chrome (at least, in HTTPSE 2015.1.22/5.0dev2 it is). So this is just Opera not following this case. 4.0 "bug"/feature not implemented, rather than Opera specific bug?


For https://windows.microsoft.com/ko-kr/windows-8/meet, Chrome helpfully tells us "This server could not prove that it is windows.microsoft.com; its security certificate is from *.windows.microsoft.com. This may be caused by a misconfiguration or an attacker intercepting your connection.". https://windows.microsoft.com/en-gb/windows-8/meet is similarly broken. Not a Opera specific issue

**Comment by jsha** [comment]
Opera is semi-officially supported. We have it on good authority that Opera extensions are byte-for-byte compatible with Chrome, so I upload stable versions to the Opera extensions store when I do a release. However, I don't do any testing on Opera.

There are rules for both Microsoft and Ubuntu forums that are disabled for MCB. It's possible the code doesn't do the right thing in Opera with regards to disabling MCB rules? Has Opera recently enabled MCB?

**Comment by blahxblah** [comment]
Ubuntu Forums will be shown correctly when I turn off the MCB rules :D
Microsoft sites are shown correctly by checking off the Microsoft (mixed content) :)
However, this extension is the Ubuntu Forums.org (false MCB) and Microsoft (mixed content) is checked by default.
In Chrome it is unchecked by default.(same version:2015.1.22)
